import type { IntentDefinition } from "./types";

export const publicIntentRegistry: IntentDefinition[] = [
  {
    intentId: "start_request",
    label: "Start",
    category: "discovery",
    actionId: "open_workspace",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["start me", "i want to start", "أريد أبدأ"],
    responseRule: "Route to the paper-safe workspace and explain Free active truth.",
  },
  {
    intentId: "open_workspace_request",
    label: "Open workspace",
    category: "workspace",
    actionId: "open_workspace",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["open the workspace", "open the chart", "افتح الشارت"],
    responseRule: "Open or point to Trading Workspace without public nav clutter.",
  },
  {
    intentId: "chart_comfort_request",
    label: "Bigger chart",
    category: "chart",
    actionId: "bigger_chart",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["make the chart bigger", "bigger chart", "كبر الشارت"],
    responseRule: "Explain Chart Comfort as layout-only and ask confirmation if applying.",
  },
  {
    intentId: "calm_ui_request",
    label: "Calmer interface",
    category: "personal_reality",
    actionId: "make_calmer",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["make it calmer", "less noise", "اجعل المنصة أهدأ"],
    responseRule: "Offer Calm Workspace, Low Motion, and cleaner chart surroundings.",
  },
  {
    intentId: "focus_request",
    label: "Focus",
    category: "workspace",
    actionId: "personal_reality_request",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["focus", "focus workspace", "أريد تركيز"],
    responseRule: "Explain chart-first focus as a confirmed workspace preference.",
  },
  {
    intentId: "reduce_motion_request",
    label: "Low motion",
    category: "accessibility",
    actionId: "reduce_motion",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["reduce motion", "low motion", "قلل الحركة"],
    responseRule: "Guide Low Motion without disabling safety copy.",
  },
  {
    intentId: "static_mode_request",
    label: "Static Mode",
    category: "environment",
    actionId: "static_mode",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["static mode", "night mode", "أريد الوضع الثابت"],
    responseRule: "Guide Static Mode and remind that time/weather/session are not trading advice.",
  },
  {
    intentId: "high_contrast_request",
    label: "High Contrast",
    category: "accessibility",
    actionId: "high_contrast",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["high contrast", "more contrast"],
    responseRule: "Guide High Contrast as active accessibility support.",
  },
  {
    intentId: "apps_platforms_request",
    label: "Apps / Platforms",
    category: "apps_platforms",
    actionId: "where_mobile_app",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["where is the mobile app", "desktop app", "أين تطبيق الموبايل"],
    responseRule: "Explain Web current, Desktop/Mobile planned, Tablet future, no fake downloads.",
  },
  {
    intentId: "support_request",
    label: "Support",
    category: "support",
    actionId: "how_to_get_support",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["support", "help me", "أريد دعم"],
    responseRule: "Route to Help Center, report problem, security contact, or partnership contact readiness.",
  },
  {
    intentId: "academy_request",
    label: "Academy",
    category: "learning",
    actionId: "learning_path",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["help me learn", "academy", "أريد أتعلم"],
    responseRule: "Suggest a paper-safe learning path.",
  },
  {
    intentId: "journal_request",
    label: "Journal",
    category: "learning",
    actionId: "how_to_use_journal",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["open journal", "journal", "افتح Journal"],
    responseRule: "Suggest a paper-session reflection prompt.",
  },
  {
    intentId: "coach_request",
    label: "Coach",
    category: "learning",
    actionId: "how_to_use_coach",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["coach", "open coach"],
    responseRule: "Suggest a non-advisory Coach prompt.",
  },
  {
    intentId: "plans_request",
    label: "Plans",
    category: "plan",
    actionId: "explain_pro",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["plans", "explain plans"],
    responseRule: "Explain Free active, Pro/VIP planned, Institutional future.",
  },
  {
    intentId: "explain_free_request",
    label: "Explain Free",
    category: "plan",
    actionId: "explain_paper_safe",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["explain free", "what is free"],
    responseRule: "Explain Free as complete, paper-safe, and active.",
  },
  {
    intentId: "explain_pro_request",
    label: "Explain Pro",
    category: "plan",
    actionId: "explain_pro",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["explain pro", "what is pro"],
    responseRule: "Explain Pro as planned professional depth.",
  },
  {
    intentId: "explain_vip_request",
    label: "Explain VIP",
    category: "plan",
    actionId: "explain_vip",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["explain vip", "vip theme"],
    responseRule: "Explain VIP as planned premium depth without profit promises.",
  },
  {
    intentId: "explain_institutional_request",
    label: "Explain Institutional",
    category: "plan",
    actionId: "explain_institutional",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["explain institutional", "institutional"],
    responseRule: "Explain Institutional as future formal readiness.",
  },
  {
    intentId: "why_blocked_request",
    label: "Why blocked?",
    category: "blocked",
    actionId: "explain_why_locked",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["why blocked", "why locked", "لماذا هذا مقفل"],
    responseRule: "Explain blocked, planned, locked, inactive, or future state with safe alternative.",
  },
  {
    intentId: "paper_safe_request",
    label: "Paper-safe",
    category: "safety",
    actionId: "explain_paper_safe",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["what is paper-safe", "paper safe", "ما معنى paper-safe"],
    responseRule: "Explain paper-safe rehearsal and no real-money routing.",
  },
  {
    intentId: "environment_request",
    label: "Adaptive Atmosphere",
    category: "environment",
    actionId: "personal_reality_request",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["environment", "solar theme", "weather theme"],
    responseRule: "Explain atmosphere controls as visual only, privacy-safe, and not trading advice.",
  },
  {
    intentId: "reset_experience_request",
    label: "Reset experience",
    category: "personal_reality",
    actionId: "reset_experience",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["reset experience", "restore defaults", "أعد الإعدادات الافتراضية"],
    responseRule: "Return to Clean Earth defaults without activating anything.",
  },
  {
    intentId: "blocked_safety_request",
    label: "Blocked request",
    category: "blocked",
    actionId: "enable_live",
    publicVisible: true,
    privateOnly: false,
    examplePhrases: ["enable live", "real money", "activate billing"],
    responseRule: "Block unsafe requests and offer safe alternatives.",
  },
];

export const privateIntentRegistry: IntentDefinition[] = [
  {
    intentId: "alkon_status_request",
    label: "Alkon status",
    category: "founder_private",
    actionId: "expose_alkon",
    publicVisible: false,
    privateOnly: true,
    examplePhrases: ["alkon status", "الكون"],
    responseRule: "Private Founder-only readiness; never public.",
  },
  {
    intentId: "codex_draft_request",
    label: "Codex draft",
    category: "founder_private",
    actionId: "expose_codex",
    publicVisible: false,
    privateOnly: true,
    examplePhrases: ["codex draft", "build draft"],
    responseRule: "Private Founder-only draft readiness; no execution.",
  },
  {
    intentId: "task_passport_request",
    label: "Task Passport",
    category: "founder_private",
    actionId: "expose_codex",
    publicVisible: false,
    privateOnly: true,
    examplePhrases: ["task passport"],
    responseRule: "Private Founder-only task review packet.",
  },
  {
    intentId: "tribunal_request",
    label: "Result Tribunal",
    category: "founder_private",
    actionId: "expose_codex",
    publicVisible: false,
    privateOnly: true,
    examplePhrases: ["result tribunal"],
    responseRule: "Private Founder-only validation review.",
  },
  {
    intentId: "memory_lesson_request",
    label: "Memory lesson",
    category: "founder_private",
    actionId: "expose_codex",
    publicVisible: false,
    privateOnly: true,
    examplePhrases: ["memory lesson", "product memory"],
    responseRule: "Private Founder-only safe memory summary.",
  },
];

export function getPublicIntentRegistry() {
  return publicIntentRegistry;
}

export function getPrivateIntentRegistry() {
  return privateIntentRegistry;
}

export function getUserIntentRegistry() {
  return [...publicIntentRegistry, ...privateIntentRegistry];
}
