import { boundary, entity, evidence, purpose, risk } from "./helpers";
import type { ExistenceEntity } from "./types";

export function getCodebaseExistenceEntities(): ExistenceEntity[] {
  return [
    entity({
      id: "code_app_routes",
      name: "app/",
      path: "app/",
      type: "code_folder",
      owner: "public_pro_max",
      purpose: purpose("Next.js App Router public, private, and API surfaces.", true, "/ and /trading are public reality; /founder/* stays private."),
      visibility: "invisible_internal",
      evidence: evidence("present", ["tests/regression/alkon-permission-to-exist.spec.ts"], ["reports/alkon-codebase-existence-classification.md"], []),
      lifecycle: "active",
      nextFate: "keep",
    }),
    entity({
      id: "code_app_founder_routes",
      name: "app/founder/",
      path: "app/founder/",
      type: "code_folder",
      owner: "private_alkon_minus_zero",
      purpose: purpose("Private Founder-only Alkon routes.", true, "Founder surfaces may show Alkon -0 internals."),
      visibility: "private_founder_only",
      evidence: evidence("present", ["tests/regression/alkon-permission-to-exist.spec.ts"], ["reports/alkon-codebase-existence-classification.md"], ["test-results/alkon-permission-to-exist/existence-architecture-panel.png"]),
      lifecycle: "active",
      nextFate: "protect",
    }),
    entity({
      id: "code_modules_public_shell",
      name: "modules/shell and public product components",
      path: "modules/",
      type: "code_folder",
      owner: "public_pro_max",
      purpose: purpose("Public Pro Max Center shell and Pro Max Trading cockpit UI.", true, "The public shell and Trading cockpit are the first living product surface."),
      visibility: "public_safe",
      boundary: boundary({ publicExposureAllowed: true }),
      evidence: evidence("present", ["tests/regression/pro-max-trading-clean-zero-rebuild.spec.ts"], ["reports/pro-max-world-status.md"], ["test-results/alkon-total-root-to-reality-rebirth/trading-route-pro-max-trading.png"]),
      lifecycle: "active_with_notes",
      nextFate: "improve",
    }),
    entity({
      id: "code_founder_command_modules",
      name: "modules/founder-command/",
      path: "modules/founder-command/",
      type: "code_folder",
      owner: "private_alkon_minus_zero",
      purpose: purpose("Private Alkon command panels and Founder-only operating room.", true, "Founder Command receives Kernel, Jar, Permission-to-Exist, and evidence snapshots."),
      visibility: "private_founder_only",
      evidence: evidence("present", ["tests/regression/alkon-permission-to-exist.spec.ts"], ["reports/alkon-component-existence-map.md"], ["test-results/alkon-permission-to-exist/existence-gate-panel.png"]),
      lifecycle: "active_with_notes",
      nextFate: "improve",
    }),
    entity({
      id: "code_lib_server",
      name: "lib/server/",
      path: "lib/server/",
      type: "code_folder",
      owner: "invisible_operating_layer",
      purpose: purpose("Server-only operating layer for product truth, private Alkon systems, reports, and classifiers.", true, "It translates private reality into public-safe state."),
      visibility: "invisible_internal",
      evidence: evidence("present", ["tests/regression/verified-platform-truth.spec.ts"], ["reports/alkon-code-cohesion-audit.md"], []),
      lifecycle: "active",
      nextFate: "protect",
    }),
    entity({
      id: "code_existence_architecture",
      name: "lib/server/existence-architecture/",
      path: "lib/server/existence-architecture/",
      type: "code_folder",
      owner: "private_alkon_minus_zero",
      purpose: purpose("Permission-to-Exist model, classifiers, Jar mapping, and gate engine.", true, "Prevents future clutter from entering ALKON without proof."),
      visibility: "private_founder_only",
      evidence: evidence("present", ["tests/regression/alkon-permission-to-exist.spec.ts"], ["reports/alkon-permission-to-exist-status.md"], []),
      lifecycle: "active_with_notes",
      nextFate: "keep",
    }),
    entity({
      id: "code_tools_builder",
      name: "tools/",
      path: "tools/",
      type: "code_folder",
      owner: "tools_builder",
      purpose: purpose("Local builder tools and read-only operational helpers.", false, "Builder work must remain local and no-execution from web."),
      visibility: "tool_local_only",
      evidence: evidence("documented_reason", [], ["reports/origin-clean-ownership-map.md"], []),
      lifecycle: "active_with_notes",
      nextFate: "protect",
    }),
    entity({
      id: "code_docs",
      name: "docs/",
      path: "docs/",
      type: "code_folder",
      owner: "docs_reports",
      purpose: purpose("Doctrine, law, and product architecture memory.", true, "No build law survives without docs."),
      visibility: "docs_reports_only",
      evidence: evidence("present", [], ["reports/alkon-codebase-existence-classification.md"], []),
      lifecycle: "active",
      nextFate: "keep",
    }),
    entity({
      id: "code_reports",
      name: "reports/",
      path: "reports/",
      type: "code_folder",
      owner: "docs_reports",
      purpose: purpose("Wake reports, architecture maps, and evidence memory.", true, "No closure without current reports."),
      visibility: "docs_reports_only",
      evidence: evidence("present", [], ["reports/alkon-permission-to-exist-status.md"], []),
      lifecycle: "active",
      nextFate: "keep",
    }),
    entity({
      id: "code_tests",
      name: "tests/",
      path: "tests/",
      type: "code_folder",
      owner: "tests_evidence",
      purpose: purpose("Regression proof and guard tests.", true, "No closure without tests and visual proof."),
      visibility: "test_evidence_only",
      evidence: evidence("present", ["npm run test:regression"], ["reports/alkon-last-full-report.md"], []),
      lifecycle: "active",
      nextFate: "keep",
    }),
    entity({
      id: "code_public_assets",
      name: "public/",
      path: "public/",
      type: "code_folder",
      owner: "public_assets",
      purpose: purpose("Approved public static assets only.", false, "No raster assets or unknown-license assets may enter public without approval."),
      visibility: "public_asset_only",
      risk: risk("medium", "Public assets can leak unapproved media if not gated.", ["asset license", "raster policy"]),
      evidence: evidence("present", ["tests/regression/alkon-permission-to-exist.spec.ts"], ["reports/alkon-codebase-existence-classification.md"], []),
      lifecycle: "protected",
      nextFate: "protect",
    }),
  ];
}
