import { boundary, entity, evidence, purpose, risk } from "./helpers";
import type { ExistenceEntity } from "./types";

export function getComponentExistenceEntities(): ExistenceEntity[] {
  return [
    entity({
      id: "component_public_shell_header",
      name: "Public shell, header, logo, Sign in",
      path: "modules/shell/components/PublicAppShell.tsx modules/brand/*",
      type: "component",
      owner: "public_pro_max",
      purpose: purpose("Public Pro Max navigation and identity.", true, "Users enter Pro Max Center and Pro Max Trading without private leakage."),
      visibility: "public_safe",
      boundary: boundary({ publicExposureAllowed: true }),
      evidence: evidence("present", ["tests/regression/pro-max-trading-clean-zero-rebuild.spec.ts"], ["reports/alkon-component-existence-map.md"], []),
      lifecycle: "active",
      nextFate: "keep",
    }),
    entity({
      id: "component_home_center",
      name: "Pro Max Center Home",
      path: "app/page.tsx modules/product/components/*",
      type: "component",
      owner: "public_pro_max",
      purpose: purpose("Public center and first-heart entry.", true, "Home explains Pro Max Center and routes to /trading."),
      visibility: "public_safe",
      boundary: boundary({ publicExposureAllowed: true }),
      evidence: evidence("present", ["tests/regression/alkon-permission-to-exist.spec.ts"], ["reports/alkon-component-existence-map.md"], ["test-results/alkon-permission-to-exist/public-home-clean.png"]),
      lifecycle: "active",
      nextFate: "keep",
    }),
    entity({
      id: "component_trading_cockpit",
      name: "Trading cockpit, chart, execution, Assistant, Journal/Coach",
      path: "modules/shell/components/TradingWorkstation.tsx",
      type: "component",
      owner: "public_pro_max",
      purpose: purpose("First living product cockpit.", true, "Chart, paper execution, Assistant, and Journal/Coach serve Pro Max Trading."),
      visibility: "public_safe",
      boundary: boundary({ publicExposureAllowed: true }),
      evidence: evidence("present", ["tests/regression/alkon-total-root-to-reality-rebirth.spec.ts"], ["reports/pro-max-trading-readiness-status.md"], ["test-results/alkon-total-root-to-reality-rebirth/trading-chart-owns-page.png"]),
      lifecycle: "active_with_notes",
      nextFate: "improve",
    }),
    entity({
      id: "component_founder_command",
      name: "Founder Command panels",
      path: "modules/founder-command/components/",
      type: "component",
      owner: "private_alkon_minus_zero",
      purpose: purpose("Private Alkon command surfaces.", true, "Founder Command receives Jar, Permission-to-Exist, Kernel, and Evidence."),
      visibility: "private_founder_only",
      evidence: evidence("present", ["tests/regression/alkon-permission-to-exist.spec.ts"], ["reports/alkon-component-existence-map.md"], ["test-results/alkon-permission-to-exist/existence-architecture-panel.png"]),
      lifecycle: "active_with_notes",
      nextFate: "improve",
    }),
    entity({
      id: "component_alkon_chat_jar",
      name: "Alkon Chat and Jar panels",
      path: "modules/founder-command/components/AlkonSovereignChatInterface.tsx modules/founder-command/components/AlkonJarBuildPanel.tsx",
      type: "component",
      owner: "private_alkon_minus_zero",
      purpose: purpose("Private command mind and execution intake filter.", true, "Ahmad can ask, judge, classify, and prepare without execution."),
      visibility: "private_founder_only",
      evidence: evidence("present", ["tests/regression/alkon-total-root-to-reality-rebirth.spec.ts"], ["reports/alkon-component-existence-map.md"], ["test-results/alkon-total-root-to-reality-rebirth/jar-build-panel.png"]),
      lifecycle: "active",
      nextFate: "protect",
    }),
    entity({
      id: "component_duplicate_visual_layers",
      name: "Duplicate or stale rendered component pattern",
      path: "rendered duplicate shell/header/card walls",
      type: "component",
      owner: "unknown_needs_ahmad",
      purpose: purpose("Cleanup candidate pattern, not a product surface.", false, "Duplicate rendered UI must be classified before it grows."),
      visibility: "unknown",
      risk: risk("medium", "Duplicate UI can create public/private confusion.", ["duplicate", "stale visual"]),
      evidence: evidence("missing", [], ["reports/visual-duplicate-layer-map.md"], []),
      lifecycle: "cleanup_candidate",
      nextFate: "needs_ahmad_decision",
      requiresAhmad: true,
    }),
  ];
}
