import { entity, evidence, purpose, risk } from "./helpers";
import type { ExistenceEntity } from "./types";

export function getCssExistenceEntities(): ExistenceEntity[] {
  return [
    entity({
      id: "css_public_pro_max_visual_source",
      name: "Public Pro Max visual source",
      path: "app/theme-localization.css public shell sections",
      type: "css_layer",
      owner: "public_pro_max",
      purpose: purpose("Earth-native public Pro Max visual language.", true, "Public Home and /trading stay related but not private."),
      visibility: "public_safe",
      evidence: evidence("present", ["tests/regression/public-shell-earth-visual-correction.spec.ts"], ["reports/alkon-css-existence-map.md"], []),
      lifecycle: "active_with_notes",
      nextFate: "improve",
    }),
    entity({
      id: "css_trading_cockpit_visual_source",
      name: "Trading cockpit visual source",
      path: "app/theme-localization.css clean-zero workspace block",
      type: "css_layer",
      owner: "public_pro_max",
      purpose: purpose("Chart-first Pro Max Trading cockpit layout.", true, "Chart owns the page and execution remains attached."),
      visibility: "public_safe",
      evidence: evidence("present", ["tests/regression/pro-max-trading-clean-zero-rebuild.spec.ts"], ["reports/alkon-css-existence-map.md"], ["test-results/alkon-total-root-to-reality-rebirth/trading-ultrawide-no-empty-right.png"]),
      lifecycle: "active_with_notes",
      nextFate: "protect",
    }),
    entity({
      id: "css_private_alkon_visual_source",
      name: "Private Alkon command visual source",
      path: "app/theme-localization.css founder/private classes",
      type: "css_layer",
      owner: "private_alkon_minus_zero",
      purpose: purpose("Private sovereign Founder-only command styling.", true, "Alkon -0 and Founder Command must not look public."),
      visibility: "private_founder_only",
      evidence: evidence("present", ["tests/regression/alkon-permission-to-exist.spec.ts"], ["reports/alkon-css-existence-map.md"], ["test-results/alkon-permission-to-exist/existence-gate-panel.png"]),
      lifecycle: "active_with_notes",
      nextFate: "improve",
    }),
    entity({
      id: "css_old_language_theme_controls",
      name: "Old language/theme/header control styles",
      path: "app/theme-localization.css legacy control classes",
      type: "css_layer",
      owner: "inbox_needs_sorting",
      purpose: purpose("Compatibility styles awaiting cleanup classification.", false, "Old controls must not reappear in public header."),
      visibility: "invisible_internal",
      risk: risk("medium", "Stale CSS can override clean public layout.", ["stale css", "public clutter"]),
      evidence: evidence("documented_reason", [], ["reports/visual-cleanup-candidates.md"], []),
      lifecycle: "cleanup_candidate",
      nextFate: "delete_later_after_review",
      requiresAhmad: true,
    }),
    entity({
      id: "css_raw_status_labels",
      name: "Raw status label style pattern",
      path: "visible underscore labels",
      type: "css_layer",
      owner: "inbox_needs_sorting",
      purpose: purpose("Blocked visible raw machine label pattern.", false, "Visible UI must render human labels, not raw status spam."),
      visibility: "unknown",
      risk: risk("high", "Raw labels reduce clarity and can expose internal status.", ["raw labels", "internal language"]),
      evidence: evidence("missing", [], ["reports/visual-cleanup-candidates.md"], []),
      lifecycle: "cleanup_candidate",
      nextFate: "needs_ahmad_decision",
      requiresAhmad: true,
    }),
  ];
}
