import { boundary, entity, evidence, purpose, risk } from "./helpers";
import type { ExistenceEntity } from "./types";

export function getRouteExistenceEntities(): ExistenceEntity[] {
  return [
    entity({
      id: "route_home",
      name: "/",
      path: "/",
      type: "route",
      owner: "public_pro_max",
      purpose: purpose("Pro Max Center public root.", true, "Public users start at Pro Max Center and enter Pro Max Trading."),
      visibility: "public_safe",
      boundary: boundary({ publicExposureAllowed: true }),
      evidence: evidence("present", ["tests/regression/alkon-permission-to-exist.spec.ts"], ["reports/pro-max-route-existence-map.md"], ["test-results/alkon-permission-to-exist/public-home-clean.png"]),
      lifecycle: "active",
      nextFate: "keep",
    }),
    entity({
      id: "route_trading",
      name: "Pro Max Trading / Trading Workspace",
      path: "/trading",
      type: "route",
      owner: "public_pro_max",
      purpose: purpose("Canonical Pro Max Trading / Trading Workspace route.", true, "This is the first living product and current heart."),
      visibility: "public_safe",
      boundary: boundary({ publicExposureAllowed: true }),
      evidence: evidence("present", ["tests/regression/pro-max-trading-clean-zero-rebuild.spec.ts"], ["reports/pro-max-route-existence-map.md"], ["test-results/alkon-total-root-to-reality-rebirth/trading-route-pro-max-trading.png"]),
      lifecycle: "active",
      nextFate: "keep",
    }),
    entity({
      id: "route_en_compatibility",
      name: "/en",
      path: "/en",
      type: "route",
      owner: "public_pro_max",
      purpose: purpose("Legacy compatibility route, not primary Trading identity.", true, "/trading owns canonical identity; /en remains compatibility for older tests/links."),
      visibility: "public_safe",
      boundary: boundary({ publicExposureAllowed: true }),
      evidence: evidence("documented_reason", ["tests/regression/public-header-language-disable-route-repair.spec.ts"], ["reports/pro-max-route-cohesion-result.md"], []),
      lifecycle: "active_with_notes",
      nextFate: "protect",
      notes: ["/en must not become the primary workspace identity again."],
    }),
    entity({
      id: "route_public_readiness",
      name: "/settings and /diagnostics",
      path: "/settings /diagnostics",
      type: "route",
      owner: "public_pro_max",
      purpose: purpose("Public-safe settings and diagnostics readiness surfaces.", false, "They support user trust without exposing Alkon internals."),
      visibility: "public_safe",
      boundary: boundary({ publicExposureAllowed: true }),
      evidence: evidence("present", ["tests/regression/verified-platform-truth.spec.ts"], ["reports/pro-max-route-existence-map.md"], ["test-results/alkon-permission-to-exist/diagnostics-public-safe.png"]),
      lifecycle: "active_with_notes",
      nextFate: "keep",
    }),
    entity({
      id: "route_future_public_surfaces",
      name: "/markets /plans /apps /support",
      path: "/markets /plans /apps /support",
      type: "route",
      owner: "public_pro_max",
      purpose: purpose("Public route destinations where available; otherwise public-safe readiness anchors.", false, "They must never fake readiness or expose private internals."),
      visibility: "public_safe",
      boundary: boundary({ publicExposureAllowed: true }),
      evidence: evidence("documented_reason", [], ["reports/pro-max-route-existence-map.md"], []),
      lifecycle: "readiness_only",
      nextFate: "improve",
    }),
    entity({
      id: "route_founder_alkon",
      name: "/founder/alkon",
      path: "/founder/alkon",
      type: "route",
      owner: "private_alkon_minus_zero",
      purpose: purpose("Alkon -0 private command universe.", true, "Founder-only surface may show Kernel, Jar, Evidence, and Permission-to-Exist."),
      visibility: "private_founder_only",
      evidence: evidence("present", ["tests/regression/alkon-permission-to-exist.spec.ts"], ["reports/pro-max-route-existence-map.md"], ["test-results/alkon-total-root-to-reality-rebirth/founder-alkon-minus-zero.png"]),
      lifecycle: "active",
      nextFate: "protect",
    }),
    entity({
      id: "route_founder_pocket",
      name: "/founder/pocket",
      path: "/founder/pocket",
      type: "route",
      owner: "private_alkon_minus_zero",
      purpose: purpose("Private Alkon Pocket decision center.", true, "Pocket exposes Wake Report, One Next Action, Visual Review, and Local Day One Gate only to Founder."),
      visibility: "private_founder_only",
      evidence: evidence("present", ["tests/regression/alkon-total-root-to-reality-rebirth.spec.ts"], ["reports/pro-max-route-existence-map.md"], ["test-results/alkon-total-root-to-reality-rebirth/founder-pocket-private.png"]),
      lifecycle: "active",
      nextFate: "protect",
    }),
    entity({
      id: "route_public_alkon_leak_pattern",
      name: "Public route exposing Alkon pattern",
      path: "public/* -> Alkon internals",
      type: "route",
      owner: "unknown_needs_ahmad",
      purpose: purpose("Blocked pattern for public Alkon exposure.", false, "Public Alkon exposure is P0 and cannot exist."),
      visibility: "unknown",
      risk: risk("p0", "Public Alkon exposure would violate the public/private boundary.", ["public Alkon leak", "internal governance"]),
      evidence: evidence("missing", [], ["reports/alkon-existence-blocked.md"], []),
      lifecycle: "blocked",
      nextFate: "black_hole",
      requiresAhmad: true,
    }),
  ];
}
