import type {
  PersonalRealityProfile,
  PersonalRealitySetting,
} from "./types";

export const personalRealitySettings: PersonalRealitySetting[] = [
  {
    settingId: "clean_earth",
    name: "Clean Earth",
    layer: "visual",
    description: "A clean Earth-native visual setting for the complete Free workspace.",
    availability: "active",
    allowedPlans: ["demo_free", "pro", "vip", "enterprise"],
    blockedPlans: [],
    requiresEntitlement: false,
    requiresConfirmation: false,
    publicVisible: true,
    founderVisible: true,
    safetyNotes: ["No premium-gold dominance", "Code-only visual identity"],
    productTruthNotes: ["Free remains complete", "No paid activation"],
  },
  {
    settingId: "calm_workspace",
    name: "Calm Workspace",
    layer: "workspace",
    description: "Reduces visual pressure around the chart and paper ticket.",
    availability: "active",
    allowedPlans: ["demo_free", "pro", "vip", "enterprise"],
    blockedPlans: [],
    requiresEntitlement: false,
    requiresConfirmation: false,
    publicVisible: true,
    founderVisible: true,
    safetyNotes: ["Chart remains first", "No execution change"],
    productTruthNotes: ["Paper-safe only"],
  },
  {
    settingId: "chart_comfort",
    name: "Chart Comfort",
    layer: "workspace",
    description: "Emphasizes chart size, calm grid, and fewer distractions.",
    availability: "active",
    allowedPlans: ["demo_free", "pro", "vip", "enterprise"],
    blockedPlans: [],
    requiresEntitlement: false,
    requiresConfirmation: true,
    publicVisible: true,
    founderVisible: true,
    safetyNotes: ["Layout-only change", "No order hotkeys"],
    productTruthNotes: ["No trading signal generated"],
  },
  {
    settingId: "static_mode",
    name: "Static Mode",
    layer: "accessibility",
    description: "Disables atmospheric motion and keeps a steady interface.",
    availability: "active",
    allowedPlans: ["demo_free", "pro", "vip", "enterprise"],
    blockedPlans: [],
    requiresEntitlement: false,
    requiresConfirmation: false,
    publicVisible: true,
    founderVisible: true,
    safetyNotes: ["Reduced motion respected"],
    productTruthNotes: ["No environment automation"],
  },
  {
    settingId: "low_motion",
    name: "Low Motion",
    layer: "accessibility",
    description: "Keeps atmosphere subtle and reduces movement.",
    availability: "active",
    allowedPlans: ["demo_free", "pro", "vip", "enterprise"],
    blockedPlans: [],
    requiresEntitlement: false,
    requiresConfirmation: false,
    publicVisible: true,
    founderVisible: true,
    safetyNotes: ["Motion-sensitive users remain supported"],
    productTruthNotes: ["No hidden tracking"],
  },
  {
    settingId: "high_contrast",
    name: "High Contrast",
    layer: "accessibility",
    description: "Prioritizes readable text, controls, and chart contrast.",
    availability: "active",
    allowedPlans: ["demo_free", "pro", "vip", "enterprise"],
    blockedPlans: [],
    requiresEntitlement: false,
    requiresConfirmation: false,
    publicVisible: true,
    founderVisible: true,
    safetyNotes: ["Readability over atmosphere"],
    productTruthNotes: ["No feature activation"],
  },
  {
    settingId: "learning_basics",
    name: "Learning Basics",
    layer: "learning",
    description: "Keeps Assistant and Journal/Coach prompts simple and paper-first.",
    availability: "active",
    allowedPlans: ["demo_free", "pro", "vip", "enterprise"],
    blockedPlans: [],
    requiresEntitlement: false,
    requiresConfirmation: false,
    publicVisible: true,
    founderVisible: true,
    safetyNotes: ["No financial advice", "No trade pressure"],
    productTruthNotes: ["Basic learning active"],
  },
  {
    settingId: "professional_orbit",
    name: "Professional Orbit",
    layer: "visual",
    description: "Professional orbit identity and workflow focus planned for Pro.",
    availability: "planned",
    allowedPlans: ["pro"],
    blockedPlans: ["demo_free"],
    requiresEntitlement: true,
    requiresConfirmation: true,
    publicVisible: true,
    founderVisible: true,
    safetyNotes: ["No fake Pro activation"],
    productTruthNotes: ["Pro remains planned unless entitled"],
  },
  {
    settingId: "market_session_focus",
    name: "Market Session Focus",
    layer: "workspace",
    description: "Professional session-aware focus planned for Pro.",
    availability: "planned",
    allowedPlans: ["pro"],
    blockedPlans: ["demo_free"],
    requiresEntitlement: true,
    requiresConfirmation: true,
    publicVisible: true,
    founderVisible: true,
    safetyNotes: ["Session is informational only"],
    productTruthNotes: ["No live feed implied"],
  },
  {
    settingId: "lunar_premium",
    name: "Lunar Premium",
    layer: "visual",
    description: "Premium lunar/deep-orbit atmosphere planned for VIP.",
    availability: "planned",
    allowedPlans: ["vip"],
    blockedPlans: ["demo_free", "pro"],
    requiresEntitlement: true,
    requiresConfirmation: true,
    publicVisible: true,
    founderVisible: true,
    safetyNotes: ["No performance promise", "No signal guarantee"],
    productTruthNotes: ["VIP remains planned unless entitled"],
  },
  {
    settingId: "premium_reports",
    name: "Premium Reports",
    layer: "assistant",
    description: "Advanced premium review and reports planned for VIP.",
    availability: "planned",
    allowedPlans: ["vip"],
    blockedPlans: ["demo_free", "pro"],
    requiresEntitlement: true,
    requiresConfirmation: true,
    publicVisible: true,
    founderVisible: true,
    safetyNotes: ["No guaranteed performance"],
    productTruthNotes: ["Reports are planned"],
  },
  {
    settingId: "station_mode",
    name: "Station Mode",
    layer: "workspace",
    description: "Formal team/institutional station controls for future readiness.",
    availability: "future",
    allowedPlans: ["enterprise"],
    blockedPlans: ["demo_free", "pro", "vip"],
    requiresEntitlement: true,
    requiresConfirmation: true,
    publicVisible: true,
    founderVisible: true,
    safetyNotes: ["No fake team access"],
    productTruthNotes: ["Institutional remains future"],
  },
  {
    settingId: "alkon_private_reality",
    name: "Private Command Reality",
    layer: "plan",
    description: "Internal owner-only command reality, never a public profile.",
    availability: "internal_only",
    allowedPlans: [],
    blockedPlans: ["demo_free", "pro", "vip", "enterprise"],
    requiresEntitlement: true,
    requiresConfirmation: true,
    publicVisible: false,
    founderVisible: true,
    safetyNotes: ["Never public", "No user-plan access"],
    productTruthNotes: ["Owner-only private"],
  },
];

export const personalRealityProfiles: PersonalRealityProfile[] = [
  {
    profileId: "clean",
    name: "Clean Earth",
    publicLabel: "Clean Earth",
    planRealm: "free_earth",
    visualSettings: ["clean_earth"],
    workspaceSettings: ["calm_workspace"],
    learningSettings: ["learning_basics"],
    assistantSettings: ["basic_public_safe"],
    environmentSettings: ["adaptive_atmosphere"],
    accessibilitySettings: ["low_motion", "high_contrast"],
    safetyBoundaries: ["Paper-safe", "No paid activation"],
    upgradeExplanation: "Active for Free as a complete starting reality.",
    availability: "active",
    allowedPlans: ["demo_free", "pro", "vip", "enterprise"],
    publicVisible: true,
    founderVisible: true,
  },
  {
    profileId: "calm",
    name: "Calm Workspace",
    publicLabel: "Calm Workspace",
    planRealm: "free_earth",
    visualSettings: ["clean_earth"],
    workspaceSettings: ["calm_workspace", "chart_comfort"],
    learningSettings: ["learning_basics"],
    assistantSettings: ["short_calm_responses"],
    environmentSettings: ["low_motion"],
    accessibilitySettings: ["low_motion"],
    safetyBoundaries: ["No execution change", "No trading advice"],
    upgradeExplanation: "Active for Free and safe for all plans.",
    availability: "active",
    allowedPlans: ["demo_free", "pro", "vip", "enterprise"],
    publicVisible: true,
    founderVisible: true,
  },
  {
    profileId: "chart_first",
    name: "Chart Comfort",
    publicLabel: "Chart Comfort",
    planRealm: "free_earth",
    visualSettings: ["clean_earth"],
    workspaceSettings: ["chart_comfort"],
    learningSettings: ["learning_basics"],
    assistantSettings: ["non_blocking"],
    environmentSettings: ["static_or_subtle"],
    accessibilitySettings: ["low_motion"],
    safetyBoundaries: ["Layout-only", "Paper-safe"],
    upgradeExplanation: "Active for Free; larger chart focus does not change execution.",
    availability: "active",
    allowedPlans: ["demo_free", "pro", "vip", "enterprise"],
    publicVisible: true,
    founderVisible: true,
  },
  {
    profileId: "static",
    name: "Static Mode",
    publicLabel: "Static Mode",
    planRealm: "free_earth",
    visualSettings: ["static_mode"],
    workspaceSettings: ["calm_workspace"],
    learningSettings: ["learning_basics"],
    assistantSettings: ["short_calm_responses"],
    environmentSettings: ["static_mode"],
    accessibilitySettings: ["low_motion"],
    safetyBoundaries: ["No motion", "No hidden tracking"],
    upgradeExplanation: "Active for every public plan.",
    availability: "active",
    allowedPlans: ["demo_free", "pro", "vip", "enterprise"],
    publicVisible: true,
    founderVisible: true,
  },
  {
    profileId: "high_contrast",
    name: "High Contrast",
    publicLabel: "High Contrast",
    planRealm: "free_earth",
    visualSettings: ["high_contrast"],
    workspaceSettings: ["chart_comfort"],
    learningSettings: ["learning_basics"],
    assistantSettings: ["short_calm_responses"],
    environmentSettings: ["readability_first"],
    accessibilitySettings: ["high_contrast"],
    safetyBoundaries: ["Readability first"],
    upgradeExplanation: "Active for every public plan.",
    availability: "active",
    allowedPlans: ["demo_free", "pro", "vip", "enterprise"],
    publicVisible: true,
    founderVisible: true,
  },
  {
    profileId: "professional_orbit",
    name: "Professional Orbit",
    publicLabel: "Professional Orbit",
    planRealm: "pro_orbit",
    visualSettings: ["professional_orbit"],
    workspaceSettings: ["market_session_focus"],
    learningSettings: ["advanced_journal_planned"],
    assistantSettings: ["stronger_assistant_planned"],
    environmentSettings: ["emerald_silver_orbit"],
    accessibilitySettings: ["low_motion"],
    safetyBoundaries: ["Planned unless entitled", "No fake Pro activation"],
    upgradeExplanation: "Pro controls are planned or entitlement-gated.",
    availability: "planned",
    allowedPlans: ["pro"],
    publicVisible: true,
    founderVisible: true,
  },
  {
    profileId: "lunar_premium",
    name: "Lunar Premium",
    publicLabel: "Lunar Premium",
    planRealm: "vip_lunar",
    visualSettings: ["lunar_premium"],
    workspaceSettings: ["premium_calm"],
    learningSettings: ["advanced_coach_planned"],
    assistantSettings: ["premium_reports_planned"],
    environmentSettings: ["gold_platinum_depth"],
    accessibilitySettings: ["low_motion"],
    safetyBoundaries: ["Planned unless entitled", "No performance promise"],
    upgradeExplanation: "VIP controls are planned or entitlement-gated.",
    availability: "planned",
    allowedPlans: ["vip"],
    publicVisible: true,
    founderVisible: true,
  },
  {
    profileId: "institutional_station",
    name: "Station Mode",
    publicLabel: "Station Mode",
    planRealm: "institutional_station",
    visualSettings: ["station_mode"],
    workspaceSettings: ["compliance_calm_future"],
    learningSettings: ["team_review_future"],
    assistantSettings: ["formal_reports_future"],
    environmentSettings: ["station_control"],
    accessibilitySettings: ["low_motion"],
    safetyBoundaries: ["Future only", "No fake team access"],
    upgradeExplanation: "Institutional controls remain future.",
    availability: "future",
    allowedPlans: ["enterprise"],
    publicVisible: true,
    founderVisible: true,
  },
  {
    profileId: "alkon_private",
    name: "Private Command Reality",
    publicLabel: "Private",
    planRealm: "alkon_universe",
    visualSettings: ["alkon_private_reality"],
    workspaceSettings: [],
    learningSettings: [],
    assistantSettings: ["private_founder_only"],
    environmentSettings: ["private_command"],
    accessibilitySettings: [],
    safetyBoundaries: ["Internal only", "Never public"],
    upgradeExplanation: "Private owner-only command reality, never a user plan.",
    availability: "internal_only",
    allowedPlans: [],
    publicVisible: false,
    founderVisible: true,
  },
];

export function getPublicPersonalRealitySettings() {
  return personalRealitySettings.filter((setting) => setting.publicVisible);
}

export function getPublicPersonalRealityProfiles() {
  return personalRealityProfiles.filter((profile) => profile.publicVisible);
}

export function getFounderPersonalRealityProfiles() {
  return personalRealityProfiles;
}

export function findPersonalRealitySetting(settingId: string) {
  return personalRealitySettings.find((setting) => setting.settingId === settingId);
}

export function findPersonalRealityProfile(profileId: string) {
  return personalRealityProfiles.find((profile) => profile.profileId === profileId);
}
