import "server-only";

import type { PlanetSystemOwner, PlanetSystemOwnerId } from "./types";

export const PLANET_SYSTEM_OWNERS: Record<
  PlanetSystemOwnerId,
  PlanetSystemOwner
> = {
  earth_public_world: {
    id: "earth_public_world",
    name: "Earth Public World",
    ownsSurfaces: [
      "Home",
      "Trading Workspace",
      "Markets",
      "Plans",
      "Apps / Platforms",
      "Academy",
      "Community",
      "Support",
      "Settings",
      "Diagnostics",
    ],
    ownsEventTypes: ["public_ui_crowded", "internal_term_leaked", "support_missing"],
    workers: ["public_copy_worker", "public_navigation_worker"],
    stations: ["public_ux_station", "diagnostics_station"],
    forbiddenScope: [
      "Alkon public exposure",
      "Founder Command navigation",
      "internal governance language",
      "fake plan activation",
    ],
    reportsToAlkon: true,
  },
  moon_cycle_system: {
    id: "moon_cycle_system",
    name: "Moon Cycle System",
    ownsSurfaces: ["Local Day Cycle", "Founder review cadence", "End-of-day report"],
    ownsEventTypes: ["local_day_report_needed"],
    workers: ["alkon_report_worker", "memory_lesson_worker"],
    stations: ["founder_review_station", "memory_station"],
    forbiddenScope: ["public launch authority", "automatic execution"],
    reportsToAlkon: true,
  },
  orbit_command: {
    id: "orbit_command",
    name: "Orbit Command",
    ownsSurfaces: ["Events", "Founder ideas", "Task queue", "Result status"],
    ownsEventTypes: ["generic_founder_idea", "codex_task_needed"],
    workers: ["codex_passport_worker", "alkon_report_worker"],
    stations: ["codex_station", "founder_review_station"],
    forbiddenScope: ["direct Codex execution", "shell execution from web app"],
    reportsToAlkon: true,
  },
  solar_command: {
    id: "solar_command",
    name: "Solar Command",
    ownsSurfaces: [
      "Founder vision",
      "priority law",
      "next safe direction",
      "blocked future activations",
    ],
    ownsEventTypes: ["billing_requested", "live_execution_requested"],
    workers: ["security_gate_worker", "alkon_report_worker"],
    stations: ["founder_review_station", "security_station"],
    forbiddenScope: ["production launch", "billing activation", "broker/feed activation"],
    reportsToAlkon: true,
  },
  visual_identity_planet: {
    id: "visual_identity_planet",
    name: "Visual Identity Planet",
    ownsSurfaces: ["Product logo", "Earth mark", "theme identity", "visual proof"],
    ownsEventTypes: ["logo_rejected"],
    workers: ["logo_identity_worker"],
    stations: ["design_station", "founder_review_station"],
    forbiddenScope: ["raster assets", "generated images", "public internal terms"],
    reportsToAlkon: true,
  },
  trading_workspace_planet: {
    id: "trading_workspace_planet",
    name: "Trading Workspace Planet",
    ownsSurfaces: ["Web workspace", "charts", "watchlists", "paper-safe execution"],
    ownsEventTypes: ["chart_annoying"],
    workers: ["chart_comfort_worker", "markets_worker"],
    stations: ["chart_station", "diagnostics_station"],
    forbiddenScope: ["live execution", "real money routing", "broker/feed activation"],
    reportsToAlkon: true,
  },
  assistant_planet: {
    id: "assistant_planet",
    name: "Assistant Planet",
    ownsSurfaces: ["TPM Assistant", "why blocked", "paper-safe explanations"],
    ownsEventTypes: ["generic_founder_idea", "internal_term_leaked"],
    workers: ["tpm_assistant_worker", "public_copy_worker"],
    stations: ["assistant_station"],
    forbiddenScope: ["financial advice", "signals", "profit guarantees"],
    reportsToAlkon: true,
  },
  journal_coach_planet: {
    id: "journal_coach_planet",
    name: "Journal Coach Planet",
    ownsSurfaces: ["Journal", "Coach", "decision notes", "reflection prompts"],
    ownsEventTypes: ["generic_founder_idea"],
    workers: ["journal_coach_worker", "memory_lesson_worker"],
    stations: ["assistant_station", "memory_station"],
    forbiddenScope: ["financial advice", "outcome guarantees", "private medical claims"],
    reportsToAlkon: true,
  },
  plans_realm_planet: {
    id: "plans_realm_planet",
    name: "Plans Realm Planet",
    ownsSurfaces: ["Free", "Pro", "VIP", "Institutional", "entitlements"],
    ownsEventTypes: ["generic_founder_idea", "public_ui_crowded"],
    workers: ["plan_realm_worker", "public_copy_worker"],
    stations: ["plan_realm_station", "public_ux_station"],
    forbiddenScope: ["fake paid activation", "billing activation", "Alkon as plan"],
    reportsToAlkon: true,
  },
  apps_support_planet: {
    id: "apps_support_planet",
    name: "Apps Support Planet",
    ownsSurfaces: ["Apps / Platforms", "Support", "readiness"],
    ownsEventTypes: ["support_missing"],
    workers: ["apps_platforms_worker", "support_readiness_worker"],
    stations: ["support_station"],
    forbiddenScope: ["external account creation", "sending support email"],
    reportsToAlkon: true,
  },
  academy_community_planet: {
    id: "academy_community_planet",
    name: "Academy Community Planet",
    ownsSurfaces: ["Academy", "Community", "learning readiness"],
    ownsEventTypes: ["support_missing", "generic_founder_idea"],
    workers: ["academy_worker", "community_worker"],
    stations: ["support_station", "public_ux_station"],
    forbiddenScope: ["social publishing", "fake community metrics"],
    reportsToAlkon: true,
  },
  world_interface_planet: {
    id: "world_interface_planet",
    name: "World Interface Planet",
    ownsSurfaces: ["email readiness", "social readiness", "support channels"],
    ownsEventTypes: ["world_interface_request"],
    workers: ["apps_platforms_worker", "support_readiness_worker"],
    stations: ["world_interface_station"],
    forbiddenScope: ["sending email", "posting social content", "storing tokens"],
    reportsToAlkon: true,
  },
  media_planet: {
    id: "media_planet",
    name: "Media Planet",
    ownsSurfaces: ["media readiness", "campaign drafts", "content review"],
    ownsEventTypes: ["world_interface_request", "generic_founder_idea"],
    workers: ["public_copy_worker", "alkon_report_worker"],
    stations: ["world_interface_station", "founder_review_station"],
    forbiddenScope: ["publishing", "fake followers", "unreviewed claims"],
    reportsToAlkon: true,
  },
  treasury_readiness_planet: {
    id: "treasury_readiness_planet",
    name: "Treasury Readiness Planet",
    ownsSurfaces: ["billing readiness", "plan price truth", "monetization review"],
    ownsEventTypes: ["billing_requested"],
    workers: ["security_gate_worker", "plan_realm_worker"],
    stations: ["founder_review_station", "security_station"],
    forbiddenScope: ["billing activation", "real-money routing", "fake revenue"],
    reportsToAlkon: true,
  },
  defense_universe: {
    id: "defense_universe",
    name: "Defense Universe",
    ownsSurfaces: ["security", "public boundary", "incident readiness"],
    ownsEventTypes: ["internal_term_leaked", "secret_risk", "live_execution_requested"],
    workers: ["security_gate_worker", "secrets_safety_worker"],
    stations: ["security_station", "secrets_station"],
    forbiddenScope: ["external offensive action", "secrets exposure", "auth weakening"],
    reportsToAlkon: true,
  },
  secrets_authority: {
    id: "secrets_authority",
    name: "Secrets Authority",
    ownsSurfaces: ["secret presence", "secret categories", "rotation readiness"],
    ownsEventTypes: ["secret_risk"],
    workers: ["secrets_safety_worker"],
    stations: ["secrets_station"],
    forbiddenScope: ["raw secret values", "production secrets", "sending secrets to Codex"],
    reportsToAlkon: true,
  },
  construction_universe: {
    id: "construction_universe",
    name: "Construction Universe",
    ownsSurfaces: ["Task Passport", "Codex License", "Result Tribunal"],
    ownsEventTypes: ["codex_task_needed", "generic_founder_idea"],
    workers: ["codex_passport_worker", "codex_prompt_worker", "result_tribunal_worker"],
    stations: ["codex_station", "tribunal_station"],
    forbiddenScope: ["web-app shell execution", "direct Codex call", "unscoped work"],
    reportsToAlkon: true,
  },
  memory_universe: {
    id: "memory_universe",
    name: "Memory Universe",
    ownsSurfaces: ["lessons", "validation summaries", "rejected patterns"],
    ownsEventTypes: ["local_day_report_needed", "generic_founder_idea"],
    workers: ["memory_lesson_worker", "alkon_report_worker"],
    stations: ["memory_station", "founder_review_station"],
    forbiddenScope: ["raw secrets", "private sensitive data", "fake metrics"],
    reportsToAlkon: true,
  },
  diagnostics_satellite_network: {
    id: "diagnostics_satellite_network",
    name: "Diagnostics Satellite Network",
    ownsSurfaces: ["Diagnostics", "Readiness", "public-safe owner-only state"],
    ownsEventTypes: ["public_ui_crowded", "internal_term_leaked"],
    workers: ["diagnostics_worker", "public_copy_worker"],
    stations: ["diagnostics_station", "public_ux_station"],
    forbiddenScope: ["Founder internals in public diagnostics", "secret exposure"],
    reportsToAlkon: true,
  },
  alkon_founder_command: {
    id: "alkon_founder_command",
    name: "Alkon Founder Command",
    ownsSurfaces: ["Founder Command", "Alkon report", "next safe actions"],
    ownsEventTypes: [
      "generic_founder_idea",
      "codex_task_needed",
      "local_day_report_needed",
    ],
    workers: ["alkon_report_worker", "result_tribunal_worker"],
    stations: ["founder_review_station", "tribunal_station"],
    forbiddenScope: ["public navigation", "user-plan access", "fake authority"],
    reportsToAlkon: true,
  },
};

export function getPlanetSystemOwner(
  ownerId: PlanetSystemOwnerId
): PlanetSystemOwner {
  return PLANET_SYSTEM_OWNERS[ownerId];
}

export function getPlanetSystemOwners(): PlanetSystemOwner[] {
  return Object.values(PLANET_SYSTEM_OWNERS);
}
