import "server-only";

import type { CosmicWorker, CosmicWorkerId } from "./types";

function worker(input: CosmicWorker): CosmicWorker {
  return input;
}

export const COSMIC_WORKERS: Record<CosmicWorkerId, CosmicWorker> = {
  logo_identity_worker: worker({
    id: "logo_identity_worker",
    name: "Logo Identity Worker",
    allowedTasks: ["Earth mark refinement", "visual identity correction"],
    forbiddenTasks: ["raster asset creation", "generated image use", "private term exposure"],
    allowedFilesOrSurfaces: ["brand components", "theme CSS", "visual docs"],
    forbiddenFilesOrSurfaces: ["public internal vocabulary", "production secrets"],
    requiredReviews: ["Ahmad visual acceptance", "public boundary review"],
    validationRequirements: ["no raster scan", "light/dark proof", "screenshot proof"],
    reportTarget: "Visual Identity Planet",
    memoryRule: "Record accepted and rejected identity patterns.",
  }),
  chart_comfort_worker: worker({
    id: "chart_comfort_worker",
    name: "Chart Comfort Worker",
    allowedTasks: ["Chart hierarchy", "workspace density", "overlay cleanup"],
    forbiddenTasks: ["live execution", "real-money routing", "broker/feed activation"],
    allowedFilesOrSurfaces: ["Trading Workspace", "Markets", "chart CSS"],
    forbiddenFilesOrSurfaces: ["broker credentials", "execution routes"],
    requiredReviews: ["chart comfort review", "paper-safe truth review"],
    validationRequirements: ["workstation screenshot", "route smoke"],
    reportTarget: "Trading Workspace Planet",
    memoryRule: "Record chart annoyance and comfort lessons.",
  }),
  public_copy_worker: worker({
    id: "public_copy_worker",
    name: "Public Copy Worker",
    allowedTasks: ["Public-safe wording", "blocked-state explanations"],
    forbiddenTasks: ["Alkon exposure", "cosmic term exposure", "fake activation"],
    allowedFilesOrSurfaces: ["public components", "plans", "diagnostics copy"],
    forbiddenFilesOrSurfaces: ["Founder internals", "secret reports"],
    requiredReviews: ["public language scan", "Product Truth review"],
    validationRequirements: ["public leak regression", "ESLint"],
    reportTarget: "Earth Public World",
    memoryRule: "Record public/private boundary lessons.",
  }),
  public_navigation_worker: worker({
    id: "public_navigation_worker",
    name: "Public Navigation Worker",
    allowedTasks: ["Navigation clarity", "surface ordering", "public link hygiene"],
    forbiddenTasks: ["Founder Command link", "Alkon link", "Worker/Task Graph link"],
    allowedFilesOrSurfaces: ["public navigation", "home", "settings"],
    forbiddenFilesOrSurfaces: ["private command routes"],
    requiredReviews: ["navigation leak review"],
    validationRequirements: ["smoke routes", "public text scan"],
    reportTarget: "Earth Public World",
    memoryRule: "Record navigation boundary lessons.",
  }),
  apps_platforms_worker: worker({
    id: "apps_platforms_worker",
    name: "Apps Platforms Worker",
    allowedTasks: ["Apps/platforms readiness", "desktop/mobile planned state"],
    forbiddenTasks: ["external account creation", "app store publishing"],
    allowedFilesOrSurfaces: ["Apps / Platforms", "Support", "World Interface readiness"],
    forbiddenFilesOrSurfaces: ["external tokens", "publishing automation"],
    requiredReviews: ["readiness-only review"],
    validationRequirements: ["public copy scan", "route smoke"],
    reportTarget: "Apps Support Planet",
    memoryRule: "Record platform readiness lessons.",
  }),
  support_readiness_worker: worker({
    id: "support_readiness_worker",
    name: "Support Readiness Worker",
    allowedTasks: ["Support copy", "help readiness", "public-safe contact state"],
    forbiddenTasks: ["send email", "create support accounts", "fake support metrics"],
    allowedFilesOrSurfaces: ["Support", "Community", "Academy"],
    forbiddenFilesOrSurfaces: ["email tokens", "external CRM"],
    requiredReviews: ["support readiness review"],
    validationRequirements: ["no external call check", "public text scan"],
    reportTarget: "Apps Support Planet",
    memoryRule: "Record support readiness lessons.",
  }),
  markets_worker: worker({
    id: "markets_worker",
    name: "Markets Worker",
    allowedTasks: ["Market display truth", "paper-safe market copy"],
    forbiddenTasks: ["broker/feed activation", "live market promise", "signal guarantee"],
    allowedFilesOrSurfaces: ["Markets", "Trading Workspace"],
    forbiddenFilesOrSurfaces: ["broker/feed credentials", "execution services"],
    requiredReviews: ["Product Truth review"],
    validationRequirements: ["market surface regression", "truth scan"],
    reportTarget: "Trading Workspace Planet",
    memoryRule: "Record market truth lessons.",
  }),
  academy_worker: worker({
    id: "academy_worker",
    name: "Academy Worker",
    allowedTasks: ["Learning readiness", "paper-mode lessons"],
    forbiddenTasks: ["financial advice", "profit promise", "certification claim"],
    allowedFilesOrSurfaces: ["Academy", "Journal", "Coach"],
    forbiddenFilesOrSurfaces: ["legal certification claims"],
    requiredReviews: ["education safety review"],
    validationRequirements: ["copy scan", "regression"],
    reportTarget: "Academy Community Planet",
    memoryRule: "Record learning readiness lessons.",
  }),
  community_worker: worker({
    id: "community_worker",
    name: "Community Worker",
    allowedTasks: ["Community readiness", "inactive state explanation"],
    forbiddenTasks: ["social publishing", "fake users", "fake community metrics"],
    allowedFilesOrSurfaces: ["Community", "Support"],
    forbiddenFilesOrSurfaces: ["social tokens", "external posting"],
    requiredReviews: ["community truth review"],
    validationRequirements: ["fake metrics scan", "public text scan"],
    reportTarget: "Academy Community Planet",
    memoryRule: "Record community readiness lessons.",
  }),
  tpm_assistant_worker: worker({
    id: "tpm_assistant_worker",
    name: "TPM Assistant Worker",
    allowedTasks: ["Assistant behavior", "why-blocked guidance", "plan-aware copy"],
    forbiddenTasks: ["trade signals", "financial advice", "internal vocabulary public"],
    allowedFilesOrSurfaces: ["TPM Assistant", "state explanations"],
    forbiddenFilesOrSurfaces: ["private Founder command language"],
    requiredReviews: ["assistant safety review"],
    validationRequirements: ["assistant regression", "blocked-state test"],
    reportTarget: "Assistant Planet",
    memoryRule: "Record safe Assistant behavior lessons.",
  }),
  journal_coach_worker: worker({
    id: "journal_coach_worker",
    name: "Journal Coach Worker",
    allowedTasks: ["Reflection prompts", "decision notes", "paper-mode lessons"],
    forbiddenTasks: ["financial advice", "outcome guarantee", "private health claim"],
    allowedFilesOrSurfaces: ["Journal", "Coach"],
    forbiddenFilesOrSurfaces: ["private sensitive data stores"],
    requiredReviews: ["coach safety review"],
    validationRequirements: ["journal coach regression", "copy scan"],
    reportTarget: "Journal Coach Planet",
    memoryRule: "Record coaching depth lessons without private sensitive data.",
  }),
  plan_realm_worker: worker({
    id: "plan_realm_worker",
    name: "Plan Realm Worker",
    allowedTasks: ["Plan truth", "realm behavior", "entitlement mapping"],
    forbiddenTasks: ["fake Pro activation", "fake VIP activation", "Alkon user plan"],
    allowedFilesOrSurfaces: ["plans", "realms", "public plan cards"],
    forbiddenFilesOrSurfaces: ["billing activation", "Founder Command public"],
    requiredReviews: ["entitlement truth review"],
    validationRequirements: ["plan realm regression", "public leak scan"],
    reportTarget: "Plans Realm Planet",
    memoryRule: "Record plan entitlement and activation truth lessons.",
  }),
  security_gate_worker: worker({
    id: "security_gate_worker",
    name: "Security Gate Worker",
    allowedTasks: ["Block hard-forbidden requests", "review public boundary risk"],
    forbiddenTasks: ["auth weakening", "external offensive action", "launch activation"],
    allowedFilesOrSurfaces: ["security readiness", "Product Truth", "Founder reports"],
    forbiddenFilesOrSurfaces: ["secret values", "execution endpoints"],
    requiredReviews: ["security review", "Founder review"],
    validationRequirements: ["no execution route check", "secret scan"],
    reportTarget: "Defense Universe",
    memoryRule: "Record blocked risk and safe alternative lessons.",
  }),
  secrets_safety_worker: worker({
    id: "secrets_safety_worker",
    name: "Secrets Safety Worker",
    allowedTasks: ["Presence-only secret status", "rotation readiness", "incident note"],
    forbiddenTasks: ["show raw secret", "store production secret", "send secret to Codex"],
    allowedFilesOrSurfaces: ["Secrets Authority status", "security reports"],
    forbiddenFilesOrSurfaces: [".env values", "production secret material"],
    requiredReviews: ["Secrets Authority review"],
    validationRequirements: ["secret pattern scan", "no raw value proof"],
    reportTarget: "Secrets Authority",
    memoryRule: "Record secrets lessons without values.",
  }),
  codex_passport_worker: worker({
    id: "codex_passport_worker",
    name: "Codex Passport Worker",
    allowedTasks: ["Task Passport", "scope contract", "validation checklist"],
    forbiddenTasks: ["unscoped work", "secret inclusion", "automatic Codex execution"],
    allowedFilesOrSurfaces: ["construction readiness", "Codex draft preview"],
    forbiddenFilesOrSurfaces: ["secret files", "web-app execution endpoints"],
    requiredReviews: ["Task Passport review"],
    validationRequirements: ["scope check", "forbidden action check"],
    reportTarget: "Construction Universe",
    memoryRule: "Record task distribution lessons.",
  }),
  codex_prompt_worker: worker({
    id: "codex_prompt_worker",
    name: "Codex Prompt Worker",
    allowedTasks: ["Manual draft prompt", "validation instructions"],
    forbiddenTasks: ["direct Codex call", "shell execution", "secrets in prompt"],
    allowedFilesOrSurfaces: ["Codex drafts", "Founder Command previews"],
    forbiddenFilesOrSurfaces: ["secret values", "external automation"],
    requiredReviews: ["Codex License review"],
    validationRequirements: ["prompt safety scan", "manual-only proof"],
    reportTarget: "Construction Universe",
    memoryRule: "Record safe prompt drafting lessons.",
  }),
  result_tribunal_worker: worker({
    id: "result_tribunal_worker",
    name: "Result Tribunal Worker",
    allowedTasks: ["Validation review", "acceptance decision", "fix request"],
    forbiddenTasks: ["accept without tests", "ignore Product Truth violation"],
    allowedFilesOrSurfaces: ["validation summaries", "Founder reports"],
    forbiddenFilesOrSurfaces: ["raw secrets", "fake metrics"],
    requiredReviews: ["Result Tribunal review"],
    validationRequirements: ["all required commands", "diff check", "git status"],
    reportTarget: "Result Tribunal",
    memoryRule: "Record validation and result lessons.",
  }),
  memory_lesson_worker: worker({
    id: "memory_lesson_worker",
    name: "Memory Lesson Worker",
    allowedTasks: ["Safe lesson", "accepted pattern", "rejected pattern"],
    forbiddenTasks: ["raw secrets", "private sensitive data", "fake users/revenue/metrics"],
    allowedFilesOrSurfaces: ["Memory Universe", "Product Memory summaries"],
    forbiddenFilesOrSurfaces: ["secret files", "private user data"],
    requiredReviews: ["safe memory review"],
    validationRequirements: ["no secrets", "no private sensitive data"],
    reportTarget: "Memory Universe",
    memoryRule: "Store only safe summaries and lessons.",
  }),
  diagnostics_worker: worker({
    id: "diagnostics_worker",
    name: "Diagnostics Worker",
    allowedTasks: ["Readiness status", "public-safe diagnostics", "route smoke"],
    forbiddenTasks: ["Founder internal diagnostics public", "secret output"],
    allowedFilesOrSurfaces: ["Diagnostics", "Readiness"],
    forbiddenFilesOrSurfaces: ["Alkon internals in public UI", "secret values"],
    requiredReviews: ["public-safe diagnostics review"],
    validationRequirements: ["smoke routes", "public text scan"],
    reportTarget: "Diagnostics Satellite Network",
    memoryRule: "Record diagnostic boundary lessons.",
  }),
  alkon_report_worker: worker({
    id: "alkon_report_worker",
    name: "Alkon Report Worker",
    allowedTasks: ["Founder Command report", "next safe actions", "blocked actions"],
    forbiddenTasks: ["public route exposure", "approval execution", "external action"],
    allowedFilesOrSurfaces: ["Founder Command", "Alkon reports"],
    forbiddenFilesOrSurfaces: ["public navigation", "user plan cards"],
    requiredReviews: ["Founder review"],
    validationRequirements: ["read-only proof", "public route absence"],
    reportTarget: "Alkon Founder Command",
    memoryRule: "Record Founder decision and next safe action lessons.",
  }),
};

export function getCosmicWorker(workerId: CosmicWorkerId): CosmicWorker {
  return COSMIC_WORKERS[workerId];
}

export function getCosmicWorkers(): CosmicWorker[] {
  return Object.values(COSMIC_WORKERS);
}
