import type { DeviceRegistryItem } from "./types";

const PRIVATE_BLOCKS: DeviceRegistryItem["blockedCapabilities"] = [
  "live_execution",
  "real_money",
  "billing_activation",
  "broker_feed_activation",
  "production_activation",
  "production_secrets",
  "codex_execution",
  "payment_execution",
  "social_publishing",
  "shell_execution",
  "public_private_systems",
  "fake_downloads",
  "fake_store_claims",
  "fake_metrics",
];

export const alkonDeviceRegistry: DeviceRegistryItem[] = [
  {
    deviceId: "ahmad_windows_command_build_center",
    publicName: "Internal Windows command center",
    privateName: "Windows Command + Build Center",
    world: "private_alkon",
    type: "desktop",
    audience: "founder_private",
    availability: "internal_only",
    role:
      "Official Ahmad desktop command and local build center. Ahmad may use the terminal locally; the web app never executes shell or Codex.",
    allowedCapabilities: ["full_private_command", "local_build_center"],
    blockedCapabilities: PRIVATE_BLOCKS,
    permissionLevel: "founder_command",
    constellationRole: "windows_command_build_center",
    securityPosture: [
      "internal_only",
      "trusted_device_required",
      "step_up_required",
      "passkey_planned",
    ],
    publicVisible: false,
    founderVisible: true,
    appStoreStatus: "internal_only",
    installStatus: "internal_only",
    continuityRole: "Primary command, review, and local terminal build surface for Ahmad only.",
    productTruthNotes: [
      "Terminal use is allowed only by Ahmad outside the web app.",
      "No public device claim is created.",
      "No live, billing, broker/feed, real money, or production activation is allowed.",
    ],
    nextSafeAction: "Keep local build commands manual in the Windows terminal.",
  },
  {
    deviceId: "ahmad_iphone_pocket_decision_center",
    publicName: "Internal iPhone pocket review",
    privateName: "iPhone Pocket Decision Center",
    world: "private_alkon",
    type: "mobile",
    audience: "founder_private",
    availability: "internal_only",
    role:
      "Official iPhone pocket decision center for Wake Report, One Next Action, visual review, accept, reject with notes, and focused correction intent.",
    allowedCapabilities: [
      "wake_report_review",
      "one_next_action_review",
      "mobile_visual_review",
      "focused_correction_intent",
    ],
    blockedCapabilities: PRIVATE_BLOCKS,
    permissionLevel: "review_only",
    constellationRole: "iphone_pocket_decision_center",
    securityPosture: [
      "internal_only",
      "trusted_device_required",
      "step_up_required",
      "biometric_planned",
      "passkey_planned",
    ],
    publicVisible: false,
    founderVisible: true,
    appStoreStatus: "internal_only",
    installStatus: "internal_only",
    continuityRole: "Pocket review and decision-intent surface; never an execution surface.",
    productTruthNotes: [
      "No shell, Codex, secrets, payments, launch, live trading, billing, broker/feed, or real money.",
      "Decision options are read-only intent until Ahmad acts through governed desktop flow.",
    ],
    nextSafeAction: "Use iPhone for visual acceptance intent and focused correction notes only.",
  },
  {
    deviceId: "ahmad_samsung_review_android_reality_center",
    publicName: "Internal Samsung Android review",
    privateName: "Samsung Review + Android Reality Center",
    world: "private_alkon",
    type: "mobile",
    audience: "founder_private",
    availability: "internal_only",
    role:
      "Official Samsung review and Android reality center for mobile visual proof, Wake Report, One Next Action, and Android-width reality review.",
    allowedCapabilities: [
      "wake_report_review",
      "one_next_action_review",
      "mobile_visual_review",
    ],
    blockedCapabilities: PRIVATE_BLOCKS,
    permissionLevel: "review_only",
    constellationRole: "samsung_review_android_reality_center",
    securityPosture: [
      "internal_only",
      "trusted_device_required",
      "step_up_required",
      "biometric_planned",
      "passkey_planned",
    ],
    publicVisible: false,
    founderVisible: true,
    appStoreStatus: "internal_only",
    installStatus: "internal_only",
    continuityRole: "Android reality review surface; never an execution or payment surface.",
    productTruthNotes: [
      "No shell, Codex, secrets, payments, launch, live trading, billing, broker/feed, or real money.",
      "Review findings become focused correction intent only.",
    ],
    nextSafeAction: "Use Samsung for Android mobile visual review and blocked-action checks.",
  },
  {
    deviceId: "alkon_desktop_command",
    publicName: "Internal command desktop",
    privateName: "Alkon Desktop Command",
    world: "private_alkon",
    type: "desktop",
    audience: "founder_private",
    availability: "internal_only",
    role:
      "Full private command universe for Earth Command, Moon Cycle, Orbit Command, Security, Memory, Launch Gate, and Result Tribunal readiness.",
    allowedCapabilities: ["full_private_command"],
    blockedCapabilities: PRIVATE_BLOCKS,
    permissionLevel: "founder_command",
    constellationRole: "legacy_internal_readiness",
    securityPosture: [
      "internal_only",
      "trusted_device_required",
      "step_up_required",
      "passkey_planned",
    ],
    publicVisible: false,
    founderVisible: true,
    appStoreStatus: "internal_only",
    installStatus: "internal_only",
    continuityRole: "Primary private Founder command surface.",
    productTruthNotes: [
      "Founder-only and read-only by default.",
      "No direct dangerous execution.",
      "No secrets are displayed.",
    ],
    nextSafeAction: "Keep full command reporting private and read-only.",
  },
  {
    deviceId: "alkon_pocket_universe_os",
    publicName: "Internal mobile command readiness",
    privateName: "Alkon Pocket Universe OS",
    world: "private_alkon",
    type: "mobile",
    audience: "founder_private",
    availability: "internal_only",
    role:
      "Planned private mobile pulse for Universe Pulse, Earth Watch, Orbit Queue, Build Signal, Guard Signal, Memory Constellation, Founder Review, Emergency Mode, and Silent Night Mode.",
    allowedCapabilities: ["mobile_pulse_planned"],
    blockedCapabilities: PRIVATE_BLOCKS,
    permissionLevel: "approve_low_risk",
    constellationRole: "legacy_internal_readiness",
    securityPosture: [
      "internal_only",
      "trusted_device_required",
      "step_up_required",
      "biometric_planned",
      "passkey_planned",
    ],
    publicVisible: false,
    founderVisible: true,
    appStoreStatus: "internal_only",
    installStatus: "planned",
    continuityRole: "Future low-risk decision pulse after trusted-device gates exist.",
    productTruthNotes: [
      "No public mobile command app is shipped.",
      "No secrets or shell execution are allowed.",
      "Approval flows remain readiness-only.",
    ],
    nextSafeAction: "Model mobile command decisions without executing them.",
  },
  {
    deviceId: "alkon_tablet_review",
    publicName: "Internal tablet review readiness",
    privateName: "Alkon Tablet Review",
    world: "private_alkon",
    type: "tablet",
    audience: "founder_private",
    availability: "future",
    role:
      "Future private visual review, report reading, launch checklist review, and Codex result review surface.",
    allowedCapabilities: ["visual_review_future"],
    blockedCapabilities: PRIVATE_BLOCKS,
    permissionLevel: "review_only",
    constellationRole: "legacy_internal_readiness",
    securityPosture: ["internal_only", "trusted_device_required", "passkey_planned"],
    publicVisible: false,
    founderVisible: true,
    appStoreStatus: "internal_only",
    installStatus: "future",
    continuityRole: "Future visual acceptance and report review path.",
    productTruthNotes: [
      "Tablet review is future only.",
      "No external publishing or store availability is claimed.",
    ],
    nextSafeAction: "Keep tablet review future-only until private auth exists.",
  },
  {
    deviceId: "alkon_watch_alerts",
    publicName: "Internal alert readiness",
    privateName: "Alkon Watch Alerts",
    world: "private_alkon",
    type: "watch",
    audience: "founder_private",
    availability: "future",
    role:
      "Future P0 alerts only for build failed, public leak, secret risk, or Founder approval needed.",
    allowedCapabilities: ["p0_alerts_future"],
    blockedCapabilities: PRIVATE_BLOCKS,
    permissionLevel: "alert_only",
    constellationRole: "legacy_internal_readiness",
    securityPosture: ["internal_only", "trusted_device_required", "biometric_planned"],
    publicVisible: false,
    founderVisible: true,
    appStoreStatus: "internal_only",
    installStatus: "future",
    continuityRole: "Future alert-only path into mobile or desktop review.",
    productTruthNotes: [
      "Watch is alert-only.",
      "No secrets, no decisions, and no execution controls are allowed.",
    ],
    nextSafeAction: "Keep watch alerts future and P0-only.",
  },
];

export function getAlkonDeviceRegistry() {
  return alkonDeviceRegistry;
}
