import type { DeviceRegistryItem } from "./types";

const PRIVATE_BLOCKS: DeviceRegistryItem["blockedCapabilities"] = [
  "live_execution",
  "real_money",
  "billing_activation",
  "broker_feed_activation",
  "production_activation",
  "production_secrets",
  "social_publishing",
  "shell_execution",
  "public_private_systems",
  "fake_downloads",
  "fake_store_claims",
  "fake_metrics",
];

export const alkonDeviceRegistry: DeviceRegistryItem[] = [
  {
    deviceId: "alkon_desktop_command",
    publicName: "Internal command desktop",
    privateName: "Alkon Desktop Command",
    world: "private_alkon",
    type: "desktop",
    audience: "founder_private",
    availability: "internal_only",
    role:
      "Full private command universe for Earth Command, Moon Cycle, Orbit Command, Security, Memory, Launch Gate, and Result Tribunal readiness.",
    allowedCapabilities: ["full_private_command"],
    blockedCapabilities: PRIVATE_BLOCKS,
    permissionLevel: "founder_command",
    securityPosture: [
      "internal_only",
      "trusted_device_required",
      "step_up_required",
      "passkey_planned",
    ],
    publicVisible: false,
    founderVisible: true,
    appStoreStatus: "internal_only",
    installStatus: "internal_only",
    continuityRole: "Primary private Founder command surface.",
    productTruthNotes: [
      "Founder-only and read-only by default.",
      "No direct dangerous execution.",
      "No secrets are displayed.",
    ],
    nextSafeAction: "Keep full command reporting private and read-only.",
  },
  {
    deviceId: "alkon_pocket_universe_os",
    publicName: "Internal mobile command readiness",
    privateName: "Alkon Pocket Universe OS",
    world: "private_alkon",
    type: "mobile",
    audience: "founder_private",
    availability: "internal_only",
    role:
      "Planned private mobile pulse for Universe Pulse, Earth Watch, Orbit Queue, Build Signal, Guard Signal, Memory Constellation, Founder Review, Emergency Mode, and Silent Night Mode.",
    allowedCapabilities: ["mobile_pulse_planned"],
    blockedCapabilities: PRIVATE_BLOCKS,
    permissionLevel: "approve_low_risk",
    securityPosture: [
      "internal_only",
      "trusted_device_required",
      "step_up_required",
      "biometric_planned",
      "passkey_planned",
    ],
    publicVisible: false,
    founderVisible: true,
    appStoreStatus: "internal_only",
    installStatus: "planned",
    continuityRole: "Future low-risk decision pulse after trusted-device gates exist.",
    productTruthNotes: [
      "No public mobile command app is shipped.",
      "No secrets or shell execution are allowed.",
      "Approval flows remain readiness-only.",
    ],
    nextSafeAction: "Model mobile command decisions without executing them.",
  },
  {
    deviceId: "alkon_tablet_review",
    publicName: "Internal tablet review readiness",
    privateName: "Alkon Tablet Review",
    world: "private_alkon",
    type: "tablet",
    audience: "founder_private",
    availability: "future",
    role:
      "Future private visual review, report reading, launch checklist review, and Codex result review surface.",
    allowedCapabilities: ["visual_review_future"],
    blockedCapabilities: PRIVATE_BLOCKS,
    permissionLevel: "review_only",
    securityPosture: ["internal_only", "trusted_device_required", "passkey_planned"],
    publicVisible: false,
    founderVisible: true,
    appStoreStatus: "internal_only",
    installStatus: "future",
    continuityRole: "Future visual acceptance and report review path.",
    productTruthNotes: [
      "Tablet review is future only.",
      "No external publishing or store availability is claimed.",
    ],
    nextSafeAction: "Keep tablet review future-only until private auth exists.",
  },
  {
    deviceId: "alkon_watch_alerts",
    publicName: "Internal alert readiness",
    privateName: "Alkon Watch Alerts",
    world: "private_alkon",
    type: "watch",
    audience: "founder_private",
    availability: "future",
    role:
      "Future P0 alerts only for build failed, public leak, secret risk, or Founder approval needed.",
    allowedCapabilities: ["p0_alerts_future"],
    blockedCapabilities: PRIVATE_BLOCKS,
    permissionLevel: "alert_only",
    securityPosture: ["internal_only", "trusted_device_required", "biometric_planned"],
    publicVisible: false,
    founderVisible: true,
    appStoreStatus: "internal_only",
    installStatus: "future",
    continuityRole: "Future alert-only path into mobile or desktop review.",
    productTruthNotes: [
      "Watch is alert-only.",
      "No secrets, no decisions, and no execution controls are allowed.",
    ],
    nextSafeAction: "Keep watch alerts future and P0-only.",
  },
];

export function getAlkonDeviceRegistry() {
  return alkonDeviceRegistry;
}
