import type { DeviceRegistryItem } from "./types";

const PUBLIC_BLOCKS: DeviceRegistryItem["blockedCapabilities"] = [
  "live_execution",
  "real_money",
  "billing_activation",
  "broker_feed_activation",
  "production_activation",
  "production_secrets",
  "social_publishing",
  "shell_execution",
  "public_private_systems",
  "fake_downloads",
  "fake_store_claims",
  "fake_metrics",
];

export const publicDeviceRegistry: DeviceRegistryItem[] = [
  {
    deviceId: "tpm_web_app",
    publicName: "Pro Max Web App",
    privateName: "Public Earth Web App",
    world: "public_earth",
    type: "web",
    audience: "public_user",
    availability: "current",
    role:
      "Earth entry, public product world, paper-safe Trading Workspace, Academy, Support, Settings, and Diagnostics.",
    allowedCapabilities: [
      "public_entry",
      "paper_workspace",
      "plans_view",
      "assistant",
      "journal_coach_basic",
      "academy_support",
      "settings_diagnostics",
    ],
    blockedCapabilities: PUBLIC_BLOCKS,
    permissionLevel: "paper_workspace",
    securityPosture: ["public_safe", "account_required"],
    publicVisible: true,
    founderVisible: true,
    appStoreStatus: "not_applicable",
    installStatus: "web_current",
    continuityRole: "Primary public surface and current workspace.",
    productTruthNotes: [
      "Web is current.",
      "Execution remains paper-safe.",
      "No billing, broker/feed, live execution, or real-money routing is active.",
    ],
    nextSafeAction: "Keep the web workspace truthful, chart-safe, and complete.",
  },
  {
    deviceId: "tpm_desktop_app",
    publicName: "Pro Max Desktop App",
    privateName: "Public Earth Desktop App",
    world: "public_earth",
    type: "desktop",
    audience: "authenticated_user",
    availability: "planned",
    role: "Future deep trading terminal packaging readiness.",
    allowedCapabilities: ["deep_work_terminal_planned", "paper_workspace"],
    blockedCapabilities: PUBLIC_BLOCKS,
    permissionLevel: "paper_workspace",
    securityPosture: ["account_required", "trusted_device_required"],
    publicVisible: true,
    founderVisible: true,
    appStoreStatus: "planned",
    installStatus: "planned",
    continuityRole: "Web workspace preferences can inform future desktop readiness.",
    productTruthNotes: [
      "Desktop is planned.",
      "No installer exists.",
      "No public download button or native release claim is allowed.",
    ],
    nextSafeAction: "Model desktop continuity without publishing an installer.",
  },
  {
    deviceId: "tpm_mobile_app",
    publicName: "Pro Max Mobile App",
    privateName: "Public Earth Mobile App",
    world: "public_earth",
    type: "mobile",
    audience: "authenticated_user",
    availability: "planned",
    role: "Future companion for status, learning, journal, and support readiness.",
    allowedCapabilities: ["mobile_status_planned", "journal_coach_basic", "academy_support"],
    blockedCapabilities: PUBLIC_BLOCKS,
    permissionLevel: "review_only",
    securityPosture: ["account_required", "trusted_device_required", "passkey_planned"],
    publicVisible: true,
    founderVisible: true,
    appStoreStatus: "planned",
    installStatus: "planned",
    continuityRole: "Learning, support, journal, and status continuity are planned only.",
    productTruthNotes: [
      "Mobile is planned.",
      "No store release, install package, or push activation claim is active.",
    ],
    nextSafeAction: "Keep mobile as readiness-only until real packaging exists.",
  },
  {
    deviceId: "tpm_tablet_app",
    publicName: "Pro Max Tablet App",
    privateName: "Public Earth Tablet App",
    world: "public_earth",
    type: "tablet",
    audience: "authenticated_user",
    availability: "future",
    role: "Future learning, review, and market overview surface.",
    allowedCapabilities: ["learning_review_future"],
    blockedCapabilities: PUBLIC_BLOCKS,
    permissionLevel: "review_only",
    securityPosture: ["account_required", "trusted_device_required"],
    publicVisible: true,
    founderVisible: true,
    appStoreStatus: "future",
    installStatus: "future",
    continuityRole: "Future review surface after web and desktop foundations mature.",
    productTruthNotes: [
      "Tablet is future.",
      "No separate tablet app is shipped or listed.",
    ],
    nextSafeAction: "Keep tablet direction future-only.",
  },
];

export function getPublicDeviceRegistry() {
  return publicDeviceRegistry;
}
