import "server-only";

import type { DailyWorkItem } from "./types";

export function getDailySafeWorkItems(): DailyWorkItem[] {
  return [
    {
      id: "project_audit",
      title: "Project audit",
      layer: "Universe Operating Kernel",
      status: "ready",
      category: "safe_internal",
      nextStep: "Review local code and report evidence.",
      whoDecides: "الكون",
      reason: "Internal audit does not touch law, money, broker, public launch, or secrets.",
    },
    {
      id: "report_generation",
      title: "Report generation",
      layer: "Reports / Tasks / Decisions",
      status: "ready",
      category: "safe_internal",
      nextStep: "Prepare local reports with no secrets.",
      whoDecides: "الكون",
      reason: "Private report generation is safe when Product Truth is preserved.",
    },
    {
      id: "docs_update_proposal",
      title: "Docs update proposal",
      layer: "Human Interface",
      status: "ready",
      category: "safe_internal",
      nextStep: "Draft proposed internal documentation changes.",
      whoDecides: "الكون",
      reason: "Documentation proposals are internal and reversible.",
    },
    {
      id: "task_organization",
      title: "Task organization",
      layer: "Daily Work Loop",
      status: "active",
      category: "safe_internal",
      nextStep: "Sort safe work, blockers, and decisions into one next action.",
      whoDecides: "الكون",
      reason: "Daily work organization is the core private operating behavior.",
    },
    {
      id: "product_truth_check",
      title: "Product Truth check",
      layer: "Product Truth",
      status: "active",
      category: "safe_internal",
      nextStep: "Verify blocked public, billing, money, broker, and legal states remain visible.",
      whoDecides: "الكون",
      reason: "Product Truth checking prevents false readiness claims.",
    },
    {
      id: "visual_consistency_check",
      title: "Visual consistency check",
      layer: "Al-Kawn Unified Visual Identity",
      status: "ready",
      category: "safe_internal",
      nextStep: "Review private surfaces for identity consistency.",
      whoDecides: "الكون",
      reason: "Visual review remains private and internal.",
    },
    {
      id: "test_status_summary",
      title: "Test status summary",
      layer: "Regression",
      status: "ready",
      category: "safe_internal",
      nextStep: "Summarize current validation and test evidence.",
      whoDecides: "الكون",
      reason: "Local test summaries are internal evidence.",
    },
    {
      id: "architecture_status_summary",
      title: "Architecture status summary",
      layer: "Canonical Architecture",
      status: "ready",
      category: "safe_internal",
      nextStep: "Summarize current architecture ownership and gaps.",
      whoDecides: "الكون",
      reason: "Architecture summaries are internal and reversible.",
    },
    {
      id: "desktop_app_status_summary",
      title: "Desktop app status summary",
      layer: "Al-Kawn Desktop",
      status: "ready",
      category: "safe_internal",
      nextStep: "Summarize desktop route, local auth, and packaging gates.",
      whoDecides: "الكون",
      reason: "Status summaries do not package, sign, publish, or distribute.",
    },
    {
      id: "next_codex_mission_draft",
      title: "Next Codex mission draft",
      layer: "Human Interface",
      status: "ready",
      category: "safe_internal",
      nextStep: "Draft one safe next internal mission for Ahmad review.",
      whoDecides: "الكون",
      reason: "Mission drafting proposes work without executing external/legal/money actions.",
    },
  ];
}
