import "server-only";

import type { DailyWorkItem } from "./types";

export function getDailyBlockedItems(): DailyWorkItem[] {
  return [
    {
      id: "legal",
      title: "Legal",
      layer: "Swiss Local Constitution",
      status: "blocked",
      category: "legal_stop",
      nextStep: "Stop for Ahmad.",
      whoDecides: "Ahmad",
      reason: "Legal matters require Ahmad and professional review.",
    },
    {
      id: "money",
      title: "Money",
      layer: "Absolute Founder Boundary",
      status: "blocked",
      category: "money_stop",
      nextStep: "Stop for Ahmad.",
      whoDecides: "Ahmad",
      reason: "Money movement, payments, bank, broker, and customer funds require Ahmad.",
    },
    {
      id: "public_launch",
      title: "Public launch",
      layer: "Product Truth",
      status: "blocked",
      category: "product_truth_block",
      nextStep: "Remain blocked.",
      whoDecides: "Ahmad",
      reason: "Public launch remains blocked until future explicit approval.",
    },
    {
      id: "billing",
      title: "Billing",
      layer: "Product Truth",
      status: "blocked",
      category: "money_stop",
      nextStep: "Stop for Ahmad.",
      whoDecides: "Ahmad",
      reason: "Billing is inactive and must not be activated by the daily loop.",
    },
    {
      id: "receiving_money",
      title: "Receiving money",
      layer: "Product Truth",
      status: "blocked",
      category: "money_stop",
      nextStep: "Stop for Ahmad.",
      whoDecides: "Ahmad",
      reason: "Receiving money requires explicit Ahmad approval.",
    },
    {
      id: "broker",
      title: "Broker",
      layer: "Earth Planet / Trading",
      status: "blocked",
      category: "money_stop",
      nextStep: "Stop for Ahmad.",
      whoDecides: "Ahmad",
      reason: "Broker execution is disabled/not connected.",
    },
    {
      id: "real_trading",
      title: "Real trading",
      layer: "Earth Planet / Trading",
      status: "blocked",
      category: "money_stop",
      nextStep: "Stop for Ahmad.",
      whoDecides: "Ahmad",
      reason: "Real-money trading is disabled.",
    },
    {
      id: "legal_claim",
      title: "Legal claim",
      layer: "Product Truth",
      status: "blocked",
      category: "legal_stop",
      nextStep: "Stop for Ahmad.",
      whoDecides: "Ahmad",
      reason: "FINMA, licensed, regulated, legal approval, and official claims require review.",
    },
    {
      id: "secrets_exposure",
      title: "Secrets exposure",
      layer: "Protection Core",
      status: "blocked",
      category: "product_truth_block",
      nextStep: "Remain blocked.",
      whoDecides: "Ahmad",
      reason: "Secrets must not be stored in Git, bundle, public assets, or reports.",
    },
    {
      id: "public_al_kawn",
      title: "Public الكون",
      layer: "Product Truth",
      status: "blocked",
      category: "product_truth_block",
      nextStep: "Remain blocked.",
      whoDecides: "Ahmad",
      reason: "الكون remains private to Ahmad devices.",
    },
    {
      id: "public_alkon",
      title: "Public ALKON",
      layer: "Product Truth",
      status: "blocked",
      category: "product_truth_block",
      nextStep: "Remain blocked.",
      whoDecides: "Ahmad",
      reason: "ALKON remains private/background.",
    },
  ];
}
