import "server-only";

import type { DailyBlocker } from "./types";

export function getDailyBlockedItems(): DailyBlocker[] {
  return [
    {
      id: "legal_tasks_stopped",
      title: "Legal tasks stopped",
      reason: "Legal tasks require Ahmad and professional review.",
      gate: "legal",
      whatAlKawnCanPrepare: "Prepare internal legal-readiness notes without claims.",
      ahmadMustDecide: "Whether any official legal review, contract, compliance, or ownership matter proceeds.",
    },
    {
      id: "money_tasks_stopped",
      title: "Money tasks stopped",
      reason: "Money movement and financial-account work require Ahmad.",
      gate: "money",
      whatAlKawnCanPrepare: "Prepare internal readiness notes only.",
      ahmadMustDecide: "Whether payment, bank, broker, payout, subscription, or money movement work proceeds.",
    },
    {
      id: "public_launch_blocked",
      title: "Public launch blocked",
      reason: "Public launch remains blocked by Product Truth.",
      gate: "public",
      whatAlKawnCanPrepare: "Prepare private launch-readiness checklists only.",
      ahmadMustDecide: "Whether a future launch gate may be opened.",
    },
    {
      id: "billing_blocked",
      title: "Billing blocked",
      reason: "Billing is inactive.",
      gate: "money",
      whatAlKawnCanPrepare: "Prepare non-executing billing readiness notes.",
      ahmadMustDecide: "Whether billing may ever be activated.",
    },
    {
      id: "payments_blocked",
      title: "Payments blocked",
      reason: "Payments are inactive and no payment provider is activated.",
      gate: "money",
      whatAlKawnCanPrepare: "Prepare payment-gate documentation only.",
      ahmadMustDecide: "Whether Stripe, PayPal, bank, or any payment system may be connected.",
    },
    {
      id: "receiving_money_blocked",
      title: "Receiving money blocked",
      reason: "Receiving customer or external money requires Ahmad.",
      gate: "money",
      whatAlKawnCanPrepare: "Prepare internal receiving-money boundary notes.",
      ahmadMustDecide: "Whether receiving-money workflows may proceed.",
    },
    {
      id: "real_money_blocked",
      title: "Real money blocked",
      reason: "Real-money trading remains disabled.",
      gate: "money",
      whatAlKawnCanPrepare: "Prepare demo-safe trading readiness notes only.",
      ahmadMustDecide: "Whether any real-money trading path may be considered.",
    },
    {
      id: "broker_blocked",
      title: "Broker blocked",
      reason: "Broker execution is disabled/not connected.",
      gate: "money",
      whatAlKawnCanPrepare: "Prepare broker-boundary notes without keys or connections.",
      ahmadMustDecide: "Whether broker connection work may ever begin.",
    },
    {
      id: "legal_approval_claim_blocked",
      title: "Legal approval claim blocked",
      reason: "Legal approval, FINMA approval, and licensed/regulated claims are not true.",
      gate: "legal",
      whatAlKawnCanPrepare: "Prepare wording review notes without public claims.",
      ahmadMustDecide: "Whether official legal review evidence exists later.",
    },
    {
      id: "public_al_kawn_blocked",
      title: "Public الكون blocked",
      reason: "الكون remains private to Ahmad devices.",
      gate: "public",
      whatAlKawnCanPrepare: "Prepare private explanation only.",
      ahmadMustDecide: "Whether any future public framing is allowed.",
    },
    {
      id: "public_alkon_blocked",
      title: "Public ALKON blocked",
      reason: "ALKON remains private/background.",
      gate: "public",
      whatAlKawnCanPrepare: "Prepare private guardian status notes.",
      ahmadMustDecide: "Whether any future ALKON exposure is allowed.",
    },
    {
      id: "secrets_exposure_blocked",
      title: "Secrets exposure blocked",
      reason: "Secrets, private documents, API keys, payment keys, and broker keys must not enter Git or the bundle.",
      gate: "security",
      whatAlKawnCanPrepare: "Prepare redacted security notes only.",
      ahmadMustDecide: "Whether any sensitive material may be handled in a future approved secure vault path.",
    },
    {
      id: "product_truth_violations_blocked",
      title: "Product Truth violations blocked",
      reason: "False readiness, hidden blockers, guaranteed profit, risk-free, and public/private contradictions are blocked immediately.",
      gate: "product_truth",
      whatAlKawnCanPrepare: "Prepare correction notes and safe wording.",
      ahmadMustDecide: "Only Ahmad may approve final external wording later.",
    },
  ];
}
