import "server-only";

import type { DailyWorkItem } from "./types";

export function getDailySafeWorkItems(): DailyWorkItem[] {
  return [
    {
      id: "project_state_audit",
      title: "Project state audit",
      layer: "Universe Operating Kernel",
      reason: "The day starts by understanding local project state without touching external systems.",
      priority: "architecture",
      status: "ready",
      canExecuteDirectly: true,
      stopGate: "none",
      expectedOutput: "A concise local state summary.",
      nextStep: "Review local reports, Git state, and validation evidence.",
    },
    {
      id: "report_generation",
      title: "Report generation",
      layer: "Reports / Tasks / Decisions",
      reason: "Reports keep the daily loop explainable without secrets.",
      priority: "reports",
      status: "ready",
      canExecuteDirectly: true,
      stopGate: "none",
      expectedOutput: "Updated daily reports with no sensitive data.",
      nextStep: "Update the daily WAKE REPORT and memory snapshot.",
    },
    {
      id: "docs_update_proposal",
      title: "Docs update proposal",
      layer: "Human Interface",
      reason: "Documentation proposals are reversible internal work.",
      priority: "reports",
      status: "ready",
      canExecuteDirectly: true,
      stopGate: "none",
      expectedOutput: "A proposed internal documentation update.",
      nextStep: "Draft concise docs changes for Ahmad review when needed.",
    },
    {
      id: "regression_summary",
      title: "Regression summary",
      layer: "Regression",
      reason: "Validation state tells Ahmad what is real and what is pending.",
      priority: "tests",
      status: "ready",
      canExecuteDirectly: true,
      stopGate: "none",
      expectedOutput: "Latest validation summary.",
      nextStep: "Summarize focused and full regression results.",
    },
    {
      id: "visual_consistency_review",
      title: "Visual consistency review",
      layer: "Al-Kawn Unified Visual Identity",
      reason: "Visual review keeps private surfaces coherent after truth/protection work.",
      priority: "visual_consistency",
      status: "ready",
      canExecuteDirectly: true,
      stopGate: "none",
      expectedOutput: "Visual consistency notes.",
      nextStep: "Check founder/desktop/trading identity density and Product Truth visibility.",
    },
    {
      id: "desktop_status_review",
      title: "Desktop status review",
      layer: "Al-Kawn Desktop",
      reason: "/desktop/kawn is the main daily command client.",
      priority: "desktop",
      status: "ready",
      canExecuteDirectly: true,
      stopGate: "none",
      expectedOutput: "Desktop route, auth, and gate status summary.",
      nextStep: "Review local auth, packaging gates, dry-run state, and distribution gate.",
    },
    {
      id: "product_truth_verification",
      title: "Product Truth verification",
      layer: "Product Truth",
      reason: "Product Truth priority comes first.",
      priority: "product_truth",
      status: "selected",
      canExecuteDirectly: true,
      stopGate: "none",
      expectedOutput: "Daily Product Truth confirmation with blockers visible.",
      nextStep: "Confirm public, legal, billing, money, broker, and secrets remain blocked.",
    },
    {
      id: "architecture_status_summary",
      title: "Architecture status summary",
      layer: "Canonical Architecture",
      reason: "Architecture summaries keep ownership and next work understandable.",
      priority: "architecture",
      status: "ready",
      canExecuteDirectly: true,
      stopGate: "none",
      expectedOutput: "Layer and module ownership summary.",
      nextStep: "Summarize wake, desktop, auth, packaging, and control surface layers.",
    },
    {
      id: "next_codex_mission_draft",
      title: "Next Codex mission draft",
      layer: "Human Interface",
      reason: "Mission drafts propose safe internal work without executing external actions.",
      priority: "future_gates",
      status: "ready",
      canExecuteDirectly: true,
      stopGate: "none",
      expectedOutput: "One safe next mission draft.",
      nextStep: "Prepare a mission only after the daily next action is selected.",
    },
    {
      id: "task_organization",
      title: "Task organization",
      layer: "Daily Work Loop",
      reason: "الكون ينظم يومه الداخلي.",
      priority: "reports",
      status: "active",
      canExecuteDirectly: true,
      stopGate: "none",
      expectedOutput: "Sorted safe work, blockers, needs, and one next action.",
      nextStep: "Group safe internal work separately from Ahmad stop-gates.",
    },
    {
      id: "daily_briefing_update",
      title: "Daily briefing update",
      layer: "Human Spoken Interface",
      reason: "Ahmad receives a clear Arabic-first daily summary.",
      priority: "reports",
      status: "ready",
      canExecuteDirectly: true,
      stopGate: "none",
      expectedOutput: "Updated spoken daily briefing.",
      nextStep: "Update spoken lines for checks, blockers, and one next action.",
    },
    {
      id: "control_surface_status_review",
      title: "Control surface status review",
      layer: "Control Surfaces",
      reason: "Layer control surfaces show what can act, stop, or block.",
      priority: "architecture",
      status: "ready",
      canExecuteDirectly: true,
      stopGate: "none",
      expectedOutput: "Control surface status summary.",
      nextStep: "Review root, kernel, Product Truth, desktop, Earth, reports, and future gates.",
    },
  ];
}
