import "server-only";

import type {
  FounderApprovalItem,
  FounderCommandDeviceTarget,
  FounderCommandModule,
  FounderCommandSnapshot,
  FounderGuardianAlert,
  FounderLegalReview,
  FounderMediaApproval,
  FounderOpsSignal,
  FounderTreasuryControl,
} from "./types";

const deviceTargets: FounderCommandDeviceTarget[] = [
  "windows",
  "macos",
  "linux",
  "android",
  "ios",
];

const modules: FounderCommandModule[] = [
  {
    key: "planet_overview",
    label: "Planet Overview",
    purpose: "Shows global TPM Planet OS readiness across active, planned, inactive, blocked, and degraded systems.",
    dataSource: "Planet Blueprint, Product Truth, Founder Reporting, Visual Acceptance",
    platforms: ["desktop", "mobile"],
    readiness: "active_contract",
    riskLevel: "low",
    actionState: "read_only",
    allowedNow: ["view planet status", "view product truth", "view next safe actions"],
    plannedLater: ["native desktop overview", "mobile briefing summary"],
    truth: "Readiness contract exists; no native app dashboard is shipped.",
    blockedActions: ["fake metrics", "public route exposure"],
    mustNotFake: ["users", "revenue", "launch readiness"],
    mobileFriendly: true,
  },
  {
    key: "continents_states_map",
    label: "Continents & States Map",
    purpose: "Maps the Earth-like TPM hierarchy from continents to states, cities, workers, citizens, and resources.",
    dataSource: "Planet Earth Hierarchy and Planet Blueprint",
    platforms: ["desktop"],
    readiness: "active_contract",
    riskLevel: "low",
    actionState: "read_only",
    allowedNow: ["view hierarchy readiness", "view state reporting paths"],
    plannedLater: ["interactive private planet map", "mobile summary cards"],
    truth: "Hierarchy is deterministic architecture and does not claim live operational population metrics.",
    blockedActions: ["fake users", "fake economy metrics", "public command map"],
    mustNotFake: ["citizens", "activity", "resources"],
    mobileFriendly: false,
  },
  {
    key: "ministry_reports",
    label: "Ministry Reports",
    purpose: "Shows the 40-ministry reporting model, blockers, risks, automation levels, and Founder decision needs.",
    dataSource: "Founder Command Reporting Engine and Ministry Reports",
    platforms: ["desktop", "mobile"],
    readiness: "active_contract",
    riskLevel: "medium",
    actionState: "read_only",
    allowedNow: ["view ministry cards", "view blockers", "view next coordination action"],
    plannedLater: ["filterable desktop ministry console", "mobile attention list"],
    truth: "Ministry counts are blueprint/reporting counts, not real staff or user counts.",
    blockedActions: ["fake staff accounts", "fake completed handoffs"],
    mustNotFake: ["staff", "activity volume", "resolved work"],
    mobileFriendly: true,
  },
  {
    key: "presidency_coordination",
    label: "Presidency Coordination",
    purpose: "Shows inter-ministry message routing, workflow readiness, council review needs, and blocked categories.",
    dataSource: "Founder Presidency Coordination System",
    platforms: ["desktop", "mobile"],
    readiness: "active_contract",
    riskLevel: "high",
    actionState: "review_required",
    allowedNow: ["view workflow templates", "view blocked categories", "view review requirements"],
    plannedLater: ["audited message ledger", "owner-reviewed coordination decisions"],
    truth: "Coordination is readiness-only; no real workflow execution occurs.",
    blockedActions: ["real external workflow execution", "critical override", "unreviewed cross-ministry action"],
    mustNotFake: ["approvals", "resolved workflow counts", "production activation"],
    mobileFriendly: true,
  },
  {
    key: "councils_constitution",
    label: "Councils & Constitution",
    purpose: "Shows Constitutional, Legislative, and Executive Council signals and hard product laws.",
    dataSource: "Planet Governance and Constitution Rules",
    platforms: ["desktop", "mobile"],
    readiness: "active_contract",
    riskLevel: "critical",
    actionState: "blocked",
    allowedNow: ["view constitutional rules", "view council escalation paths"],
    plannedLater: ["policy drafting workflow", "audited council decision ledger"],
    truth: "Critical constitutional blocks cannot be bypassed by Founder approval wording.",
    blockedActions: ["guaranteed profit", "fake launch", "fake live/broker/feed/billing"],
    mustNotFake: ["legal authority", "certification", "launch gates"],
    mobileFriendly: true,
  },
  {
    key: "guardian_command",
    label: "Guardian Command",
    purpose: "Reviews abuse, auth, fraud, entitlement, prompt-injection, and safety signals.",
    dataSource: "Guardian + Legal Rules Engine and Founder Reporting",
    platforms: ["desktop", "mobile"],
    readiness: "active_contract",
    riskLevel: "medium",
    actionState: "review_required",
    allowedNow: ["view safety boundaries", "view blocked unsafe action categories"],
    plannedLater: ["owner-visible incident queue", "audited escalation actions"],
    truth: "Guardian command is contract-only; no invasive surveillance is introduced.",
    blockedActions: ["auth bypass", "private data exposure", "invasive surveillance"],
    mustNotFake: ["real enforcement", "surveillance", "resolved incidents"],
    mobileFriendly: true,
  },
  {
    key: "legal_counsel_command",
    label: "Legal Counsel Command",
    purpose: "Reviews risky claims across media, AI, VIP, Islamic wording, launch, broker/feed, and billing language.",
    dataSource: "Legal rules, claims policies, and Product Truth",
    platforms: ["desktop", "mobile"],
    readiness: "active_contract",
    riskLevel: "high",
    actionState: "founder_approval_required",
    allowedNow: ["view blocked claims", "view safe language", "view review requirements"],
    plannedLater: ["audited legal review workflow", "reviewed claim library"],
    truth: "Legal Counsel remains guidance only and does not claim legal certification.",
    blockedActions: ["legal certification claim", "fake compliance claim"],
    mustNotFake: ["legal advice", "Sharia certification", "regulatory approval"],
    mobileFriendly: true,
  },
  {
    key: "media_command",
    label: "Media Command",
    purpose: "Coordinates draft content, campaigns, AI video scripts, channel readiness, and approval state.",
    dataSource: "Content Factory, Media readiness, Approval Center",
    platforms: ["desktop", "mobile"],
    readiness: "active_contract",
    riskLevel: "high",
    actionState: "founder_approval_required",
    allowedNow: ["view draft readiness", "view required reviews"],
    plannedLater: ["audited content calendar", "Founder-reviewed publishing queue"],
    truth: "No social accounts are connected and no external publishing is active.",
    blockedActions: ["external publishing", "fake follower metrics", "copied competitor content"],
    mustNotFake: ["followers", "social accounts", "published campaigns"],
    mobileFriendly: true,
  },
  {
    key: "ai_video_studio_command",
    label: "AI Video Studio Command",
    purpose: "Tracks AI video script readiness, platform adaptation, review state, and publishing boundaries.",
    dataSource: "Content Factory and AI Video Studio docs",
    platforms: ["desktop", "mobile"],
    readiness: "active_contract",
    riskLevel: "high",
    actionState: "founder_approval_required",
    allowedNow: ["view script readiness", "view Legal/Guardian/Founder review requirements"],
    plannedLater: ["script review cards", "platform adaptation queue"],
    truth: "No upload automation, social tokens, or publishing is active.",
    blockedActions: ["media upload automation", "external posting", "fake video metrics"],
    mustNotFake: ["publishing", "views", "channel connection"],
    mobileFriendly: true,
  },
  {
    key: "companion_brain_command",
    label: "Companion & Brain Command",
    purpose: "Tracks assistant quality, AI/IQ boundaries, coaching intelligence, and safe guidance state.",
    dataSource: "Companion Context Engine and TPM Brain Context",
    platforms: ["desktop"],
    readiness: "active_contract",
    riskLevel: "medium",
    actionState: "review_required",
    allowedNow: ["view context quality", "view blocked capabilities", "view assistant safety boundaries"],
    plannedLater: ["Founder policy review for assistant changes", "quality tuning queue"],
    truth: "AI remains operator-assist and never guarantees predictions.",
    blockedActions: ["guaranteed signals", "trade execution", "auth bypass"],
    mustNotFake: ["prediction certainty", "signals", "autonomous trading"],
    mobileFriendly: false,
  },
  {
    key: "treasury_command",
    label: "Treasury Command",
    purpose: "Tracks Free, Pro, VIP, Enterprise, subscription, and performance-fee readiness truth.",
    dataSource: "Plan Entitlement Engine and Product Truth",
    platforms: ["desktop"],
    readiness: "active_contract",
    riskLevel: "high",
    actionState: "founder_approval_required",
    allowedNow: ["view billing inactive truth", "view plan readiness", "view 0% current fee"],
    plannedLater: ["audited entitlement changes", "billing provider readiness review"],
    truth: "Billing is inactive and performance-based revenue remains hidden/inactive at 0%.",
    blockedActions: ["billing activation", "fake paid access", "public performance-fee UI"],
    mustNotFake: ["paid access", "subscriptions", "fee activation"],
    mobileFriendly: false,
  },
  {
    key: "plan_citizen_classes_command",
    label: "Plan / Citizen Classes Command",
    purpose: "Tracks Guest, Demo, Pro, VIP, Enterprise, Staff, and Founder access layers.",
    dataSource: "Plan Entitlement Engine and Citizen Access Map",
    platforms: ["desktop", "mobile"],
    readiness: "active_contract",
    riskLevel: "medium",
    actionState: "read_only",
    allowedNow: ["view plan readiness", "view citizen classes", "view user-plan boundaries"],
    plannedLater: ["audited entitlement console", "owner-only plan activation review"],
    truth: "Founder Command is owner-only and never a user-plan feature.",
    blockedActions: ["fake VIP activation", "Founder Command as plan perk", "billing claim"],
    mustNotFake: ["Pro active", "VIP active", "Enterprise available"],
    mobileFriendly: true,
  },
  {
    key: "community_vip_rooms_command",
    label: "Community / VIP Rooms Command",
    purpose: "Tracks community readiness, moderation rules, Pro/VIP rooms, and anti-scam protections.",
    dataSource: "Community architecture and VIP room roadmap",
    platforms: ["desktop"],
    readiness: "planned",
    riskLevel: "medium",
    actionState: "review_required",
    allowedNow: ["view planned room boundaries", "view moderation requirements"],
    plannedLater: ["moderation review queue", "VIP room readiness cards"],
    truth: "Community architecture exists; no social network is shipped.",
    blockedActions: ["signal selling", "fake rooms", "unmoderated public claims"],
    mustNotFake: ["active rooms", "members", "moderation enforcement"],
    mobileFriendly: false,
  },
  {
    key: "academy_journal_coach_command",
    label: "Academy / Journal / Coach Command",
    purpose: "Tracks education, journal, coaching, and decision replay readiness.",
    dataSource: "Journal/Coach readiness and Academy docs",
    platforms: ["desktop"],
    readiness: "planned",
    riskLevel: "medium",
    actionState: "review_required",
    allowedNow: ["view prompt readiness", "view no-advice boundaries"],
    plannedLater: ["curriculum queue", "decision replay review"],
    truth: "Learning systems remain bounded by no-financial-advice and no-guarantee rules.",
    blockedActions: ["financial advice", "gambling-style pressure", "profit guarantees"],
    mustNotFake: ["coaching outcomes", "performance improvement", "financial advice"],
    mobileFriendly: false,
  },
  {
    key: "engineering_command",
    label: "Engineering Command",
    purpose: "Tracks product gaps, regressions, visual tasks, desktop/mobile work, and integration readiness.",
    dataSource: "Build Planner, Visual Acceptance, diagnostics, and route smoke",
    platforms: ["desktop"],
    readiness: "active_contract",
    riskLevel: "medium",
    actionState: "review_required",
    allowedNow: ["view validation requirements", "view safe next engineering tasks"],
    plannedLater: ["private build planning queue", "release gate checklist"],
    truth: "Engineering command is planning/readiness only and does not close real blockers by wording.",
    blockedActions: ["fake capability closure", "secret exposure"],
    mustNotFake: ["tests passed without running", "production readiness", "integration activation"],
    mobileFriendly: false,
  },
  {
    key: "ops_tower_command",
    label: "Ops Tower Command",
    purpose: "Tracks health, incidents, monitoring readiness, staging/production blockers, secret rotation, and recovery actions.",
    dataSource: "Diagnostics, Ops readiness, Production gates",
    platforms: ["desktop", "mobile"],
    readiness: "active_contract",
    riskLevel: "high",
    actionState: "founder_approval_required",
    allowedNow: ["view ops blockers", "view production forbidden truth", "view recovery readiness"],
    plannedLater: ["incident review cards", "audited production gate approvals"],
    truth: "Monitoring and production remain truthful and cannot be faked by command summaries.",
    blockedActions: ["fake monitoring", "production deployment without gates", "secret display"],
    mustNotFake: ["production active", "monitoring complete", "secrets rotated"],
    mobileFriendly: true,
  },
  {
    key: "quality_visual_acceptance_command",
    label: "Quality / Visual Acceptance Command",
    purpose: "Tracks visual acceptance, regression quality, dark/light/RTL readiness, and human acceptance gaps.",
    dataSource: "Visual Acceptance Engine and regression tests",
    platforms: ["desktop"],
    readiness: "active_contract",
    riskLevel: "medium",
    actionState: "review_required",
    allowedNow: ["view rubric scores", "view Ahmad acceptance requirement"],
    plannedLater: ["private screenshot acceptance queue", "release visual gate"],
    truth: "Visual scores are estimates; Ahmad human acceptance remains required.",
    blockedActions: ["fake 10/10", "skip visual proof"],
    mustNotFake: ["human acceptance", "screenshot proof", "final polish"],
    mobileFriendly: false,
  },
  {
    key: "rights_brand_command",
    label: "Rights & Brand Command",
    purpose: "Tracks brand/IP, competitor-copying boundaries, Swiss-inspired wording, and rights review.",
    dataSource: "Rights/Brand docs and Legal rules",
    platforms: ["desktop", "mobile"],
    readiness: "active_contract",
    riskLevel: "high",
    actionState: "founder_approval_required",
    allowedNow: ["view rights boundaries", "view brand safe language"],
    plannedLater: ["brand approval review cards", "partnership rights workflow"],
    truth: "Swiss-inspired design is allowed; fake Swiss legal/company status is blocked.",
    blockedActions: ["competitor copying", "uncontracted brand use", "fake Swiss legal status"],
    mustNotFake: ["contracts", "company status", "IP permission"],
    mobileFriendly: true,
  },
  {
    key: "islamic_review_command",
    label: "Islamic Review Command",
    purpose: "Tracks Islamic account wording, certification truth, and legal/religious review requirements.",
    dataSource: "Legal rules, account type truth, Islamic review docs",
    platforms: ["desktop", "mobile"],
    readiness: "active_contract",
    riskLevel: "critical",
    actionState: "blocked",
    allowedNow: ["view not-certified truth", "view wording review requirements"],
    plannedLater: ["real certification evidence workflow", "Founder review after Legal/rights review"],
    truth: "Islamic/Sharia certification is not claimed.",
    blockedActions: ["fake Sharia certification", "Islamic guarantee claim"],
    mustNotFake: ["certification", "scholar review", "religious compliance"],
    mobileFriendly: true,
  },
  {
    key: "founder_approval_queue",
    label: "Founder Approval Queue",
    purpose: "Collects high-risk reviewed items that require Founder decision.",
    dataSource: "Approval Center readiness and Presidency Coordination",
    platforms: ["desktop", "mobile"],
    readiness: "active_contract",
    riskLevel: "high",
    actionState: "founder_approval_required",
    allowedNow: ["view approval categories", "view lifecycle states", "view hard blocks"],
    plannedLater: ["audited approve/reject/review-later actions", "step-up confirmation"],
    truth: "Approval queue is contract-only until owner app auth and audit workflow are implemented.",
    blockedActions: ["bypass Guardian", "bypass Legal", "approve hard-blocked content"],
    mustNotFake: ["approval execution", "published result", "activation"],
    mobileFriendly: true,
  },
];

const approvalQueue: FounderApprovalItem[] = [
  {
    id: "founder-command-public-launch-wording",
    title: "Public launch wording",
    module: "founder_approval_queue",
    lifecycle: "blocked",
    riskLevel: "critical",
    actionState: "blocked",
    requiredReviews: ["Guardian", "Legal", "Ops Tower", "Founder"],
    safeNextStep: "Keep launch wording blocked until production, monitoring, legal, and release gates pass.",
  },
  {
    id: "founder-command-media-drafts",
    title: "Media and AI video drafts",
    module: "media_command",
    lifecycle: "pending_guardian_review",
    riskLevel: "high",
    actionState: "founder_approval_required",
    requiredReviews: ["Guardian", "Legal", "Founder"],
    safeNextStep: "Review draft language for blocked claims before any future publishing workflow.",
  },
  {
    id: "founder-command-vip-claim-review",
    title: "Pro/VIP claim review",
    module: "plan_citizen_classes_command",
    lifecycle: "pending_legal_review",
    riskLevel: "high",
    actionState: "founder_approval_required",
    requiredReviews: ["Legal", "Guardian", "Treasury", "Founder"],
    safeNextStep: "Keep Pro/VIP planned until entitlement, billing, and claims review gates exist.",
  },
  {
    id: "founder-command-billing-wording",
    title: "Billing and subscription wording",
    module: "treasury_command",
    lifecycle: "pending_treasury_review",
    riskLevel: "high",
    actionState: "founder_approval_required",
    requiredReviews: ["Treasury", "Legal", "Founder"],
    safeNextStep: "Keep billing inactive and avoid checkout or paid-access language.",
  },
  {
    id: "founder-command-sponsored-clock-review",
    title: "Sponsored Swiss Precision Clock partnership wording",
    module: "rights_brand_command",
    lifecycle: "pending_legal_review",
    riskLevel: "high",
    actionState: "founder_approval_required",
    requiredReviews: ["Rights/IP", "Legal", "Guardian", "Founder"],
    safeNextStep:
      "Keep sponsored clock and brand partnership language inactive until a signed contract and review chain exist.",
  },
  {
    id: "founder-command-vip-community-review",
    title: "Community and VIP room readiness",
    module: "community_vip_rooms_command",
    lifecycle: "pending_guardian_review",
    riskLevel: "high",
    actionState: "founder_approval_required",
    requiredReviews: ["Guardian", "Legal", "Founder"],
    safeNextStep:
      "Keep all community and VIP rooms planned-only until moderation, entitlement, and claim-review gates exist.",
  },
  {
    id: "founder-command-production-secret-action",
    title: "Production or secret action",
    module: "ops_tower_command",
    lifecycle: "blocked",
    riskLevel: "critical",
    actionState: "blocked",
    requiredReviews: ["Guardian", "Legal", "Engineering", "Founder"],
    safeNextStep: "Keep production and secret actions blocked until owner auth, audit, and production gates exist.",
  },
];

const treasury: FounderTreasuryControl[] = [
  {
    id: "billing-readiness",
    label: "Billing readiness",
    readiness: "inactive",
    riskLevel: "high",
    actionState: "founder_approval_required",
    currentTruth: "Billing, checkout, and subscriptions are inactive.",
    activationRequirements: ["billing provider", "legal review", "user consent", "Founder approval", "audit trail"],
  },
  {
    id: "performance-fee-readiness",
    label: "Performance-based revenue research",
    readiness: "blocked",
    riskLevel: "critical",
    actionState: "blocked",
    currentTruth: "Current fee is 0%; any 5%-10% future concept is hidden, inactive, and requires legal/regulatory review.",
    activationRequirements: ["legal review", "regulatory review", "billing infrastructure", "public disclosure", "user consent"],
  },
  {
    id: "planet-economy-growth-readiness",
    label: "Plan economy and growth readiness",
    readiness: "planned",
    riskLevel: "medium",
    actionState: "review_required",
    currentTruth:
      "Free is active for paper-safe trust; Pro, VIP, and Institutional remain planned/future with no fake paid activation.",
    activationRequirements: [
      "entitlement implementation",
      "support readiness",
      "legal review",
      "safety review",
      "owner approval",
    ],
  },
];

const media: FounderMediaApproval[] = [
  {
    id: "media-command-draft-queue",
    channel: "planned multi-channel media office",
    contentType: "campaign",
    lifecycle: "draft",
    riskLevel: "high",
    currentTruth: "No social accounts are connected and no external publishing is active.",
  },
  {
    id: "ai-video-studio-script-queue",
    channel: "planned AI Video Studio",
    contentType: "ai_video_script",
    lifecycle: "draft",
    riskLevel: "high",
    currentTruth:
      "Video scripts may be drafted for review only; no upload, publishing, tokens, views, or channel metrics exist.",
  },
];

const guardian: FounderGuardianAlert[] = [
  {
    id: "guardian-command-foundation",
    category: "command_app_access",
    riskLevel: "high",
    actionState: "founder_approval_required",
    currentTruth: "Owner-only access is required before any command API or route can be exposed.",
  },
];

const legal: FounderLegalReview[] = [
  {
    id: "legal-command-blocked-claims",
    category: "blocked_claims",
    lifecycle: "blocked",
    riskLevel: "high",
    blockedClaimPatterns: [
      "guaranteed profit",
      "win-rate claim",
      "risk-free",
      "fake live trading",
      "fake broker connected",
      "fake billing active",
      "fake public launch",
      "fake Islamic certification",
    ],
    safeLanguage: [
      "paper-only",
      "fallback-first",
      "operator review required",
      "not certified",
      "decision support",
      "no guarantee",
    ],
  },
];

const ops: FounderOpsSignal[] = [
  {
    id: "founder-command-native-shell",
    label: "Native command app shell",
    readiness: "planned",
    riskLevel: "medium",
    currentTruth: "Desktop and mobile command app foundations exist as docs/contracts only.",
    safeNextStep: "Implement private owner app shell only after owner auth and audit foundations are ready.",
  },
  {
    id: "founder-command-readiness-api",
    label: "Owner-only readiness API",
    readiness: "active_contract",
    riskLevel: "high",
    currentTruth:
      "Sanitized read-only Founder readiness APIs exist; they do not execute approvals, expose secrets, publish, bill, launch, or route money.",
    safeNextStep:
      "Keep APIs readiness-only until private owner app authentication, step-up confirmation, and audit requirements are finalized.",
  },
  {
    id: "founder-command-local-day-one-gate",
    label: "Local Day One acceptance gate",
    readiness: "active_contract",
    riskLevel: "medium",
    currentTruth:
      "Local Day One readiness can be viewed as a closed local acceptance gate; it does not evaluate global launch or activate approvals.",
    safeNextStep:
      "Use the gate to start local operations review only after validation and Ahmad visual review.",
  },
];

export function getFounderCommandSnapshot(checkedAt = new Date().toISOString()): FounderCommandSnapshot {
  return {
    checkedAt,
    mode: "founder_command_app_foundation",
    access: {
      state: "owner_only_planned",
      publicRouteExposed: false,
      normalUserVisible: false,
      ownerOnly: true,
      readOnlyDefault: true,
    },
    deviceTargets,
    truth: {
      nativeDesktopShipped: false,
      nativeMobileShipped: false,
      liveExecutionEnabled: false,
      realMoneyRoutingEnabled: false,
      brokerActivationFaked: false,
      feedActivationFaked: false,
      billingActivated: false,
      publicLaunchClaimed: false,
      socialAccountsConnected: false,
      secretsExposed: false,
    },
    modules,
    approvalQueue,
    treasury,
    media,
    guardian,
    legal,
    ops,
    blockers: [
      "owner app authentication is not shipped",
      "native desktop shell is not shipped",
      "native mobile shell is not shipped",
      "public Founder route is intentionally not exposed",
      "live execution and real-money routing remain blocked",
      "billing, broker, feed, media posting, and public launch remain inactive",
    ],
  };
}
