import "server-only";

import type {
  PlanetConstructionEventType,
  PlanetConstructionReview,
  PlanetEventOwnership,
} from "./types";

const ownershipByType: Record<
  PlanetConstructionEventType,
  Omit<PlanetEventOwnership, "requiredReviews"> & {
    requiredReviews: PlanetConstructionReview[];
  }
> = {
  visual_gap_detected: {
    ownerMinistry: "Product Quality & Testing Ministry",
    supportingMinistries: ["Engineering & Infrastructure Ministry"],
    requiredReviews: ["quality", "visual_acceptance"],
    escalationTarget: "none",
    founderVisible: true,
    userVisible: false,
  },
  ux_confusion_detected: {
    ownerMinistry: "Product Quality & Testing Ministry",
    supportingMinistries: ["Personal Companion Ministry"],
    requiredReviews: ["quality"],
    escalationTarget: "none",
    founderVisible: true,
    userVisible: false,
  },
  chart_quality_low: {
    ownerMinistry: "Markets & Trading Ministry",
    supportingMinistries: ["Product Quality & Testing Ministry", "Engineering & Infrastructure Ministry"],
    requiredReviews: ["quality", "visual_acceptance"],
    escalationTarget: "none",
    founderVisible: true,
    userVisible: false,
  },
  companion_context_missing: {
    ownerMinistry: "Personal Companion Ministry",
    supportingMinistries: ["AI / IQ / Brain Ministry"],
    requiredReviews: ["quality"],
    escalationTarget: "none",
    founderVisible: true,
    userVisible: false,
  },
  assistant_response_risk: {
    ownerMinistry: "Personal Companion Ministry",
    supportingMinistries: ["Justice / Legal / Compliance Ministry", "Guardian & Defense Ministry"],
    requiredReviews: ["guardian", "legal", "quality"],
    escalationTarget: "guardian",
    founderVisible: true,
    userVisible: false,
  },
  plan_copy_conflict: {
    ownerMinistry: "Plans & Subscriptions Ministry",
    supportingMinistries: ["Justice / Legal / Compliance Ministry", "Product Quality & Testing Ministry"],
    requiredReviews: ["treasury", "legal", "guardian", "quality"],
    escalationTarget: "founder_command",
    founderVisible: true,
    userVisible: false,
  },
  product_truth_conflict: {
    ownerMinistry: "Constitutional Ministry",
    supportingMinistries: ["Guardian & Defense Ministry", "Justice / Legal / Compliance Ministry"],
    requiredReviews: ["product_truth", "guardian", "legal"],
    escalationTarget: "founder_command",
    founderVisible: true,
    userVisible: false,
  },
  legal_claim_risk: {
    ownerMinistry: "Justice / Legal / Compliance Ministry",
    supportingMinistries: ["Guardian & Defense Ministry"],
    requiredReviews: ["legal", "guardian"],
    escalationTarget: "legal",
    founderVisible: true,
    userVisible: false,
  },
  guardian_blocked_action: {
    ownerMinistry: "Guardian & Defense Ministry",
    supportingMinistries: ["Justice / Legal / Compliance Ministry"],
    requiredReviews: ["guardian", "legal"],
    escalationTarget: "guardian",
    founderVisible: true,
    userVisible: false,
  },
  ministry_report_due: {
    ownerMinistry: "Founder Presidency & Coordination Ministry",
    supportingMinistries: ["Executive Implementation Ministry"],
    requiredReviews: ["quality"],
    escalationTarget: "none",
    founderVisible: true,
    userVisible: false,
  },
  founder_approval_required: {
    ownerMinistry: "Supreme Command Ministry",
    supportingMinistries: ["Founder Presidency & Coordination Ministry"],
    requiredReviews: ["founder"],
    escalationTarget: "founder_command",
    founderVisible: true,
    userVisible: false,
  },
  codex_task_needed: {
    ownerMinistry: "Engineering & Infrastructure Ministry",
    supportingMinistries: ["Product Quality & Testing Ministry"],
    requiredReviews: ["engineering", "quality"],
    escalationTarget: "none",
    founderVisible: true,
    userVisible: false,
  },
  validation_failed: {
    ownerMinistry: "Product Quality & Testing Ministry",
    supportingMinistries: ["Engineering & Infrastructure Ministry"],
    requiredReviews: ["quality", "engineering"],
    escalationTarget: "none",
    founderVisible: true,
    userVisible: false,
  },
  build_failed: {
    ownerMinistry: "Engineering & Infrastructure Ministry",
    supportingMinistries: ["Product Quality & Testing Ministry"],
    requiredReviews: ["engineering", "quality"],
    escalationTarget: "none",
    founderVisible: true,
    userVisible: false,
  },
  lint_failed: {
    ownerMinistry: "Product Quality & Testing Ministry",
    supportingMinistries: ["Engineering & Infrastructure Ministry"],
    requiredReviews: ["quality", "engineering"],
    escalationTarget: "none",
    founderVisible: true,
    userVisible: false,
  },
  regression_failed: {
    ownerMinistry: "Product Quality & Testing Ministry",
    supportingMinistries: ["Engineering & Infrastructure Ministry"],
    requiredReviews: ["quality", "engineering"],
    escalationTarget: "none",
    founderVisible: true,
    userVisible: false,
  },
  screenshot_missing: {
    ownerMinistry: "Product Quality & Testing Ministry",
    supportingMinistries: ["Engineering & Infrastructure Ministry"],
    requiredReviews: ["visual_acceptance", "quality"],
    escalationTarget: "none",
    founderVisible: true,
    userVisible: false,
  },
  public_language_leak_detected: {
    ownerMinistry: "Brand, Rights & IP Ministry",
    supportingMinistries: ["Justice / Legal / Compliance Ministry", "Product Quality & Testing Ministry"],
    requiredReviews: ["legal", "quality"],
    escalationTarget: "legal",
    founderVisible: true,
    userVisible: false,
  },
  internal_term_leak_detected: {
    ownerMinistry: "Brand, Rights & IP Ministry",
    supportingMinistries: ["Product Quality & Testing Ministry"],
    requiredReviews: ["quality", "legal"],
    escalationTarget: "legal",
    founderVisible: true,
    userVisible: false,
  },
  billing_activation_requested: {
    ownerMinistry: "Treasury & Economy Ministry",
    supportingMinistries: ["Justice / Legal / Compliance Ministry", "Supreme Command Ministry"],
    requiredReviews: ["treasury", "legal", "guardian", "founder"],
    escalationTarget: "founder_command",
    founderVisible: true,
    userVisible: false,
  },
  live_execution_requested: {
    ownerMinistry: "Execution & Ticket Ministry",
    supportingMinistries: ["Markets & Trading Ministry", "Guardian & Defense Ministry", "Justice / Legal / Compliance Ministry"],
    requiredReviews: ["guardian", "legal", "engineering", "founder"],
    escalationTarget: "guardian",
    founderVisible: true,
    userVisible: false,
  },
  real_money_requested: {
    ownerMinistry: "Treasury & Economy Ministry",
    supportingMinistries: ["Execution & Ticket Ministry", "Justice / Legal / Compliance Ministry"],
    requiredReviews: ["treasury", "legal", "guardian", "founder"],
    escalationTarget: "guardian",
    founderVisible: true,
    userVisible: false,
  },
  broker_feed_activation_requested: {
    ownerMinistry: "Market Data & Feed Ministry",
    supportingMinistries: ["External Integrations Ministry", "Guardian & Defense Ministry", "Justice / Legal / Compliance Ministry"],
    requiredReviews: ["engineering", "guardian", "legal", "founder"],
    escalationTarget: "guardian",
    founderVisible: true,
    userVisible: false,
  },
  social_publish_requested: {
    ownerMinistry: "Media & Communications Ministry",
    supportingMinistries: ["Justice / Legal / Compliance Ministry", "Guardian & Defense Ministry"],
    requiredReviews: ["legal", "guardian", "founder"],
    escalationTarget: "founder_command",
    founderVisible: true,
    userVisible: false,
  },
  partnership_claim_requested: {
    ownerMinistry: "Brand, Rights & IP Ministry",
    supportingMinistries: ["Partnerships & Sponsorships Ministry", "Justice / Legal / Compliance Ministry"],
    requiredReviews: ["legal", "guardian", "founder"],
    escalationTarget: "legal",
    founderVisible: true,
    userVisible: false,
  },
  vip_claim_requested: {
    ownerMinistry: "Plans & Subscriptions Ministry",
    supportingMinistries: ["Justice / Legal / Compliance Ministry", "Guardian & Defense Ministry"],
    requiredReviews: ["treasury", "legal", "guardian", "founder"],
    escalationTarget: "founder_command",
    founderVisible: true,
    userVisible: false,
  },
  islamic_certification_claim_requested: {
    ownerMinistry: "Special Accounts & Islamic Review Ministry",
    supportingMinistries: ["Justice / Legal / Compliance Ministry", "Brand, Rights & IP Ministry"],
    requiredReviews: ["legal", "guardian", "founder"],
    escalationTarget: "legal",
    founderVisible: true,
    userVisible: false,
  },
  safe_docs_update_needed: {
    ownerMinistry: "Engineering & Infrastructure Ministry",
    supportingMinistries: ["Product Quality & Testing Ministry"],
    requiredReviews: ["quality"],
    escalationTarget: "none",
    founderVisible: false,
    userVisible: false,
  },
  safe_ui_polish_needed: {
    ownerMinistry: "Product Quality & Testing Ministry",
    supportingMinistries: ["Engineering & Infrastructure Ministry"],
    requiredReviews: ["quality", "visual_acceptance"],
    escalationTarget: "none",
    founderVisible: true,
    userVisible: false,
  },
  task_completed: {
    ownerMinistry: "Product Quality & Testing Ministry",
    supportingMinistries: ["Founder Presidency & Coordination Ministry"],
    requiredReviews: ["quality"],
    escalationTarget: "none",
    founderVisible: true,
    userVisible: false,
  },
  task_rejected: {
    ownerMinistry: "Founder Presidency & Coordination Ministry",
    supportingMinistries: ["Product Quality & Testing Ministry"],
    requiredReviews: ["quality"],
    escalationTarget: "founder_command",
    founderVisible: true,
    userVisible: false,
  },
  task_blocked: {
    ownerMinistry: "Guardian & Defense Ministry",
    supportingMinistries: ["Justice / Legal / Compliance Ministry"],
    requiredReviews: ["guardian", "legal"],
    escalationTarget: "guardian",
    founderVisible: true,
    userVisible: false,
  },
};

export function resolvePlanetEventOwnership(
  type: PlanetConstructionEventType
): PlanetEventOwnership {
  return ownershipByType[type];
}
