import type { EarthRealityMatrixPage } from "./types";

export const publicWorldMatrix: EarthRealityMatrixPage[] = [
  {
    surface: "home",
    publicLabel: "Home",
    whereAmI: "The public Trading Pro Max entry world.",
    whatCanIDo: "Understand the product, enter the workspace, explore plans, apps, learning, community, and support.",
    activeNow: "Web workspace, Free Earth experience, paper-safe status, Assistant entry, public navigation.",
    plannedFuture: "Pro/VIP depth, desktop/mobile/tablet readiness, richer support/community layers.",
    blockedInactive: "Live execution, real money, billing, broker/feed, social publishing, production launch.",
    nextStep: "Enter Trading Workspace or review Apps / Platforms and Plans.",
  },
  {
    surface: "trading_workspace",
    publicLabel: "Trading Workspace",
    whereAmI: "The chart-first paper-safe practice terminal.",
    whatCanIDo: "Review charts, paper ticket preflight, Assistant guidance, Journal/Coach reflection, and diagnostics.",
    activeNow: "Paper-safe execution, fallback-labeled market context, chart comfort controls.",
    plannedFuture: "Professional workflow memory, alerts, deeper replay, richer coaching.",
    blockedInactive: "Live orders, broker routing, real money, guaranteed signals.",
    nextStep: "Practice in paper mode and write a decision note.",
  },
  {
    surface: "markets",
    publicLabel: "Markets",
    whereAmI: "The public market-category overview.",
    whatCanIDo: "Inspect Forex, Crypto, Commodities, Indices, and future/planned market coverage.",
    activeNow: "Paper-ready market context and fallback truth.",
    plannedFuture: "More categories and provider readiness after review.",
    blockedInactive: "Live feed, broker connectivity, advice, and routing.",
    nextStep: "Open the workspace for paper-safe chart review.",
  },
  {
    surface: "plans",
    publicLabel: "Plans",
    whereAmI: "The public plan-realm comparison.",
    whatCanIDo: "Compare Free, Pro, VIP, and Institutional access truth.",
    activeNow: "Free Earth complete starting experience.",
    plannedFuture: "Pro professional tools, VIP premium layer, Institutional team layer.",
    blockedInactive: "Checkout, paid activation, fake premium unlocks.",
    nextStep: "Use Free now; read planned states honestly.",
  },
  {
    surface: "apps_platforms",
    publicLabel: "Apps / Platforms",
    whereAmI: "The platform availability map.",
    whatCanIDo: "See Web current and Desktop/Mobile/Tablet readiness.",
    activeNow: "Web app current.",
    plannedFuture: "Desktop and mobile planned, tablet future.",
    blockedInactive: "Fake downloads or store releases.",
    nextStep: "Use Web now.",
  },
  {
    surface: "academy",
    publicLabel: "Academy",
    whereAmI: "The learning path.",
    whatCanIDo: "Learn paper trading basics, chart basics, risk basics, Why Blocked, Assistant, and Journal/Coach.",
    activeNow: "Basic learning structure.",
    plannedFuture: "Deeper Pro/VIP learning paths and reviews.",
    blockedInactive: "Financial advice and signal teaching.",
    nextStep: "Start with Getting Started or Why Blocked.",
  },
  {
    surface: "community",
    publicLabel: "Community",
    whereAmI: "The planned learning and feedback community layer.",
    whatCanIDo: "Understand future learning, feedback, support, Pro community, and VIP rooms readiness.",
    activeNow: "Readiness descriptions only.",
    plannedFuture: "Learning spaces, feedback spaces, support spaces, Pro community, VIP rooms.",
    blockedInactive: "Fake members, signal rooms, copy trading, profit screenshots.",
    nextStep: "Use support/feedback readiness while community remains planned.",
  },
  {
    surface: "support",
    publicLabel: "Support",
    whereAmI: "The public support readiness surface.",
    whatCanIDo: "Find Help Center, Contact Support, Report a Problem, Security Contact, and Partnership Contact readiness.",
    activeNow: "Support path and readiness copy.",
    plannedFuture: "Provider-backed workflows after review.",
    blockedInactive: "Fake ticket backend and email sending.",
    nextStep: "Use available support guidance without sending secrets.",
  },
  {
    surface: "settings",
    publicLabel: "Settings",
    whereAmI: "Your public-safe controls.",
    whatCanIDo: "Adjust theme, language, Adaptive Atmosphere, Personal Reality, workspace comfort, and paper defaults.",
    activeNow: "Free controls: Clean Earth, Calm Workspace, Chart Comfort, Static, Low Motion, High Contrast.",
    plannedFuture: "Professional, premium, and institutional reality profiles.",
    blockedInactive: "Billing, live, broker/feed, private systems.",
    nextStep: "Choose an allowed Personal Reality profile or ask TPM Assistant.",
  },
  {
    surface: "diagnostics",
    publicLabel: "Diagnostics",
    whereAmI: "The public-safe readiness report.",
    whatCanIDo: "Check system, workspace, plan, Assistant, Product Truth, Environment, Earth Reality, and Personal Reality readiness.",
    activeNow: "Readiness reports and blocked-state truth.",
    plannedFuture: "More readiness detail as public systems mature.",
    blockedInactive: "Secrets, private command internals, internal memory.",
    nextStep: "Review blocked/inactive items before assuming capability.",
  },
];

export function getPublicWorldMatrix() {
  return publicWorldMatrix;
}
