import "server-only";

import type { CodexMemoryLesson } from "./types";

export function getCodexMemoryLessons(): CodexMemoryLesson[] {
  return [
    {
      lessonId: "codex_memory_no_generated_images",
      taskType: "founder_preference",
      outcome: "future_rule",
      reason: "Ahmad does not want generated images unless explicitly requested.",
      filesTouched: [],
      risk: "medium",
      ahmadFeedback: "No generated images unless I ask for them.",
      knownRepeatedMistake: "Adding raster or generated assets during visual work.",
      futureRule:
        "Use code-native UI, CSS, SVG, or existing vector systems; do not generate raster assets by default.",
      avoidPattern: "Creating images or stock-like media for product surfaces.",
      acceptedPattern: "Use deterministic UI/CSS and ask for explicit image approval first.",
      noSecrets: true,
      noPrivateSensitiveData: true,
    },
    {
      lessonId: "codex_memory_public_logo_subtitle_rejected",
      taskType: "logo_identity",
      outcome: "rejected_pattern",
      reason: "Public logo subtitle treatment was rejected.",
      filesTouched: [],
      risk: "high",
      ahmadFeedback: "Public logo subtitle rejected.",
      knownRepeatedMistake: "Adding explanatory subtitle text under the logo.",
      futureRule: "Keep logo identity simple and await Founder visual approval.",
      avoidPattern: "Subtitle-heavy brand lockups.",
      acceptedPattern: "Founder-approved clean Trading Pro Max identity only.",
      noSecrets: true,
      noPrivateSensitiveData: true,
    },
    {
      lessonId: "codex_memory_old_logo_not_accepted",
      taskType: "logo_identity",
      outcome: "repeated_mistake",
      reason: "Old logo direction is not accepted.",
      filesTouched: [],
      risk: "high",
      ahmadFeedback: "Old logo not accepted.",
      knownRepeatedMistake: "Returning to an identity direction Ahmad rejected.",
      futureRule: "Do not reuse rejected logo directions without explicit Founder instruction.",
      avoidPattern: "Recycling rejected brand shapes or subtitles.",
      acceptedPattern: "Treat identity as Founder-approval-required.",
      noSecrets: true,
      noPrivateSensitiveData: true,
    },
    {
      lessonId: "codex_memory_chart_annoyance_guard",
      taskType: "visual_polish",
      outcome: "future_rule",
      reason: "Chart annoyance must be guarded because the workstation is chart-first.",
      filesTouched: [],
      risk: "medium",
      ahmadFeedback: "Chart annoyance must be fixed carefully.",
      knownRepeatedMistake: "Letting diagnostics, panels, or copy crowd the chart.",
      futureRule: "Protect chart-first hierarchy and capture visual proof for chart changes.",
      avoidPattern: "Adding clutter around the chart or changing layout without proof.",
      acceptedPattern: "Small scoped chart polish with screenshots and no execution changes.",
      noSecrets: true,
      noPrivateSensitiveData: true,
    },
    {
      lessonId: "codex_memory_free_simplicity",
      taskType: "copy_cleanup",
      outcome: "accepted_pattern",
      reason: "Free public simplicity must be protected.",
      filesTouched: [],
      risk: "low",
      ahmadFeedback: "Free should stay simple to normal users.",
      knownRepeatedMistake: "Explaining internal systems in public plan surfaces.",
      futureRule: "Keep Free, Pro, VIP, and Institutional public naming simple and truthful.",
      avoidPattern: "Over-explaining governance or readiness in public plan cards.",
      acceptedPattern: "Public copy says paper-safe, planned, inactive, future, or readiness.",
      noSecrets: true,
      noPrivateSensitiveData: true,
    },
    {
      lessonId: "codex_memory_internal_terms_no_public_leak",
      taskType: "founder_command",
      outcome: "blocked_category",
      reason: "Founder/internal terms must not leak to normal users.",
      filesTouched: [],
      risk: "critical",
      ahmadFeedback: "Public users must not see internal governance language.",
      knownRepeatedMistake: "Surfacing Founder Command or construction terminology in public Diagnostics.",
      futureRule:
        "Sanitize internal terms in public UI and keep full details inside private APIs/docs.",
      avoidPattern: "Public navigation or plan features mentioning internal control systems.",
      acceptedPattern: "Public-safe readiness labels with private detail behind Founder routes.",
      noSecrets: true,
      noPrivateSensitiveData: true,
    },
    {
      lessonId: "codex_memory_no_overbuilding_home",
      taskType: "public_ui",
      outcome: "future_rule",
      reason: "Home must not be overbuilt or crowded.",
      filesTouched: [],
      risk: "medium",
      ahmadFeedback: "Do not overbuild Home.",
      knownRepeatedMistake: "Adding too many cards or internal explanations to the first viewport.",
      futureRule: "Keep Home focused on Trading Pro Max product entry and public-safe next actions.",
      avoidPattern: "Crowding Home with internal readiness systems.",
      acceptedPattern: "Simple public entry with clear product truth and no internal leakage.",
      noSecrets: true,
      noPrivateSensitiveData: true,
    },
  ];
}
