import "server-only";

import type { FinalConvergenceLayer } from "./types";

const blockedByDefault = [
  "billing activation",
  "live execution",
  "real-money routing",
  "broker/feed activation",
  "production secrets",
  "social publishing",
  "public launch activation",
  "fake claims",
  "Alkon public exposure",
];

export const FINAL_CONVERGENCE_LAYERS = [
  {
    layerId: "public_earth_world",
    type: "public_user_layer",
    name: "Public Earth World",
    purpose:
      "Unifies Home, Workspace, Markets, Plans, Apps, Academy, Community, Support, Settings, and Diagnostics into a public-safe Trading Pro Max world.",
    world: "public_earth_world",
    owner: "Product Truth + Public Surface Boundaries",
    dependencies: ["product_truth", "plan_realms", "planetary_environment"],
    outputs: ["Public product navigation", "Paper-safe copy", "Clean readiness"],
    riskLevel: "medium",
    publicVisible: true,
    founderVisible: true,
    validationRequired: [
      "public leak prevention",
      "route smoke",
      "visual public proof",
    ],
    memoryRule:
      "Record public wording that users understand and reject any internal vocabulary leakage.",
    nextPossibleLayers: ["visual_truth_audit", "public_copy_polish"],
    blockedEscalations: blockedByDefault,
    convergenceStatus: "ready_with_notes",
  },
  {
    layerId: "living_market_core",
    type: "market_layer",
    name: "Trading Workspace / Living Market Core",
    purpose:
      "Keeps the chart-first workstation paper-safe, calm, and separated from public marketing navigation.",
    world: "public_earth_world",
    owner: "Trading Workspace Planet",
    dependencies: ["public_earth_world", "product_truth"],
    outputs: ["Chart-first workspace", "Paper controls", "Market readiness"],
    riskLevel: "high",
    publicVisible: true,
    founderVisible: true,
    validationRequired: ["chart render", "workspace shell", "no live feed claim"],
    memoryRule:
      "Preserve chart comfort lessons and escalate disruptive layout changes to Founder review.",
    nextPossibleLayers: ["chart_comfort_audit", "workspace_density_review"],
    blockedEscalations: blockedByDefault,
    convergenceStatus: "ready_with_notes",
  },
  {
    layerId: "plan_realms",
    type: "public_user_layer",
    name: "Plan Realms",
    purpose:
      "Maps Free, Pro, VIP, and Institutional to functional public realms without fake activation.",
    world: "public_earth_world",
    owner: "Plans Realm Planet",
    dependencies: ["product_truth", "public_earth_world"],
    outputs: ["Free active", "Pro planned", "VIP planned", "Institutional future"],
    riskLevel: "high",
    publicVisible: true,
    founderVisible: true,
    validationRequired: ["entitlement truth", "public plan copy", "no Alkon plan"],
    memoryRule:
      "Remember that Pro/VIP/Institutional may not be presented as active unless real entitlements exist.",
    nextPossibleLayers: ["plan_truth_copy_review", "entitlement_gate_audit"],
    blockedEscalations: blockedByDefault,
    convergenceStatus: "ready_with_notes",
  },
  {
    layerId: "tpm_assistant",
    type: "assistant_layer",
    name: "TPM Assistant",
    purpose:
      "Explains product state, plan boundaries, paper-safe workflow, and blocked states without signals or guarantees.",
    world: "public_earth_world",
    owner: "Assistant Planet",
    dependencies: ["product_truth", "plan_realms", "journal_coach"],
    outputs: ["Plan-aware guidance", "Why Blocked", "Paper-safe help"],
    riskLevel: "high",
    publicVisible: true,
    founderVisible: true,
    validationRequired: ["no financial advice", "no signals", "no private terms"],
    memoryRule:
      "Store safe assistant behavior patterns only; never store secrets or guaranteed outcome wording.",
    nextPossibleLayers: ["assistant_prompt_boundary_audit"],
    blockedEscalations: blockedByDefault,
    convergenceStatus: "ready_with_notes",
  },
  {
    layerId: "planetary_environment",
    type: "environment_layer",
    name: "Planetary Environment",
    purpose:
      "Adds privacy-safe Adaptive Atmosphere by time, solar phase, weather readiness, market session, plan realm, and surface intensity.",
    world: "public_earth_world",
    owner: "Brand Intelligence + Environment Engine",
    dependencies: ["public_earth_world", "living_market_core"],
    outputs: ["Adaptive atmosphere", "Static mode", "Chart-safe intensity"],
    riskLevel: "medium",
    publicVisible: true,
    founderVisible: true,
    validationRequired: ["no GPS", "no external weather calls", "reduced motion"],
    memoryRule:
      "Record atmosphere settings that help focus; reject weather-as-trading-advice patterns.",
    nextPossibleLayers: ["environment_visual_acceptance"],
    blockedEscalations: [...blockedByDefault, "precise location tracking"],
    convergenceStatus: "ready_with_notes",
  },
  {
    layerId: "alkon_private_universe",
    type: "private_founder_layer",
    name: "Alkon Private Universe",
    purpose:
      "Private command universe where Ahmad sees Earth, Moon, Orbit, Solar, Defense, Construction, Memory, World Interface, and next safe actions.",
    world: "private_alkon_world",
    owner: "Alkon Founder Command",
    dependencies: ["product_truth", "public_private_boundary"],
    outputs: ["Private readiness", "Blocked actions", "Founder decisions"],
    riskLevel: "critical",
    publicVisible: false,
    founderVisible: true,
    validationRequired: ["owner-only surface", "no public route", "no secrets"],
    memoryRule:
      "Alkon vocabulary stays private and may only feed public-safe summaries outward.",
    nextPossibleLayers: ["founder_command_visual_review"],
    blockedEscalations: blockedByDefault,
    convergenceStatus: "ready_with_notes",
  },
  {
    layerId: "alkon_cosmic_operating_physics",
    type: "automation_layer",
    name: "Alkon Cosmic Operating Physics",
    purpose:
      "Routes private work through source, energy, gravity, orbit, owner, monitors, station, worker, passport, license, validation, tribunal, memory, and Founder report.",
    world: "private_alkon_world",
    owner: "Construction Universe",
    dependencies: ["alkon_private_universe", "codex_sovereign_construction"],
    outputs: ["Task graph", "Risk belt", "Black hole zone"],
    riskLevel: "critical",
    publicVisible: false,
    founderVisible: true,
    validationRequired: ["no execution", "no direct Codex call", "black-hole gates"],
    memoryRule:
      "Every accepted work body records source, validation, tribunal, and lesson without secrets.",
    nextPossibleLayers: ["layer_growth_engine", "convergence_score"],
    blockedEscalations: blockedByDefault,
    convergenceStatus: "ready_with_notes",
  },
  {
    layerId: "alkon_sovereign_operating_consciousness",
    type: "private_founder_layer",
    name: "Alkon Sovereign Operating Consciousness",
    purpose:
      "Connects Founder decisions, sovereign autonomy, idea intake, and safe next actions without uncontrolled autonomy.",
    world: "private_alkon_world",
    owner: "Sovereign Autonomy",
    dependencies: ["alkon_private_universe", "product_memory"],
    outputs: ["Founder decisions needed", "Blocked requests", "Next safe actions"],
    riskLevel: "critical",
    publicVisible: false,
    founderVisible: true,
    validationRequired: ["Founder approval", "no automatic execution"],
    memoryRule:
      "Store decisions and lessons as private summaries, never as secret-bearing automation instructions.",
    nextPossibleLayers: ["founder_decision_queue_refinement"],
    blockedEscalations: blockedByDefault,
    convergenceStatus: "partial",
  },
  {
    layerId: "codex_sovereign_construction",
    type: "automation_layer",
    name: "Codex Sovereign Construction",
    purpose:
      "Prepares Task Passports and Codex-ready prompts for manual external execution after validation gates.",
    world: "private_alkon_world",
    owner: "Codex Sovereignty",
    dependencies: ["alkon_cosmic_operating_physics", "security_sovereignty"],
    outputs: ["Task Passport", "Codex prompt draft", "Result Tribunal"],
    riskLevel: "critical",
    publicVisible: false,
    founderVisible: true,
    validationRequired: ["task passport", "codex license", "result tribunal"],
    memoryRule:
      "Codex outputs are lessons only after validation; the web app never executes Codex.",
    nextPossibleLayers: ["validation_interpreter_review"],
    blockedEscalations: blockedByDefault,
    convergenceStatus: "ready_with_notes",
  },
  {
    layerId: "product_memory",
    type: "memory_layer",
    name: "Product Memory",
    purpose:
      "Keeps accepted patterns, rejected patterns, product gaps, validation summaries, and local day lessons.",
    world: "private_alkon_world",
    owner: "Memory Universe",
    dependencies: ["product_truth", "result_tribunal"],
    outputs: ["Lessons", "Open gaps", "Validation memory"],
    riskLevel: "high",
    publicVisible: false,
    founderVisible: true,
    validationRequired: ["no secrets", "no private sensitive data", "memory summary"],
    memoryRule:
      "Memory stores summaries and lessons; secrets, private sensitive data, fake metrics, and raw credentials are forbidden.",
    nextPossibleLayers: ["memory_gap_clustering"],
    blockedEscalations: [...blockedByDefault, "secret storage"],
    convergenceStatus: "ready_with_notes",
  },
  {
    layerId: "security_sovereignty",
    type: "security_layer",
    name: "Security Sovereignty",
    purpose:
      "Protects public/private boundaries, auth/security review, incident readiness, and hard forbidden categories.",
    world: "private_alkon_world",
    owner: "Defense Universe",
    dependencies: ["secrets_authority", "guardian_legal_trust"],
    outputs: ["Boundary rules", "Incident readiness", "Security review"],
    riskLevel: "critical",
    publicVisible: false,
    founderVisible: true,
    validationRequired: ["security review", "no auth weakening", "secret scan"],
    memoryRule:
      "Security lessons remain private and only public-safe readiness may be exposed.",
    nextPossibleLayers: ["security_reality_audit"],
    blockedEscalations: [...blockedByDefault, "auth weakening"],
    convergenceStatus: "ready_with_notes",
  },
  {
    layerId: "secrets_authority",
    type: "security_layer",
    name: "Secrets Authority",
    purpose:
      "Confirms production secrets are untouched, hidden, and never sent to Codex or public routes.",
    world: "private_alkon_world",
    owner: "Defense Universe",
    dependencies: ["security_sovereignty"],
    outputs: ["No secrets exposed", "No secret status details public"],
    riskLevel: "critical",
    publicVisible: false,
    founderVisible: true,
    validationRequired: ["secret scan", "API payload review"],
    memoryRule:
      "Never store actual secrets; store only private-safe readiness summaries.",
    nextPossibleLayers: ["secrets_rotation_plan_future"],
    blockedEscalations: [...blockedByDefault, "production secret touch"],
    convergenceStatus: "ready_with_notes",
  },
  {
    layerId: "guardian_legal_trust",
    type: "product_truth_layer",
    name: "Security / Guardian / Legal / Trust",
    purpose:
      "Blocks fake claims, unsafe advice, fake legal/certification status, guaranteed outcomes, and public launch claims.",
    world: "invisible_operating_layer",
    owner: "Guardian Legal Trust Governor",
    dependencies: ["product_truth", "public_earth_world"],
    outputs: ["Claim safety", "No fake status", "Trust rules"],
    riskLevel: "critical",
    publicVisible: false,
    founderVisible: true,
    validationRequired: ["claim review", "legal readiness", "trust governor"],
    memoryRule:
      "Record claim safety decisions as reusable product truth rules.",
    nextPossibleLayers: ["claim_policy_audit"],
    blockedEscalations: blockedByDefault,
    convergenceStatus: "ready_with_notes",
  },
  {
    layerId: "world_interface",
    type: "invisible_operating_layer",
    name: "World Interface",
    purpose:
      "Models support, email, social, partners, media, security channels, and quarantine readiness without sending or publishing.",
    world: "invisible_operating_layer",
    owner: "World Interface Planet",
    dependencies: ["support_readiness", "launch_readiness"],
    outputs: ["Support readiness", "World channel readiness", "Quarantine status"],
    riskLevel: "high",
    publicVisible: false,
    founderVisible: true,
    validationRequired: ["no external calls", "no email sending", "no social publishing"],
    memoryRule:
      "World-interface lessons must keep external actions disabled until real provider gates exist.",
    nextPossibleLayers: ["support_channel_readiness_review"],
    blockedEscalations: [...blockedByDefault, "email sending"],
    convergenceStatus: "partial",
  },
  {
    layerId: "launch_readiness",
    type: "launch_readiness_layer",
    name: "Launch Readiness",
    purpose:
      "Maintains the 250 CHF/month economical launch gate without activating launch, production, billing, broker/feed, live execution, real money, or social publishing.",
    world: "invisible_operating_layer",
    owner: "Launch Gate",
    dependencies: ["legal_readiness", "support_readiness", "security_sovereignty"],
    outputs: ["Budget cap", "Waitlist readiness", "Beta/rollback gate"],
    riskLevel: "critical",
    publicVisible: false,
    founderVisible: true,
    validationRequired: ["launch gate", "Founder final decision", "rollback plan"],
    memoryRule:
      "Launch readiness is readiness only; never record it as launch activation.",
    nextPossibleLayers: ["real_world_beta_readiness_future"],
    blockedEscalations: blockedByDefault,
    convergenceStatus: "partial",
  },
  {
    layerId: "reality_audit",
    type: "invisible_operating_layer",
    name: "Reality Audit",
    purpose:
      "Prepares a full codebase and visual truth audit before any final local-day acceptance claim.",
    world: "private_alkon_world",
    owner: "Result Tribunal",
    dependencies: ["final_convergence", "product_memory"],
    outputs: ["Audit needed", "P0/P1 route", "Evidence requirements"],
    riskLevel: "medium",
    publicVisible: false,
    founderVisible: true,
    validationRequired: ["full validation", "visual proof", "git cleanliness"],
    memoryRule:
      "Record audit findings and validation evidence before local acceptance.",
    nextPossibleLayers: ["safe_cleanup"],
    blockedEscalations: ["unreviewed cleanup execution", ...blockedByDefault],
    convergenceStatus: "partial",
  },
  {
    layerId: "safe_cleanup",
    type: "invisible_operating_layer",
    name: "Safe Cleanup",
    purpose:
      "Plans cleanup after audit only, preserving user work and avoiding destructive operations.",
    world: "private_alkon_world",
    owner: "Construction Universe",
    dependencies: ["reality_audit"],
    outputs: ["Cleanup plan", "Protected files", "No destructive commands"],
    riskLevel: "high",
    publicVisible: false,
    founderVisible: true,
    validationRequired: ["Founder approval", "git diff review", "full validation"],
    memoryRule:
      "Cleanup may only remove clearly broken duplicates after explanation and approval.",
    nextPossibleLayers: ["local_day_one"],
    blockedEscalations: ["git reset", "unapproved deletion", ...blockedByDefault],
    convergenceStatus: "planned",
  },
  {
    layerId: "local_day_one",
    type: "private_founder_layer",
    name: "Local Day One",
    purpose:
      "Starts daily local operation only after convergence, audit, cleanup plan, visual acceptance, validation, and Founder approval.",
    world: "private_alkon_world",
    owner: "Moon Cycle System",
    dependencies: ["final_convergence", "reality_audit", "safe_cleanup"],
    outputs: ["Local day review", "Founder report", "Next day plan"],
    riskLevel: "medium",
    publicVisible: false,
    founderVisible: true,
    validationRequired: ["Founder start decision", "daily loop", "memory update"],
    memoryRule:
      "Every local day produces validation, tribunal, memory, and next-safe-layer summary.",
    nextPossibleLayers: ["day_two_layer_growth"],
    blockedEscalations: blockedByDefault,
    convergenceStatus: "planned",
  },
] satisfies FinalConvergenceLayer[];

export function getFinalConvergenceLayers(): FinalConvergenceLayer[] {
  return FINAL_CONVERGENCE_LAYERS;
}

export function getFinalConvergenceLayer(layerId: string) {
  return FINAL_CONVERGENCE_LAYERS.find((layer) => layer.layerId === layerId);
}
