import "server-only";

import type {
  AccountProvisioningItem,
  AccountProvisioningPriority,
  AccountProvisioningSnapshot,
} from "./types";

const accountProvisioningItems: AccountProvisioningItem[] = [
  {
    id: "github-repository",
    label: "GitHub repository",
    priority: "p0",
    status: "ready",
    purpose: "Versioned local platform construction and review.",
    createsAccountAutomatically: false,
    connectsExternally: false,
    safeNextAction: "Keep manual Git commit and push review.",
  },
  {
    id: "local-runtime",
    label: "Local runtime",
    priority: "p0",
    status: "ready",
    purpose: "Build, start, validate, and smoke-test locally.",
    createsAccountAutomatically: false,
    connectsExternally: false,
    safeNextAction: "Use terminal commands only.",
  },
  {
    id: "founder-local-command",
    label: "Founder local command readiness",
    priority: "p0",
    status: "ready",
    purpose: "Owner-only readiness view and safe next actions.",
    createsAccountAutomatically: false,
    connectsExternally: false,
    safeNextAction: "Keep private and read-only.",
  },
  {
    id: "support-email",
    label: "Support email readiness",
    priority: "p1",
    status: "planned",
    purpose: "Future support contact routing.",
    createsAccountAutomatically: false,
    connectsExternally: false,
    safeNextAction: "Plan address and policy without connecting a mailbox.",
  },
  {
    id: "hello-email",
    label: "Hello email readiness",
    priority: "p1",
    status: "planned",
    purpose: "Future public contact identity.",
    createsAccountAutomatically: false,
    connectsExternally: false,
    safeNextAction: "Reserve naming requirements only.",
  },
  {
    id: "security-contact",
    label: "Security contact readiness",
    priority: "p1",
    status: "planned",
    purpose: "Future vulnerability/security contact path.",
    createsAccountAutomatically: false,
    connectsExternally: false,
    safeNextAction: "Define review policy before any address is connected.",
  },
  {
    id: "waitlist-provider",
    label: "Waitlist or email service",
    priority: "p2",
    status: "planned",
    purpose: "Future interest capture after consent and launch policy.",
    createsAccountAutomatically: false,
    connectsExternally: false,
    safeNextAction: "Keep public waitlist inactive until pre-launch review.",
  },
  {
    id: "staging-host",
    label: "Staging host",
    priority: "p2",
    status: "planned",
    purpose: "Future pre-launch deployment rehearsal.",
    createsAccountAutomatically: false,
    connectsExternally: false,
    safeNextAction: "Document requirements before provider setup.",
  },
  {
    id: "database-provider",
    label: "Database provider",
    priority: "p2",
    status: "planned",
    purpose: "Future durable production-grade storage.",
    createsAccountAutomatically: false,
    connectsExternally: false,
    safeNextAction: "Do not provision production storage in local operation.",
  },
  {
    id: "monitoring-provider",
    label: "Monitoring",
    priority: "p2",
    status: "planned",
    purpose: "Future alerting and incident review.",
    createsAccountAutomatically: false,
    connectsExternally: false,
    safeNextAction: "Define privacy-safe alerting first.",
  },
  {
    id: "payment-provider",
    label: "Payment provider readiness",
    priority: "p2",
    status: "blocked",
    purpose: "Future billing after legal, support, and entitlement review.",
    createsAccountAutomatically: false,
    connectsExternally: false,
    safeNextAction: "Do not create checkout or billing activation now.",
  },
  {
    id: "social-channels",
    label: "Social channels",
    priority: "p3",
    status: "future",
    purpose: "Future public communications after review.",
    createsAccountAutomatically: false,
    connectsExternally: false,
    safeNextAction: "Keep accounts disconnected and publishing inactive.",
  },
  {
    id: "newsletter",
    label: "Newsletter",
    priority: "p3",
    status: "future",
    purpose: "Future opt-in content distribution.",
    createsAccountAutomatically: false,
    connectsExternally: false,
    safeNextAction: "Keep future-only until consent, privacy, and provider review exist.",
  },
  {
    id: "media-workflow",
    label: "Media workflow",
    priority: "p3",
    status: "future",
    purpose: "Future campaign planning and publishing workflow.",
    createsAccountAutomatically: false,
    connectsExternally: false,
    safeNextAction: "Keep drafts internal and review-only.",
  },
  {
    id: "partnerships-dashboard",
    label: "Partnerships dashboard",
    priority: "p3",
    status: "future",
    purpose: "Future partner opportunity review.",
    createsAccountAutomatically: false,
    connectsExternally: false,
    safeNextAction: "Do not claim partnerships without contracts.",
  },
  {
    id: "live-broker",
    label: "Live broker",
    priority: "blocked",
    status: "blocked",
    purpose: "Future regulated broker work only.",
    createsAccountAutomatically: false,
    connectsExternally: false,
    safeNextAction: "Keep broker and live execution blocked.",
  },
  {
    id: "real-money-routing",
    label: "Real-money routing",
    priority: "blocked",
    status: "blocked",
    purpose: "Future regulated money movement only.",
    createsAccountAutomatically: false,
    connectsExternally: false,
    safeNextAction: "Keep local operation paper-safe.",
  },
  {
    id: "billing-activation",
    label: "Billing activation",
    priority: "blocked",
    status: "blocked",
    purpose: "Future paid plans only after gates.",
    createsAccountAutomatically: false,
    connectsExternally: false,
    safeNextAction: "Keep billing inactive.",
  },
  {
    id: "public-launch-automation",
    label: "Public launch automation",
    priority: "blocked",
    status: "blocked",
    purpose: "Not allowed in local operation.",
    createsAccountAutomatically: false,
    connectsExternally: false,
    safeNextAction: "Do not automate public launch.",
  },
  {
    id: "social-publishing-automation",
    label: "Social publishing automation",
    priority: "blocked",
    status: "blocked",
    purpose: "Not allowed in local operation.",
    createsAccountAutomatically: false,
    connectsExternally: false,
    safeNextAction: "Keep social publishing inactive.",
  },
];

function summarize(items: AccountProvisioningItem[]) {
  const keys: AccountProvisioningPriority[] = ["p0", "p1", "p2", "p3", "blocked"];

  return keys.reduce((summary, key) => {
    summary[key] = items.filter((item) => item.priority === key).length;
    return summary;
  }, {} as Record<AccountProvisioningPriority, number>);
}

export function getAccountProvisioningSnapshot(
  checkedAt = new Date().toISOString()
): AccountProvisioningSnapshot {
  return {
    checkedAt,
    mode: "essential_account_provisioning_planner",
    status: "ready",
    items: accountProvisioningItems,
    summary: summarize(accountProvisioningItems),
    noAccountCreationAutomation: true,
    noExternalConnection: true,
    noSecretsStored: true,
  };
}
