import "server-only";

import type {
  EssentialIntegrationTool,
  IntegrationPriority,
  IntegrationPrioritySummary,
} from "./types";

function tool(input: EssentialIntegrationTool): EssentialIntegrationTool {
  return input;
}

export const essentialIntegrationRegistry: EssentialIntegrationTool[] = [
  tool({
    id: "local-runtime",
    name: "Local runtime",
    category: "local_runtime",
    priority: "p0_local_required",
    currentStatus: "active_local",
    neededFor: ["local development", "build verification", "route smoke checks"],
    ownerSurface: "local_runtime",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: false,
    requiresPayment: false,
    requiresLegalReview: false,
    requiresGuardianReview: false,
    requiresFounderApproval: false,
    blockedReason: null,
    safeNextAction: "Use documented local commands from the terminal only.",
  }),
  tool({
    id: "git-github-readiness",
    name: "Git and GitHub readiness",
    category: "github",
    priority: "p0_local_required",
    currentStatus: "ready",
    neededFor: ["version control", "commit history", "manual review"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: false,
    requiresPayment: false,
    requiresLegalReview: false,
    requiresGuardianReview: false,
    requiresFounderApproval: false,
    blockedReason: null,
    safeNextAction: "Keep commits reviewed and pushed manually after validation.",
  }),
  tool({
    id: "codex-task-workflow",
    name: "Codex task workflow",
    category: "codex",
    priority: "p0_local_required",
    currentStatus: "ready",
    neededFor: ["build planning", "task drafting", "validation summaries"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: false,
    requiresPayment: false,
    requiresLegalReview: false,
    requiresGuardianReview: true,
    requiresFounderApproval: true,
    blockedReason: null,
    safeNextAction: "Draft prompts locally and wait for Ahmad approval before separate Codex execution.",
  }),
  tool({
    id: "diagnostics-readiness",
    name: "Diagnostics",
    category: "diagnostics",
    priority: "p0_local_required",
    currentStatus: "ready",
    neededFor: ["readiness visibility", "blocked-state review", "public-safe health"],
    ownerSurface: "diagnostics",
    publicVisible: true,
    founderVisible: true,
    requiresSecret: false,
    requiresPayment: false,
    requiresLegalReview: false,
    requiresGuardianReview: false,
    requiresFounderApproval: false,
    blockedReason: null,
    safeNextAction: "Show compact user-safe readiness without private command details.",
  }),
  tool({
    id: "product-memory",
    name: "Product memory",
    category: "product_memory",
    priority: "p0_local_required",
    currentStatus: "ready",
    neededFor: ["local day reports", "safe product gaps", "validation summaries"],
    ownerSurface: "invisible_operating_layer",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: false,
    requiresPayment: false,
    requiresLegalReview: false,
    requiresGuardianReview: true,
    requiresFounderApproval: false,
    blockedReason: null,
    safeNextAction: "Store safe summaries only; never store secrets or private sensitive data.",
  }),
  tool({
    id: "validation-command-set",
    name: "Validation command set",
    category: "local_runtime",
    priority: "p0_local_required",
    currentStatus: "ready",
    neededFor: ["typecheck", "lint", "build", "regression", "smoke routes"],
    ownerSurface: "local_runtime",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: false,
    requiresPayment: false,
    requiresLegalReview: false,
    requiresGuardianReview: false,
    requiresFounderApproval: false,
    blockedReason: null,
    safeNextAction: "Run validation from the terminal, not from the web app.",
  }),
  tool({
    id: "founder-command-readiness",
    name: "Founder Command readiness",
    category: "founder_command",
    priority: "p0_local_required",
    currentStatus: "ready",
    neededFor: ["owner overview", "safe next actions", "blocked action reminders"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: false,
    requiresPayment: false,
    requiresLegalReview: false,
    requiresGuardianReview: true,
    requiresFounderApproval: false,
    blockedReason: null,
    safeNextAction: "Keep read-only and private; do not expose as a user plan.",
  }),
  tool({
    id: "email-readiness",
    name: "Email readiness",
    category: "email",
    priority: "p1_soon",
    currentStatus: "planned",
    neededFor: ["hello email", "support email", "security contact"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: true,
    requiresPayment: false,
    requiresLegalReview: true,
    requiresGuardianReview: true,
    requiresFounderApproval: true,
    blockedReason: "No email provider or mailbox is connected in this pass.",
    safeNextAction: "Plan addresses and review policies without sending email.",
  }),
  tool({
    id: "support-readiness",
    name: "Support readiness",
    category: "support",
    priority: "p1_soon",
    currentStatus: "planned",
    neededFor: ["help center", "problem reports", "public-safe support"],
    ownerSurface: "diagnostics",
    publicVisible: true,
    founderVisible: true,
    requiresSecret: false,
    requiresPayment: false,
    requiresLegalReview: true,
    requiresGuardianReview: true,
    requiresFounderApproval: true,
    blockedReason: "No ticket backend or sending system is active.",
    safeNextAction: "Keep support options as readiness labels until a guarded backend exists.",
  }),
  tool({
    id: "secrets-readiness",
    name: "Secrets readiness",
    category: "secrets",
    priority: "p1_soon",
    currentStatus: "ready",
    neededFor: ["presence-only secret status", "rotation planning", "no exposure policy"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: false,
    requiresPayment: false,
    requiresLegalReview: false,
    requiresGuardianReview: true,
    requiresFounderApproval: true,
    blockedReason: null,
    safeNextAction: "Show readiness and rotation status only; never reveal raw values.",
  }),
  tool({
    id: "security-readiness",
    name: "Security readiness",
    category: "secrets",
    priority: "p1_soon",
    currentStatus: "ready",
    neededFor: ["zero-trust rules", "incident readiness", "hardening"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: false,
    requiresPayment: false,
    requiresLegalReview: true,
    requiresGuardianReview: true,
    requiresFounderApproval: false,
    blockedReason: null,
    safeNextAction: "Keep security readiness defensive and local-owned only.",
  }),
  tool({
    id: "apps-platforms-readiness",
    name: "Apps and platforms readiness",
    category: "apps_platforms",
    priority: "p1_soon",
    currentStatus: "planned",
    neededFor: ["Web App", "Desktop planned", "Mobile planned"],
    ownerSurface: "diagnostics",
    publicVisible: true,
    founderVisible: true,
    requiresSecret: false,
    requiresPayment: false,
    requiresLegalReview: false,
    requiresGuardianReview: false,
    requiresFounderApproval: false,
    blockedReason: "Desktop and mobile apps remain planned.",
    safeNextAction: "Keep Web App current and label Desktop/Mobile as planned.",
  }),
  tool({
    id: "staging-hosting",
    name: "Staging hosting",
    category: "hosting_future",
    priority: "p2_pre_launch",
    currentStatus: "planned",
    neededFor: ["pre-launch review", "deployment rehearsal"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: true,
    requiresPayment: true,
    requiresLegalReview: false,
    requiresGuardianReview: true,
    requiresFounderApproval: true,
    blockedReason: "No staging host is connected now.",
    safeNextAction: "Define staging requirements before any deployment setup.",
  }),
  tool({
    id: "managed-database",
    name: "Managed database",
    category: "database_future",
    priority: "p2_pre_launch",
    currentStatus: "planned",
    neededFor: ["durable account data", "production readiness later"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: true,
    requiresPayment: true,
    requiresLegalReview: true,
    requiresGuardianReview: true,
    requiresFounderApproval: true,
    blockedReason: "Production database provisioning is not part of local operation.",
    safeNextAction: "Keep local storage/readiness until a guarded staging plan exists.",
  }),
  tool({
    id: "email-provider",
    name: "Email provider",
    category: "email",
    priority: "p2_pre_launch",
    currentStatus: "planned",
    neededFor: ["waitlist", "transactional email later", "support routing"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: true,
    requiresPayment: true,
    requiresLegalReview: true,
    requiresGuardianReview: true,
    requiresFounderApproval: true,
    blockedReason: "No provider key or sending domain is configured.",
    safeNextAction: "Plan provider requirements without creating keys.",
  }),
  tool({
    id: "monitoring",
    name: "Monitoring",
    category: "monitoring_future",
    priority: "p2_pre_launch",
    currentStatus: "planned",
    neededFor: ["health alerts", "error review", "incident response"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: true,
    requiresPayment: false,
    requiresLegalReview: false,
    requiresGuardianReview: true,
    requiresFounderApproval: true,
    blockedReason: "No monitoring account or token is connected.",
    safeNextAction: "Define alert policy and privacy limits first.",
  }),
  tool({
    id: "payment-provider-readiness",
    name: "Payment provider readiness",
    category: "billing_future",
    priority: "p2_pre_launch",
    currentStatus: "blocked",
    neededFor: ["future billing review", "future entitlement activation"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: true,
    requiresPayment: true,
    requiresLegalReview: true,
    requiresGuardianReview: true,
    requiresFounderApproval: true,
    blockedReason: "Billing activation is blocked now.",
    safeNextAction: "Keep payment provider as readiness only; no checkout or paid access.",
  }),
  tool({
    id: "public-waitlist",
    name: "Public waitlist",
    category: "support",
    priority: "p2_pre_launch",
    currentStatus: "planned",
    neededFor: ["future interest capture"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: true,
    requiresPayment: false,
    requiresLegalReview: true,
    requiresGuardianReview: true,
    requiresFounderApproval: true,
    blockedReason: "No public launch or waitlist capture is active.",
    safeNextAction: "Draft policy and consent requirements before implementation.",
  }),
  tool({
    id: "social-publishing",
    name: "Social publishing",
    category: "social",
    priority: "p3_post_launch",
    currentStatus: "future",
    neededFor: ["future content distribution"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: true,
    requiresPayment: false,
    requiresLegalReview: true,
    requiresGuardianReview: true,
    requiresFounderApproval: true,
    blockedReason: "Social publishing and tokens are inactive.",
    safeNextAction: "Keep social accounts disconnected and content draft-only.",
  }),
  tool({
    id: "advanced-crm",
    name: "Advanced CRM",
    category: "support",
    priority: "p3_post_launch",
    currentStatus: "future",
    neededFor: ["future support operations", "future segmentation"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: true,
    requiresPayment: true,
    requiresLegalReview: true,
    requiresGuardianReview: true,
    requiresFounderApproval: true,
    blockedReason: "No customer system is needed for local operation.",
    safeNextAction: "Keep CRM future-only until real support policy exists.",
  }),
  tool({
    id: "partnerships-dashboard",
    name: "Partnerships dashboard",
    category: "media_future",
    priority: "p3_post_launch",
    currentStatus: "future",
    neededFor: ["future partner review", "brand safety"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: false,
    requiresPayment: false,
    requiresLegalReview: true,
    requiresGuardianReview: true,
    requiresFounderApproval: true,
    blockedReason: "No partnership claims or dashboard are active.",
    safeNextAction: "Keep partnership items draft/review-only.",
  }),
  tool({
    id: "ads",
    name: "Ads",
    category: "media_future",
    priority: "p3_post_launch",
    currentStatus: "future",
    neededFor: ["future campaign testing"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: true,
    requiresPayment: true,
    requiresLegalReview: true,
    requiresGuardianReview: true,
    requiresFounderApproval: true,
    blockedReason: "No ad accounts, spend, pixels, or campaigns are active.",
    safeNextAction: "Do not connect ad platforms during local operation.",
  }),
  tool({
    id: "affiliate-referral",
    name: "Affiliate and referral",
    category: "media_future",
    priority: "p3_post_launch",
    currentStatus: "future",
    neededFor: ["future growth loops"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: true,
    requiresPayment: true,
    requiresLegalReview: true,
    requiresGuardianReview: true,
    requiresFounderApproval: true,
    blockedReason: "No referral tracking, payouts, or affiliate claims are active.",
    safeNextAction: "Keep referral systems future-only.",
  }),
  tool({
    id: "billing-activation",
    name: "Billing activation",
    category: "billing_future",
    priority: "blocked_now",
    currentStatus: "forbidden_now",
    neededFor: ["future paid plans only"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: true,
    requiresPayment: true,
    requiresLegalReview: true,
    requiresGuardianReview: true,
    requiresFounderApproval: true,
    blockedReason: "Billing activation is forbidden during local operation.",
    safeNextAction: "Keep Pro/VIP/Institutional planned or entitlement-based only.",
  }),
  tool({
    id: "broker-live",
    name: "Broker and live execution",
    category: "broker_future",
    priority: "blocked_now",
    currentStatus: "forbidden_now",
    neededFor: ["future regulated trading integration only"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: true,
    requiresPayment: false,
    requiresLegalReview: true,
    requiresGuardianReview: true,
    requiresFounderApproval: true,
    blockedReason: "Broker/feed activation and live execution are blocked now.",
    safeNextAction: "Keep execution paper-only.",
  }),
  tool({
    id: "real-money-routing",
    name: "Real-money routing",
    category: "broker_future",
    priority: "blocked_now",
    currentStatus: "forbidden_now",
    neededFor: ["future regulated money movement only"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: true,
    requiresPayment: true,
    requiresLegalReview: true,
    requiresGuardianReview: true,
    requiresFounderApproval: true,
    blockedReason: "Real-money routing is forbidden now.",
    safeNextAction: "Use paper mode only.",
  }),
  tool({
    id: "production-secrets",
    name: "Production secrets",
    category: "secrets",
    priority: "blocked_now",
    currentStatus: "forbidden_now",
    neededFor: ["future production only"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: true,
    requiresPayment: false,
    requiresLegalReview: true,
    requiresGuardianReview: true,
    requiresFounderApproval: true,
    blockedReason: "Production secrets must not be touched or stored.",
    safeNextAction: "Report presence/readiness only; never reveal values.",
  }),
  tool({
    id: "automatic-social-publishing",
    name: "Automatic social publishing",
    category: "social",
    priority: "blocked_now",
    currentStatus: "forbidden_now",
    neededFor: ["future media automation only"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: true,
    requiresPayment: false,
    requiresLegalReview: true,
    requiresGuardianReview: true,
    requiresFounderApproval: true,
    blockedReason: "Automatic social publishing is forbidden now.",
    safeNextAction: "Keep posts as drafts with review only.",
  }),
  tool({
    id: "external-autopilot",
    name: "External autopilot",
    category: "codex",
    priority: "blocked_now",
    currentStatus: "forbidden_now",
    neededFor: ["none during local operation"],
    ownerSurface: "founder_command",
    publicVisible: false,
    founderVisible: true,
    requiresSecret: true,
    requiresPayment: false,
    requiresLegalReview: true,
    requiresGuardianReview: true,
    requiresFounderApproval: true,
    blockedReason: "Uncontrolled external execution is forbidden now.",
    safeNextAction: "Keep all external execution manual and explicitly approved.",
  }),
];

const priorityLabels: Record<IntegrationPriority, string> = {
  p0_local_required: "P0 local required",
  p1_soon: "P1 soon",
  p2_pre_launch: "P2 pre-launch",
  p3_post_launch: "P3 post-launch",
  blocked_now: "Blocked now",
};

export function summarizeIntegrationPriorities(
  registry = essentialIntegrationRegistry
): IntegrationPrioritySummary {
  return (Object.keys(priorityLabels) as IntegrationPriority[]).reduce(
    (summary, priority) => {
      const tools = registry.filter((item) => item.priority === priority);
      summary[priority] = {
        label: priorityLabels[priority],
        count: tools.length,
        tools: tools.map((item) => item.name),
      };
      return summary;
    },
    {} as IntegrationPrioritySummary
  );
}
