import "server-only";

import type { AlKawnDesktopTask } from "./types";

export function getAlKawnDesktopTaskCenter(): AlKawnDesktopTask[] {
  return [
    {
      id: "internal_safe_tasks",
      title: "Organize internal safe tasks",
      layer: "Human Interface",
      priority: "P0",
      status: "active",
      category: "internal safe tasks",
      nextStep: "Group safe audits, reports, and validation plans into command cards.",
      whoDecides: "الكون",
      reason: "Private internal organization does not touch law, money, broker, or public exposure.",
    },
    {
      id: "architecture_tasks",
      title: "Keep canonical architecture clean",
      layer: "Universe Operating Kernel",
      priority: "P0",
      status: "checked",
      category: "architecture tasks",
      nextStep: "Use registry and cleanup reports as source truth.",
      whoDecides: "الكون",
      reason: "Architecture cleanup remains internal and Product Truth guarded.",
    },
    {
      id: "kernel_tasks",
      title: "Kernel guard review",
      layer: "Universe Operating Kernel",
      priority: "P1",
      status: "protected",
      category: "kernel tasks",
      nextStep: "Review guards before any future Operator or Infinity preparation.",
      whoDecides: "الكون",
      reason: "Kernel review is internal; activation remains gated.",
    },
    {
      id: "product_truth_tasks",
      title: "Product Truth visibility check",
      layer: "Product Truth",
      priority: "P0",
      status: "active",
      category: "Product Truth tasks",
      nextStep: "Keep truth chips visible on /desktop/kawn, /founder/universe, and /trading.",
      whoDecides: "الكون",
      reason: "Product Truth overrides every action.",
    },
    {
      id: "visual_review_tasks",
      title: "Visual desktop review",
      layer: "Al-Kawn Desktop",
      priority: "P2",
      status: "pending",
      category: "visual review tasks",
      nextStep: "Ahmad reviews whether the desktop feels like the private home of الكون.",
      whoDecides: "Ahmad",
      reason: "Final visual acceptance is a founder decision.",
    },
    {
      id: "report_review_tasks",
      title: "Report review queue",
      layer: "Report Center",
      priority: "P2",
      status: "active",
      category: "report review tasks",
      nextStep: "Surface latest closure reports and missing report status.",
      whoDecides: "الكون",
      reason: "Report surfacing is private and evidence-based.",
    },
    {
      id: "trading_review_tasks",
      title: "Trading review",
      layer: "Earth Planet / /trading",
      priority: "P1",
      status: "protected",
      category: "trading review tasks",
      nextStep: "Keep /trading demo-safe/read-only and chart-first.",
      whoDecides: "الكون",
      reason: "No real-money or broker execution is activated.",
    },
    {
      id: "legal_tasks",
      title: "Legal review queue",
      layer: "Swiss Local Constitution / Global Layer",
      priority: "P0",
      status: "pending",
      category: "legal tasks stopped for Ahmad",
      nextStep: "Stop for Ahmad before any official/legal/regulatory action.",
      whoDecides: "Ahmad",
      reason: "Legal decisions never execute alone.",
    },
    {
      id: "money_payment_tasks",
      title: "Money/payment queue",
      layer: "Founder Boundary",
      priority: "P0",
      status: "blocked",
      category: "money/payment tasks stopped for Ahmad",
      nextStep: "Keep billing, payments, and receiving funds inactive.",
      whoDecides: "Ahmad",
      reason: "Money decisions require Ahmad.",
    },
    {
      id: "broker_tasks",
      title: "Broker queue",
      layer: "Earth Planet / Trading Project",
      priority: "P0",
      status: "blocked",
      category: "broker tasks stopped for Ahmad",
      nextStep: "Keep broker execution disabled/not connected.",
      whoDecides: "Ahmad",
      reason: "Broker and real trading actions require Ahmad.",
    },
    {
      id: "public_launch_tasks",
      title: "Public launch queue",
      layer: "Public Pro Max Future",
      priority: "P0",
      status: "blocked",
      category: "public launch tasks blocked",
      nextStep: "Keep public launch blocked until all gates close.",
      whoDecides: "Ahmad",
      reason: "Public launch requires founder and legal readiness.",
    },
    {
      id: "desktop_mobile_tasks",
      title: "Desktop/mobile private clients",
      layer: "Al-Kawn clients",
      priority: "P2",
      status: "future_gate",
      category: "app/Desktop/mobile tasks",
      nextStep: "Use /desktop/kawn now; native packaging and mobile clients remain future gates.",
      whoDecides: "Ahmad",
      reason: "Distribution and device packaging require founder approval and security review.",
    },
  ];
}
