import "server-only";

import type {
  PlanetAuthority,
  PlanetAutomationLevel,
  PlanetCitizenClassModel,
  PlanetCity,
  PlanetEarthMinistry,
  PlanetGovernor,
  PlanetHierarchyNode,
  PlanetProfession,
  PlanetReadinessState,
  PlanetRiskLevel,
} from "./types";

type ContinentSeed = {
  id: string;
  name: string;
  purpose: string;
  governor: string;
  states: string[];
  ministries: string[];
  cities: string[];
  readiness: PlanetReadinessState;
  riskLevel: PlanetRiskLevel;
  automationLevel: PlanetAutomationLevel;
  publicRelevance: string;
  founderSignals: string[];
  mustNotFake: string[];
};

export const PLANET_EARTH_HIERARCHY_CHAIN = [
  "Founder King",
  "Founder King Command Room",
  "Planet Constitution",
  "Constitutional Council",
  "Legislative Council",
  "Executive Council",
  "Founder Presidency / Central Coordination System",
  "Continents",
  "States",
  "Governors",
  "State Governments",
  "Ministries",
  "Authorities / Agencies",
  "Cities / Districts / Product Modules",
  "Workers / Agents / Professionals",
  "Citizens / Users",
  "Resources / Economy / Daily Activity",
] as const;

export const PLANET_EARTH_CONTINENTS: ContinentSeed[] = [
  {
    id: "sovereignty-command",
    name: "Sovereignty & Command Continent",
    purpose: "Owner authority, command privacy, constitution, councils, and central coordination.",
    governor: "Founder Command Governor",
    states: [
      "Founder Command State",
      "Presidency Coordination State",
      "Constitution State",
      "Legislative State",
      "Executive State",
    ],
    ministries: [
      "Supreme Command Ministry",
      "Founder Presidency & Coordination Ministry",
      "Constitutional Ministry",
      "Legislative Ministry",
      "Executive Implementation Ministry",
    ],
    cities: ["Founder Approval Center", "Founder Command Center", "Council Chamber"],
    readiness: "foundation_ready",
    riskLevel: "critical",
    automationLevel: "founder_approval",
    publicRelevance: "None; owner-only and internal.",
    founderSignals: ["approval queue", "constitutional blocks", "coordination decisions"],
    mustNotFake: ["public command access", "owner device authentication", "approval execution"],
  },
  {
    id: "trading-markets",
    name: "Trading & Markets Continent",
    purpose: "Chart-first market context, paper execution rehearsal, feed truth, and risk state.",
    governor: "Markets Governor",
    states: [
      "Market State",
      "Execution State",
      "Risk State",
      "Feed/Data State",
      "Decision History State",
    ],
    ministries: [
      "Markets & Trading Ministry",
      "Execution & Ticket Ministry",
      "Risk & Session Ministry",
      "Market Data & Feed Ministry",
      "Records & Portfolio Ministry",
    ],
    cities: ["Chart City", "Execution Hall", "Watchlist City", "Market Context District"],
    readiness: "active",
    riskLevel: "high",
    automationLevel: "review",
    publicRelevance: "Core public workstation experience.",
    founderSignals: ["fallback feed state", "paper ticket readiness", "live block status"],
    mustNotFake: ["live execution", "broker/feed activation", "real-money routing"],
  },
  {
    id: "intelligence-brain",
    name: "Intelligence & Brain Continent",
    purpose: "Bounded AI/IQ context, Companion, coaching, strategy review, and safe guidance.",
    governor: "Brain Governor",
    states: [
      "Brain State",
      "Companion State",
      "Coach State",
      "Strategy Review State",
      "Context Quality State",
    ],
    ministries: [
      "AI / IQ / Brain Ministry",
      "Personal Companion Ministry",
      "Coaching & Guidance Ministry",
      "Journal & Learning Ministry",
      "Strategic Research & Analysis Ministry",
    ],
    cities: ["Brain Center", "Companion Center", "Coach Center", "Journal Office"],
    readiness: "foundation_ready",
    riskLevel: "medium",
    automationLevel: "review",
    publicRelevance: "Plan-aware assistant and learning support.",
    founderSignals: ["context quality", "assistant boundaries", "plan-based intelligence gaps"],
    mustNotFake: ["AI certainty", "guaranteed signals", "VIP Brain active without entitlement"],
  },
  {
    id: "protection-defense",
    name: "Protection & Defense Continent",
    purpose: "Guardian, cybersecurity, abuse defense, fraud prevention, and emergency security.",
    governor: "Guardian Governor",
    states: [
      "Guardian State",
      "Cybersecurity State",
      "Abuse Defense State",
      "Fraud Prevention State",
      "Emergency Security State",
    ],
    ministries: [
      "Guardian & Defense Ministry",
      "Cybersecurity & Privacy Ministry",
      "Anti-Fraud & Anti-Manipulation Ministry",
      "Emergency & Incident Ministry",
    ],
    cities: ["Guardian Tower", "Emergency Response Desk", "Safety Boundaries Office"],
    readiness: "foundation_ready",
    riskLevel: "high",
    automationLevel: "review",
    publicRelevance: "Visible only through safe state and auth/security truth.",
    founderSignals: ["blocked unsafe actions", "security incidents", "abuse readiness"],
    mustNotFake: ["real enforcement automation", "invasive surveillance", "silent overrides"],
  },
  {
    id: "law-rights",
    name: "Law & Rights Continent",
    purpose: "Legal Counsel, claims review, Islamic review, brand/IP, and operational law.",
    governor: "Legal Governor",
    states: [
      "Legal Counsel State",
      "Claims Review State",
      "Islamic Review State",
      "Brand/IP State",
      "Contracts/Partnerships State",
    ],
    ministries: [
      "Justice / Legal / Compliance Ministry",
      "Operational Law & Constitution Ministry",
      "Special Accounts & Islamic Review Ministry",
      "Brand, Rights & IP Ministry",
      "Partnerships & Sponsorships Ministry",
    ],
    cities: ["Legal Court", "Rights & Brand Office", "Islamic Review Desk"],
    readiness: "foundation_ready",
    riskLevel: "high",
    automationLevel: "founder_approval",
    publicRelevance: "Public wording and account-type truth only.",
    founderSignals: ["legal warnings", "claims requiring review", "certification blockers"],
    mustNotFake: ["legal compliance certification", "Sharia certification", "registered IP status"],
  },
  {
    id: "citizens-community",
    name: "Citizens & Community Continent",
    purpose: "Citizen affairs, onboarding, support, community culture, and VIP room readiness.",
    governor: "Citizen Affairs Governor",
    states: [
      "Citizen Affairs State",
      "Community State",
      "Support State",
      "Culture State",
      "VIP Rooms State",
    ],
    ministries: [
      "Interior & Citizen Affairs Ministry",
      "Onboarding & Immigration Ministry",
      "Citizen Support Ministry",
      "Community & Culture Ministry",
    ],
    cities: ["Community Square", "Feedback Court", "VIP Private Rooms"],
    readiness: "foundation_ready",
    riskLevel: "medium",
    automationLevel: "review",
    publicRelevance: "Feedback, account, future community, and support readiness.",
    founderSignals: ["feedback flow", "support blockers", "community moderation readiness"],
    mustNotFake: ["active community scale", "VIP rooms active", "real users or citizen metrics"],
  },
  {
    id: "academy-development",
    name: "Academy & Development Continent",
    purpose: "Academy, paper training, learning paths, and personal development.",
    governor: "Academy Governor",
    states: [
      "Academy State",
      "Paper Training State",
      "Learning Paths State",
      "Personal Development State",
    ],
    ministries: ["Academy & Education Ministry", "Coaching & Guidance Ministry"],
    cities: ["Academy Library", "Paper Training District", "Learning Paths Hall"],
    readiness: "foundation_ready",
    riskLevel: "low",
    automationLevel: "auto",
    publicRelevance: "Education and safe learning prompts.",
    founderSignals: ["lesson readiness", "journal/coach safety", "learning gap reports"],
    mustNotFake: ["financial advice", "performance promises", "gambling-style prompts"],
  },
  {
    id: "economy-treasury",
    name: "Economy & Treasury Continent",
    purpose: "Plans, entitlements, treasury controls, partnerships, conversion, and monetization truth.",
    governor: "Treasury Governor",
    states: [
      "Treasury State",
      "Plans State",
      "Entitlements State",
      "Partnerships State",
      "Growth/Conversion State",
    ],
    ministries: [
      "Treasury & Economy Ministry",
      "Plans & Subscriptions Ministry",
      "Partnerships & Sponsorships Ministry",
      "Growth & Conversion Ministry",
    ],
    cities: ["Treasury Hall", "Plans Center", "Partnerships Desk"],
    readiness: "planned",
    riskLevel: "high",
    automationLevel: "founder_approval",
    publicRelevance: "Plan identity only; no checkout or billing.",
    founderSignals: ["billing inactive", "entitlement gaps", "partnership review requests"],
    mustNotFake: ["billing activation", "paid access", "performance-fee public availability"],
  },
  {
    id: "media-growth",
    name: "Media & Growth Continent",
    purpose: "Media planning, content factory, AI Video Studio, campaigns, and social registry.",
    governor: "Media Governor",
    states: [
      "Media State",
      "Content Factory State",
      "AI Video Studio State",
      "Campaigns State",
      "Social Registry State",
    ],
    ministries: [
      "Media & Communications Ministry",
      "AI Video Studio & Production Ministry",
      "Growth & Conversion Ministry",
    ],
    cities: ["Media Studio", "AI Video Studio", "Content Calendar"],
    readiness: "foundation_ready",
    riskLevel: "high",
    automationLevel: "founder_approval",
    publicRelevance: "None until content is reviewed and approved.",
    founderSignals: ["draft queue", "claim risk", "publishing blockers"],
    mustNotFake: ["connected accounts", "external publishing", "followers or reach"],
  },
  {
    id: "engineering-infrastructure",
    name: "Engineering & Infrastructure Continent",
    purpose: "Platform, frontend, backend, quality, integrations, and infrastructure discipline.",
    governor: "Engineering Governor",
    states: [
      "Platform Engineering State",
      "Frontend State",
      "Backend State",
      "Quality State",
      "Integrations State",
    ],
    ministries: [
      "Engineering & Infrastructure Ministry",
      "Product Quality & Testing Ministry",
      "External Integrations Ministry",
      "Automation & Self-Managed Systems Ministry",
    ],
    cities: ["Engineering Lab", "Quality Inspection Office", "Integration Workshop"],
    readiness: "active",
    riskLevel: "medium",
    automationLevel: "review",
    publicRelevance: "Stable product behavior, quality, and UX.",
    founderSignals: ["test status", "technical blockers", "integration readiness"],
    mustNotFake: ["native app shipped", "integration active", "unvalidated quality"],
  },
  {
    id: "operations-reliability",
    name: "Operations & Reliability Continent",
    purpose: "Ops Tower, monitoring, incidents, recovery, and production blockers.",
    governor: "Ops Governor",
    states: [
      "Ops Tower State",
      "Monitoring State",
      "Incidents State",
      "Recovery State",
      "Production Blockers State",
    ],
    ministries: [
      "Ops Health & Reliability Ministry",
      "Emergency & Incident Ministry",
      "Automation & Self-Managed Systems Ministry",
    ],
    cities: ["Ops Tower", "Recovery Desk", "Production Blocker Board"],
    readiness: "foundation_ready",
    riskLevel: "medium",
    automationLevel: "review",
    publicRelevance: "Diagnostics and product truth only.",
    founderSignals: ["health", "recovery readiness", "production blockers"],
    mustNotFake: ["production deployment", "external monitoring", "secret rotation complete"],
  },
  {
    id: "platforms-devices",
    name: "Platforms & Devices Continent",
    purpose: "Web, user desktop/mobile, and private Founder Command desktop/mobile foundations.",
    governor: "Platforms Governor",
    states: [
      "Web State",
      "User Desktop State",
      "User Mobile State",
      "Founder Command Desktop State",
      "Founder Command Mobile State",
    ],
    ministries: ["Platforms & Devices Ministry", "Engineering & Infrastructure Ministry"],
    cities: ["Desktop/Mobile Workshop", "Web Product Surface", "Founder Device Workshop"],
    readiness: "planned",
    riskLevel: "medium",
    automationLevel: "review",
    publicRelevance: "Web is active; native desktop/mobile are readiness only.",
    founderSignals: ["device targets", "native app blockers", "owner app readiness"],
    mustNotFake: ["installers", "app-store assets", "native command app shipped"],
  },
];

const ministrySeed: Array<
  [
    string,
    string,
    string,
    string,
    string,
    PlanetReadinessState,
    PlanetRiskLevel,
    PlanetAutomationLevel,
  ]
> = [
  ["supreme_command", "Supreme Command Ministry", "Sovereignty & Command Continent", "Founder Command State", "Supreme Command Minister", "foundation_ready", "critical", "founder_approval"],
  ["presidency_command", "Founder Presidency & Coordination Ministry", "Sovereignty & Command Continent", "Presidency Coordination State", "Founder Presidency Coordinator", "foundation_ready", "critical", "founder_approval"],
  ["constitutional_ministry", "Constitutional Ministry", "Sovereignty & Command Continent", "Constitution State", "Constitutional Minister", "foundation_ready", "high", "review"],
  ["legislative_ministry", "Legislative Ministry", "Sovereignty & Command Continent", "Legislative State", "Legislative Minister", "foundation_ready", "medium", "review"],
  ["executive_implementation", "Executive Implementation Ministry", "Sovereignty & Command Continent", "Executive State", "Executive Implementation Minister", "foundation_ready", "medium", "review"],
  ["interior_citizen_affairs", "Interior & Citizen Affairs Ministry", "Citizens & Community Continent", "Citizen Affairs State", "Interior Minister", "foundation_ready", "medium", "review"],
  ["onboarding_immigration", "Onboarding & Immigration Ministry", "Citizens & Community Continent", "Citizen Affairs State", "Onboarding Minister", "planned", "medium", "review"],
  ["account_types_special_programs", "Special Accounts & Islamic Review Ministry", "Law & Rights Continent", "Islamic Review State", "Special Accounts Minister", "foundation_ready", "high", "founder_approval"],
  ["citizen_support", "Citizen Support Ministry", "Citizens & Community Continent", "Support State", "Support Minister", "planned", "medium", "review"],
  ["community_culture", "Community & Culture Ministry", "Citizens & Community Continent", "Community State", "Community Minister", "planned", "medium", "review"],
  ["markets_trading", "Markets & Trading Ministry", "Trading & Markets Continent", "Market State", "Markets Minister", "active", "high", "review"],
  ["execution_ticket", "Execution & Ticket Ministry", "Trading & Markets Continent", "Execution State", "Execution Minister", "active", "high", "review"],
  ["risk_session", "Risk & Session Ministry", "Trading & Markets Continent", "Risk State", "Risk Minister", "foundation_ready", "high", "review"],
  ["market_data_feed", "Market Data & Feed Ministry", "Trading & Markets Continent", "Feed/Data State", "Feed Minister", "foundation_ready", "high", "review"],
  ["records_audit_journal", "Records & Portfolio Ministry", "Trading & Markets Continent", "Decision History State", "Records Minister", "foundation_ready", "medium", "review"],
  ["ai_iq_brain", "AI / IQ / Brain Ministry", "Intelligence & Brain Continent", "Brain State", "Brain Minister", "foundation_ready", "medium", "review"],
  ["personal_companion", "Personal Companion Ministry", "Intelligence & Brain Continent", "Companion State", "Companion Minister", "foundation_ready", "medium", "review"],
  ["coaching_guidance", "Coaching & Guidance Ministry", "Intelligence & Brain Continent", "Coach State", "Coaching Minister", "foundation_ready", "medium", "review"],
  ["journal_learning", "Journal & Learning Ministry", "Intelligence & Brain Continent", "Strategy Review State", "Journal Minister", "foundation_ready", "medium", "review"],
  ["academy_education", "Academy & Education Ministry", "Academy & Development Continent", "Academy State", "Academy Minister", "foundation_ready", "low", "auto"],
  ["strategic_research_analysis", "Strategic Research & Analysis Ministry", "Intelligence & Brain Continent", "Context Quality State", "Research Minister", "planned", "medium", "review"],
  ["guardian_defense", "Guardian & Defense Ministry", "Protection & Defense Continent", "Guardian State", "Guardian Minister", "foundation_ready", "high", "review"],
  ["cybersecurity_privacy", "Cybersecurity & Privacy Ministry", "Protection & Defense Continent", "Cybersecurity State", "Privacy Minister", "foundation_ready", "high", "review"],
  ["justice_legal_compliance", "Justice / Legal / Compliance Ministry", "Law & Rights Continent", "Legal Counsel State", "Legal Minister", "foundation_ready", "high", "founder_approval"],
  ["anti_fraud_manipulation", "Anti-Fraud & Anti-Manipulation Ministry", "Protection & Defense Continent", "Fraud Prevention State", "Anti-Fraud Minister", "foundation_ready", "high", "review"],
  ["operational_law_constitution", "Operational Law & Constitution Ministry", "Law & Rights Continent", "Claims Review State", "Operational Law Minister", "foundation_ready", "high", "review"],
  ["emergency_incident", "Emergency & Incident Ministry", "Operations & Reliability Continent", "Incidents State", "Incident Minister", "foundation_ready", "high", "review"],
  ["engineering_infrastructure", "Engineering & Infrastructure Ministry", "Engineering & Infrastructure Continent", "Platform Engineering State", "Engineering Minister", "active", "medium", "review"],
  ["quality_inspection", "Product Quality & Testing Ministry", "Engineering & Infrastructure Continent", "Quality State", "Quality Minister", "active", "medium", "review"],
  ["ops_health_reliability", "Ops Health & Reliability Ministry", "Operations & Reliability Continent", "Ops Tower State", "Ops Minister", "foundation_ready", "medium", "review"],
  ["platforms_devices", "Platforms & Devices Ministry", "Platforms & Devices Continent", "Web State", "Platforms Minister", "planned", "medium", "review"],
  ["external_integrations", "External Integrations Ministry", "Engineering & Infrastructure Continent", "Integrations State", "Integrations Minister", "planned", "high", "founder_approval"],
  ["automation_self_managed_systems", "Automation & Self-Managed Systems Ministry", "Engineering & Infrastructure Continent", "Platform Engineering State", "Automation Minister", "foundation_ready", "high", "review"],
  ["treasury_economy", "Treasury & Economy Ministry", "Economy & Treasury Continent", "Treasury State", "Treasury Minister", "planned", "high", "founder_approval"],
  ["plans_subscriptions", "Plans & Subscriptions Ministry", "Economy & Treasury Continent", "Plans State", "Plans Minister", "planned", "high", "founder_approval"],
  ["partnerships_sponsorships", "Partnerships & Sponsorships Ministry", "Economy & Treasury Continent", "Partnerships State", "Partnerships Minister", "planned", "high", "founder_approval"],
  ["growth_conversion", "Growth & Conversion Ministry", "Economy & Treasury Continent", "Growth/Conversion State", "Growth Minister", "planned", "medium", "review"],
  ["media_communications", "Media & Communications Ministry", "Media & Growth Continent", "Media State", "Media Minister", "foundation_ready", "high", "founder_approval"],
  ["ai_video_studio_production", "AI Video Studio & Production Ministry", "Media & Growth Continent", "AI Video Studio State", "Video Production Minister", "foundation_ready", "high", "founder_approval"],
  ["rights_brand_ip", "Brand, Rights & IP Ministry", "Law & Rights Continent", "Brand/IP State", "Brand Rights Minister", "foundation_ready", "medium", "review"],
];

export const PLANET_40_MINISTRIES: PlanetEarthMinistry[] = ministrySeed.map(
  ([id, officialName, continent, state, leaderTitle, readiness, riskLevel, automationLevel]) => ({
    id,
    officialName,
    continent,
    state,
    leaderTitle,
    purpose: `${officialName} governs ${state} within ${continent}.`,
    responsibilities: [
      "maintain truthful readiness state",
      "report blockers upward through Presidency Coordination",
      "protect public product claims from fake activation",
    ],
    authorities: [`${officialName.replace(" Ministry", "")} Authority`],
    cityModules: PLANET_EARTH_CONTINENTS.find((item) => item.name === continent)?.cities ?? [],
    professions: ["operator", "review coordinator", "records keeper"],
    citizenFacingValue:
      readiness === "active"
        ? "Supports the current paper-safe product experience."
        : "Prepares future value without claiming activation.",
    founderCommandSignals: ["status", "risk", "blockers", "next action"],
    legalBoundaries: ["no guaranteed profit", "no fake launch", "no certification claim without proof"],
    guardianBoundaries: ["no secret exposure", "no unsafe bypass", "audit sensitive actions later"],
    automationLevel,
    riskLevel,
    readiness,
    blockers:
      riskLevel === "high" || riskLevel === "critical"
        ? ["sensitive activation requires review or Founder approval"]
        : ["human acceptance remains required"],
    nextActions: ["keep report deterministic", "route cross-ministry requests through Presidency Coordination"],
    whatMustNotBeFaked: [
      "users",
      "revenue",
      "billing",
      "broker/feed activation",
      "public launch",
      "live execution",
    ],
  })
);

export const PLANET_AUTHORITIES: PlanetAuthority[] = [
  "Guardian Authority",
  "Legal Claims Authority",
  "Quality Inspection Authority",
  "Rights & Brand Authority",
  "Emergency Response Authority",
  "Islamic Review Desk",
  "Media Review Authority",
  "Treasury Control Authority",
  "Companion Safety Authority",
  "AI Disclaimer Authority",
  "Anti-Scam Authority",
  "Citizen Support Authority",
  "Engineering Review Board",
].map((name, index) => ({
  id: name.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/_$/, ""),
  name,
  parentMinistry:
    PLANET_40_MINISTRIES[index % PLANET_40_MINISTRIES.length].officialName,
  purpose: `${name} reviews a narrow safety, quality, legal, support, or operating power.`,
  powers: ["review", "request revision", "escalate", "block unsafe claims"],
  limits: ["cannot launch", "cannot bill", "cannot publish externally", "cannot execute trades"],
  escalationRoute: [
    "Founder Presidency / Central Coordination System",
    "Founder Command Room",
  ],
  founderApprovalRequired: ["Treasury Control Authority", "Media Review Authority"].includes(name),
}));

export const PLANET_CITIES: PlanetCity[] = [
  ["chart_city", "Chart City", "Trading & Markets Continent", "Market State", "Markets & Trading Ministry", "public"],
  ["execution_hall", "Execution Hall", "Trading & Markets Continent", "Execution State", "Execution & Ticket Ministry", "public"],
  ["watchlist_city", "Watchlist City", "Trading & Markets Continent", "Market State", "Markets & Trading Ministry", "public"],
  ["market_context_district", "Market Context District", "Trading & Markets Continent", "Feed/Data State", "Market Data & Feed Ministry", "public"],
  ["companion_center", "Companion Center", "Intelligence & Brain Continent", "Companion State", "Personal Companion Ministry", "public"],
  ["brain_center", "Brain Center", "Intelligence & Brain Continent", "Brain State", "AI / IQ / Brain Ministry", "plan_scoped"],
  ["coach_center", "Coach Center", "Intelligence & Brain Continent", "Coach State", "Coaching & Guidance Ministry", "plan_scoped"],
  ["journal_office", "Journal Office", "Intelligence & Brain Continent", "Strategy Review State", "Journal & Learning Ministry", "plan_scoped"],
  ["academy_library", "Academy Library", "Academy & Development Continent", "Academy State", "Academy & Education Ministry", "public"],
  ["guardian_tower", "Guardian Tower", "Protection & Defense Continent", "Guardian State", "Guardian & Defense Ministry", "internal"],
  ["legal_court", "Legal Court", "Law & Rights Continent", "Legal Counsel State", "Justice / Legal / Compliance Ministry", "internal"],
  ["treasury_hall", "Treasury Hall", "Economy & Treasury Continent", "Treasury State", "Treasury & Economy Ministry", "founder_private"],
  ["media_studio", "Media Studio", "Media & Growth Continent", "Media State", "Media & Communications Ministry", "internal"],
  ["ai_video_studio", "AI Video Studio", "Media & Growth Continent", "AI Video Studio State", "AI Video Studio & Production Ministry", "internal"],
  ["community_square", "Community Square", "Citizens & Community Continent", "Community State", "Community & Culture Ministry", "plan_scoped"],
  ["vip_private_rooms", "VIP Private Rooms", "Citizens & Community Continent", "VIP Rooms State", "Community & Culture Ministry", "plan_scoped"],
  ["engineering_lab", "Engineering Lab", "Engineering & Infrastructure Continent", "Platform Engineering State", "Engineering & Infrastructure Ministry", "internal"],
  ["ops_tower", "Ops Tower", "Operations & Reliability Continent", "Ops Tower State", "Ops Health & Reliability Ministry", "internal"],
  ["feedback_court", "Feedback Court", "Citizens & Community Continent", "Support State", "Citizen Support Ministry", "public"],
  ["rights_brand_office", "Rights & Brand Office", "Law & Rights Continent", "Brand/IP State", "Brand, Rights & IP Ministry", "internal"],
  ["islamic_review_desk", "Islamic Review Desk", "Law & Rights Continent", "Islamic Review State", "Special Accounts & Islamic Review Ministry", "internal"],
  ["desktop_mobile_workshop", "Desktop/Mobile Workshop", "Platforms & Devices Continent", "User Desktop State", "Platforms & Devices Ministry", "internal"],
  ["founder_approval_center", "Founder Approval Center", "Sovereignty & Command Continent", "Founder Command State", "Supreme Command Ministry", "founder_private"],
].map(([id, name, continent, state, ministryOwner, userVisibility]) => ({
  id,
  name,
  continent,
  state,
  ministryOwner,
  userVisibility: userVisibility as PlanetCity["userVisibility"],
  planAccess:
    userVisibility === "founder_private"
      ? ["founder"]
      : userVisibility === "internal"
      ? ["staff", "founder"]
      : ["guest", "free_demo", "pro", "vip", "enterprise"],
  readiness: userVisibility === "public" ? "active" : "foundation_ready",
  safetyTruthRules: [
    "no fake metrics",
    "no live execution",
    "no real-money routing",
    "no public launch claim",
  ],
}));

export const PLANET_PROFESSIONS: PlanetProfession[] = [
  ["engineers", "Engineers", "Engineering & Infrastructure Ministry", "human"],
  ["guardians", "Guardians", "Guardian & Defense Ministry", "human"],
  ["legal_counsel", "Legal Counsel", "Justice / Legal / Compliance Ministry", "human"],
  ["media_officers", "Media Officers", "Media & Communications Ministry", "human"],
  ["campaign_operators", "Campaign Operators", "Growth & Conversion Ministry", "future"],
  ["video_producers", "Video Producers", "AI Video Studio & Production Ministry", "future"],
  ["coaches", "Coaches", "Coaching & Guidance Ministry", "future"],
  ["academy_teachers", "Academy Teachers", "Academy & Education Ministry", "future"],
  ["community_moderators", "Community Moderators", "Community & Culture Ministry", "future"],
  ["support_agents", "Support Agents", "Citizen Support Ministry", "future"],
  ["records_keepers", "Records Keepers", "Records & Portfolio Ministry", "module"],
  ["quality_inspectors", "Quality Inspectors", "Product Quality & Testing Ministry", "human"],
  ["ops_operators", "Ops Operators", "Ops Health & Reliability Ministry", "human"],
  ["treasury_operators", "Treasury Operators", "Treasury & Economy Ministry", "future"],
  ["integration_engineers", "Integration Engineers", "External Integrations Ministry", "future"],
  ["security_officers", "Security Officers", "Cybersecurity & Privacy Ministry", "human"],
  ["ai_agents", "AI Agents", "AI / IQ / Brain Ministry", "agent"],
  ["companion_agents", "Companion Agents", "Personal Companion Ministry", "agent"],
  ["founder_companion", "Founder Companion", "Supreme Command Ministry", "agent"],
  ["content_agents", "Content Agents", "Content Factory State", "agent"],
].map(([id, title, ministry, workerKind]) => ({
  id,
  title,
  ministry,
  workerKind: workerKind as PlanetProfession["workerKind"],
  purpose: `${title} support the ${ministry} without creating fake staff accounts.`,
  permissions: ["draft", "review", "report"],
  boundaries: ["cannot launch", "cannot bill", "cannot execute live trades", "cannot expose secrets"],
  reportsTo: ministry,
  automationLevel: workerKind === "agent" ? "review" : "review",
}));

export const PLANET_CITIZEN_CLASSES: PlanetCitizenClassModel[] = [
  {
    id: "guest",
    label: "Guest",
    visibility: ["public entry", "paper-safe product truth"],
    hidden: ["Founder Command", "paid features", "private reports"],
    planAccess: "public safe only",
    companionLevel: "none or basic guidance",
    communityAccess: "none",
    academyAccess: "preview",
    journalCoachAccess: "none",
    tradingAccess: "view/paper-safe entry only",
    blockedCapabilities: ["live execution", "real money", "billing"],
    upgradePath: "create account later; no checkout active",
    productTruthLanguage: "Public product is evaluation/paper safe.",
  },
  {
    id: "free_demo",
    label: "Free / Demo Citizen",
    visibility: ["workstation", "settings", "diagnostics", "basic Companion"],
    hidden: ["Founder Command", "VIP Brain", "billing checkout"],
    planAccess: "active paper-safe baseline",
    companionLevel: "Demo / Paper Assistant",
    communityAccess: "basic planned",
    academyAccess: "basic",
    journalCoachAccess: "basic prompts",
    tradingAccess: "paper only",
    blockedCapabilities: ["live execution", "real money", "broker activation"],
    upgradePath: "Pro/VIP planned only; no billing active",
    productTruthLanguage: "Paper-safe active; live and real money blocked.",
  },
  {
    id: "pro",
    label: "Pro Citizen",
    visibility: ["future Pro workstation depth"],
    hidden: ["Founder Command", "VIP-only review", "Enterprise admin"],
    planAccess: "planned unless entitlement exists",
    companionLevel: "Pro Assistant planned",
    communityAccess: "Pro rooms planned",
    academyAccess: "expanded planned",
    journalCoachAccess: "deeper session review planned",
    tradingAccess: "paper-safe until real gates exist",
    blockedCapabilities: ["paid activation", "premium unlock without entitlement"],
    upgradePath: "requires future entitlement and billing architecture",
    productTruthLanguage: "Pro is planned/locked by default.",
  },
  {
    id: "vip",
    label: "VIP Citizen",
    visibility: ["future VIP Brain and rooms"],
    hidden: ["Founder Command", "Enterprise admin"],
    planAccess: "planned unless entitlement exists",
    companionLevel: "VIP Brain planned",
    communityAccess: "VIP rooms planned",
    academyAccess: "advanced planned",
    journalCoachAccess: "advanced performance review planned",
    tradingAccess: "paper-safe until real gates exist",
    blockedCapabilities: ["VIP guarantee", "win-rate claims", "priority support claim without system"],
    upgradePath: "requires future VIP entitlement and reviewed support model",
    productTruthLanguage: "VIP is not active unless entitlement exists.",
  },
  {
    id: "enterprise",
    label: "Enterprise House",
    visibility: ["future team/admin/audit"],
    hidden: ["Founder Command owner controls"],
    planAccess: "future only",
    companionLevel: "Enterprise Assistant later",
    communityAccess: "enterprise rooms future",
    academyAccess: "team learning future",
    journalCoachAccess: "audit/compliance future",
    tradingAccess: "not active",
    blockedCapabilities: ["enterprise sale claim", "team admin availability"],
    upgradePath: "future enterprise contract path only",
    productTruthLanguage: "Enterprise remains future planned.",
  },
  {
    id: "beta",
    label: "Beta Citizen",
    visibility: ["guarded beta readiness if invited later"],
    hidden: ["Founder Command", "production controls"],
    planAccess: "closed beta only when explicitly configured",
    companionLevel: "Demo/Pro depending entitlement",
    communityAccess: "beta room planned",
    academyAccess: "basic",
    journalCoachAccess: "basic",
    tradingAccess: "paper-safe only",
    blockedCapabilities: ["public launch claim", "live execution"],
    upgradePath: "operator review only",
    productTruthLanguage: "Beta is not public launch.",
  },
  {
    id: "staff_operator",
    label: "Staff / Operator",
    visibility: ["guarded internal operations"],
    hidden: ["Founder-only approvals unless delegated later"],
    planAccess: "operator guarded",
    companionLevel: "operator assist later",
    communityAccess: "moderation tools later",
    academyAccess: "internal training",
    journalCoachAccess: "none by default",
    tradingAccess: "no user trading authority",
    blockedCapabilities: ["secret exposure", "critical override"],
    upgradePath: "explicit role assignment only",
    productTruthLanguage: "Operator access is guarded and audited later.",
  },
  {
    id: "founder_king",
    label: "Founder King",
    visibility: ["all internal reports", "Founder Command Room"],
    hidden: ["nothing in owner model; private user data still protected by policy"],
    planAccess: "owner-only private",
    companionLevel: "Founder Personal Companion",
    communityAccess: "all future summaries",
    academyAccess: "all summaries",
    journalCoachAccess: "all aggregate readiness summaries",
    tradingAccess: "does not bypass live/real-money blocks",
    blockedCapabilities: ["critical Guardian/Legal override without remediation"],
    upgradePath: "not a paid plan",
    productTruthLanguage: "Founder authority is private and still bound by safety.",
  },
];

export function getPlanetEarthHierarchySnapshot(checkedAt = new Date().toISOString()) {
  const stateNodes: PlanetHierarchyNode[] = PLANET_EARTH_CONTINENTS.flatMap((continent) =>
    continent.states.map((state, index) => ({
      id: `${continent.id}-state-${index + 1}`,
      kind: "state" as const,
      name: state,
      parentId: continent.id,
      level: 8,
      purpose: `${state} belongs to ${continent.name}.`,
      reportDestination: "Founder Presidency / Central Coordination System",
      visibility: "internal" as const,
      readiness: continent.readiness,
      riskLevel: continent.riskLevel,
      automationLevel: continent.automationLevel,
      truthRules: continent.mustNotFake,
    }))
  );

  const hierarchyNodes: PlanetHierarchyNode[] = [
    {
      id: "founder-king",
      kind: "founder_king",
      name: "Founder King / Sovereign Creator",
      parentId: null,
      level: 1,
      purpose: "Highest owner authority and final sensitive approval layer.",
      reportDestination: "Founder Command Room",
      visibility: "founder_private",
      readiness: "foundation_ready",
      riskLevel: "critical",
      automationLevel: "founder_approval",
      truthRules: ["owner-only", "no critical override without remediation"],
    },
    {
      id: "founder-command-room",
      kind: "command_room",
      name: "Founder King Command Room",
      parentId: "founder-king",
      level: 2,
      purpose: "Private read-only command surface foundation for whole-planet reporting.",
      reportDestination: "Founder King",
      visibility: "founder_private",
      readiness: "foundation_ready",
      riskLevel: "critical",
      automationLevel: "founder_approval",
      truthRules: ["not public", "not a user plan", "no approval execution yet"],
    },
    {
      id: "planet-constitution",
      kind: "constitution",
      name: "Planet Constitution",
      parentId: "founder-command-room",
      level: 3,
      purpose: "Defines non-negotiable truth, safety, legal, security, and launch laws.",
      reportDestination: "Founder Command Room",
      visibility: "internal",
      readiness: "foundation_ready",
      riskLevel: "high",
      automationLevel: "review",
      truthRules: ["no guaranteed profit", "no fake launch", "no secrets in Git"],
    },
    ...PLANET_EARTH_CONTINENTS.map((continent) => ({
      id: continent.id,
      kind: "continent" as const,
      name: continent.name,
      parentId: "founder-presidency",
      level: 7,
      purpose: continent.purpose,
      reportDestination: "Founder Presidency / Central Coordination System",
      visibility: "internal" as const,
      readiness: continent.readiness,
      riskLevel: continent.riskLevel,
      automationLevel: continent.automationLevel,
      truthRules: continent.mustNotFake,
    })),
    ...stateNodes,
  ];

  const governors: PlanetGovernor[] = PLANET_EARTH_CONTINENTS.map((continent) => ({
    id: `${continent.id}-governor`,
    title: continent.governor,
    governs: continent.name,
    scope: "continent",
    permissions: ["summarize state status", "request cross-ministry review"],
    limits: ["cannot launch", "cannot bill", "cannot activate live trading"],
    reportsTo: "Founder Presidency / Central Coordination System",
  }));

  return {
    checkedAt,
    mode: "tpm_planet_earth_hierarchy_core",
    hierarchyChain: PLANET_EARTH_HIERARCHY_CHAIN,
    nodes: hierarchyNodes,
    continents: PLANET_EARTH_CONTINENTS,
    states: stateNodes,
    governors,
    ministries: PLANET_40_MINISTRIES,
    authorities: PLANET_AUTHORITIES,
    cities: PLANET_CITIES,
    professions: PLANET_PROFESSIONS,
    citizenClasses: PLANET_CITIZEN_CLASSES,
    summary: {
      hierarchyLevels: PLANET_EARTH_HIERARCHY_CHAIN.length,
      continents: PLANET_EARTH_CONTINENTS.length,
      states: stateNodes.length,
      governors: governors.length,
      ministries: PLANET_40_MINISTRIES.length,
      authorities: PLANET_AUTHORITIES.length,
      cities: PLANET_CITIES.length,
      professions: PLANET_PROFESSIONS.length,
      citizenClasses: PLANET_CITIZEN_CLASSES.length,
      publicFounderRouteExposed: false,
      fakeMetricsIncluded: false,
      launchActivated: false,
      billingActivated: false,
      liveExecutionActivated: false,
    },
  };
}
