import "server-only";

import type {
  FounderBriefing,
  MinistryReport,
  MinistryStatus,
  PlanetAutomationLevel,
  PlanetCitizenClass,
  PlanetCityModule,
  PlanetContinent,
  PlanetMinistry,
  PlanetProfession,
  PlanetReadinessState,
  PlanetRiskLevel,
  PlanetState,
  PlanetStateSummary,
  ProductTruthSnapshot,
  SafetyBoundaryState,
} from "./types";
import { getMinistryCoordinationReadinessFor } from "./coordination";
import { PLANET_40_MINISTRIES } from "./hierarchy";

const PRODUCT_TRUTH: ProductTruthSnapshot = {
  liveExecution: "blocked",
  realMoneyRouting: "blocked",
  brokerFeedActivation: "not_faked",
  billing: "inactive",
  publicLaunch: "not_claimed",
  socialPublishing: "inactive",
  secrets: "not_exposed",
};

const SAFETY_BOUNDARIES: SafetyBoundaryState = {
  liveExecution: "blocked",
  realMoneyRouting: "blocked",
  brokerFeedActivation: "blocked",
  billingActivation: "blocked",
  publicLaunchClaim: "blocked",
  socialPublishing: "blocked",
  secretExposure: "blocked",
  criticalOverride: "blocked_without_remediation",
  founderApproval: "required_for_high_risk",
  auditTrail: "required_for_sensitive_actions",
};

const CITIZEN_CLASSES: PlanetStateSummary["citizenClasses"] = [
  {
    key: "free_demo",
    label: "Demo / Free Citizen",
    state: "active_paper",
    truth: "Paper-safe access only; no live execution or paid entitlement claim.",
  },
  {
    key: "pro",
    label: "Pro Citizen",
    state: "planned",
    truth: "Prepared as a product tier; billing and paid activation remain inactive.",
  },
  {
    key: "vip",
    label: "VIP Citizen",
    state: "planned",
    truth: "Prepared as an identity and roadmap tier; no VIP entitlement is active by default.",
  },
  {
    key: "enterprise",
    label: "Enterprise House",
    state: "future",
    truth: "Future operating class only; no enterprise access or billing is active.",
  },
];

const CONTINENTS: PlanetContinent[] = [
  {
    id: "trading",
    name: "Trading Continent",
    purpose: "Market reading, chart focus, and paper execution rehearsal.",
    ownerRole: "Markets & Trading Ministry",
    readiness: "active",
    automationLevel: "review",
    riskLevel: "high",
    citizenClasses: ["free_demo", "pro", "vip", "enterprise"],
    states: ["Market State", "Execution State", "Risk State"],
    ministries: ["Markets & Trading", "Records / Audit / Journal"],
    cityModules: ["Chart City", "Ticket City", "Watchlist City"],
    active: ["Public market workspace", "Paper ticket", "Fallback market disclosure"],
    planned: ["Entitlement-aware advanced workspaces", "Future broker/feed readiness review"],
    blocked: ["Live execution", "Real-money routing", "Unconfigured broker/feed claims"],
    reportDestination: "Founder Command Room",
    truthRules: ["paper route only", "fallback-first market truth", "no live route claim"],
  },
  {
    id: "intelligence",
    name: "Intelligence Continent",
    purpose: "Bounded AI/IQ, Companion, Coach, journal, and decision-support foundations.",
    ownerRole: "AI / IQ / Brain Ministry",
    readiness: "foundation_ready",
    automationLevel: "review",
    riskLevel: "medium",
    citizenClasses: ["free_demo", "pro", "vip", "enterprise"],
    states: ["Brain State", "Companion State", "Coach State"],
    ministries: ["AI / IQ / Brain", "Academy & Education"],
    cityModules: ["Brain Center", "Companion Center", "Coach Center"],
    active: ["Operator-assist wording", "Assistant tier truth", "No-guarantee guidance"],
    planned: ["Deeper journal intelligence", "VIP strategy review assistant"],
    blocked: ["Guaranteed signals", "Win-rate claims", "Autonomous trading actions"],
    reportDestination: "Founder Command Room",
    truthRules: ["no prediction certainty", "no financial advice", "operator assist only"],
  },
  {
    id: "protection",
    name: "Protection Continent",
    purpose: "Guardian, abuse defense, safety boundaries, and incident response.",
    ownerRole: "Guardian & Defense Ministry",
    readiness: "foundation_ready",
    automationLevel: "review",
    riskLevel: "high",
    citizenClasses: ["free_demo", "pro", "vip", "enterprise"],
    states: ["Guardian State", "Abuse Defense State", "Safety Boundaries State"],
    ministries: ["Guardian & Defense", "Emergency & Incident"],
    cityModules: ["Guardian Center", "Safety Boundaries Office"],
    active: ["Threat model", "Operator playbook", "Hard blocked execution boundaries"],
    planned: ["Founder alert queues", "Abuse review workflow"],
    blocked: ["Invasive surveillance", "Silent security overrides"],
    reportDestination: "Founder Command Room",
    truthRules: ["privacy-conscious protection", "audit sensitive actions", "critical blocks stay blocked"],
  },
  {
    id: "law_rights",
    name: "Law & Rights Continent",
    purpose: "Legal Counsel, claims, rights, brand, and Islamic account wording.",
    ownerRole: "Justice / Legal / Compliance Ministry",
    readiness: "foundation_ready",
    automationLevel: "founder_approval",
    riskLevel: "high",
    citizenClasses: ["free_demo", "pro", "vip", "enterprise"],
    states: ["Legal State", "Claims Court", "Rights State"],
    ministries: ["Justice / Legal / Compliance", "Rights / Brand / IP"],
    cityModules: ["Legal Counsel Center", "Rights & Brand Office", "Islamic Account Review Desk"],
    active: ["Claims policy", "Risk disclaimers", "Brand protection guidance"],
    planned: ["External legal review", "Trademark readiness workflow"],
    blocked: ["Legal certification claim", "Sharia certification claim", "Risk-free wording"],
    reportDestination: "Founder Command Room",
    truthRules: ["not legal advice", "not certified by default", "no copied competitor identity"],
  },
  {
    id: "people_community",
    name: "People & Community Continent",
    purpose: "Citizen affairs, feedback, support readiness, and future community rooms.",
    ownerRole: "Interior & Citizen Affairs Ministry",
    readiness: "foundation_ready",
    automationLevel: "review",
    riskLevel: "medium",
    citizenClasses: ["free_demo", "pro", "vip", "enterprise"],
    states: ["Citizen Affairs State", "Community State", "Support State"],
    ministries: ["Interior & Citizen Affairs", "Community & Culture"],
    cityModules: ["Feedback Court", "Community Square", "VIP Private Rooms"],
    active: ["Feedback flow", "Beta triage docs", "Protected account state"],
    planned: ["Community rooms", "Priority support readiness", "VIP rooms"],
    blocked: ["Fake tester participation", "Public social community claim"],
    reportDestination: "Founder Command Room",
    truthRules: ["no fake users", "no public signup claim", "support remains guarded"],
  },
  {
    id: "academy",
    name: "Academy Continent",
    purpose: "Education, glossary, paper training, learning paths, and safe coaching language.",
    ownerRole: "Academy & Education Ministry",
    readiness: "foundation_ready",
    automationLevel: "auto",
    riskLevel: "low",
    citizenClasses: ["free_demo", "pro", "vip", "enterprise"],
    states: ["Academy Library", "Lessons State", "Paper Training State"],
    ministries: ["Academy & Education", "Records / Audit / Journal"],
    cityModules: ["Academy", "Journal / Records Office", "Coach Center"],
    active: ["Academy architecture", "Journal and coach safety model"],
    planned: ["Lesson packs", "Decision replay", "Discipline scoring"],
    blocked: ["Financial advice", "Gambling-style prompts", "Profit promises"],
    reportDestination: "Founder Command Room",
    truthRules: ["education only", "paper training first", "no manipulation"],
  },
  {
    id: "economy_treasury",
    name: "Economy & Treasury Continent",
    purpose: "Plan classes, monetization readiness, entitlement truth, and billing inactive state.",
    ownerRole: "Treasury & Economy Ministry",
    readiness: "foundation_ready",
    automationLevel: "founder_approval",
    riskLevel: "high",
    citizenClasses: ["free_demo", "pro", "vip", "enterprise"],
    states: ["Treasury State", "Plan Classes State", "Entitlement State"],
    ministries: ["Treasury & Economy", "Account Types & Special Programs"],
    cityModules: ["Treasury / Plans Center", "Account Types Desk"],
    active: ["Plan catalog truth", "Plan visual identity", "Billing inactive disclosure"],
    planned: ["Pro/VIP entitlement logic", "Enterprise future readiness"],
    blocked: ["Billing activation", "Fake paid access", "Performance-fee public claim"],
    reportDestination: "Founder Command Room",
    truthRules: ["no fake subscription", "no VIP active claim by default", "current fee is zero"],
  },
  {
    id: "media_communications",
    name: "Media & Communications Continent",
    purpose: "Content planning, campaign review, AI Video Studio readiness, and channel registry.",
    ownerRole: "Media & Communications Ministry",
    readiness: "foundation_ready",
    automationLevel: "founder_approval",
    riskLevel: "high",
    citizenClasses: ["free_demo", "pro", "vip", "enterprise"],
    states: ["Media Office", "AI Video Studio", "Campaign State"],
    ministries: ["Media & Communications", "Justice / Legal / Compliance"],
    cityModules: ["Media Office", "AI Video Studio", "Content Calendar"],
    active: ["Media claims policy", "Approval lifecycle", "Social account registry docs"],
    planned: ["Founder media approvals", "Campaign queues", "Video drafts"],
    blocked: ["External posting", "Connected social accounts", "Fake followers or metrics"],
    reportDestination: "Founder Command Room",
    truthRules: ["no publishing tokens", "legal review required", "no fake launch claims"],
  },
  {
    id: "engineering_infrastructure",
    name: "Engineering & Infrastructure Continent",
    purpose: "Platform engineering, product quality, regression discipline, and device foundations.",
    ownerRole: "Engineering & Infrastructure Ministry",
    readiness: "active",
    automationLevel: "review",
    riskLevel: "medium",
    citizenClasses: ["free_demo", "pro", "vip", "enterprise"],
    states: ["Engineering State", "Quality State", "Platform State"],
    ministries: ["Engineering & Infrastructure", "Quality & Inspection", "Platforms & Devices"],
    cityModules: ["Engineering Guild", "Desktop/Mobile Workshop", "Quality Inspection Office"],
    active: ["Web product", "Regression tests", "Desktop/mobile readiness contracts"],
    planned: ["Native app builds", "Distribution readiness", "Expanded QA matrix"],
    blocked: ["Fake native release claim", "Unvalidated product changes"],
    reportDestination: "Founder Command Room",
    truthRules: ["test before claim", "no fake capability", "preserve visual discipline"],
  },
  {
    id: "operations_reliability",
    name: "Operations & Reliability Continent",
    purpose: "Ops Tower, health, readiness, incidents, recovery, and deployment blockers.",
    ownerRole: "Ops / Health / Reliability Ministry",
    readiness: "foundation_ready",
    automationLevel: "review",
    riskLevel: "medium",
    citizenClasses: ["free_demo", "pro", "vip", "enterprise"],
    states: ["Ops Tower", "Health State", "Recovery State"],
    ministries: ["Ops / Health / Reliability", "Emergency & Incident"],
    cityModules: ["Ops Tower", "Recovery Desk", "Readiness Control"],
    active: ["Health APIs", "Ops runbooks", "Production blockers surfaced"],
    planned: ["External monitoring", "Staging deployment", "Incident drill history"],
    blocked: ["Production deployment claim", "Secret exposure", "Monitoring active claim without config"],
    reportDestination: "Founder Command Room",
    truthRules: ["no fake production readiness", "manual recovery", "external monitoring unconfigured until real"],
  },
  {
    id: "founder_command_capital",
    name: "Founder Command Capital",
    purpose: "Private Founder Command Room, approval center, and whole-planet reporting.",
    ownerRole: "Founder King / Sovereign Creator",
    readiness: "foundation_ready",
    automationLevel: "founder_approval",
    riskLevel: "critical",
    citizenClasses: [],
    states: ["Founder King Command Room", "Founder Approval Center", "Founder Daily Briefing"],
    ministries: ["Presidency & Command"],
    cityModules: ["Founder Command Center", "Founder Approval Center", "Founder Personal Companion"],
    active: ["Documentation", "Private owner-only contracts", "Planet OS reporting snapshot"],
    planned: ["Desktop command app", "Mobile command app", "Owner-only approval UI"],
    blocked: ["Public command route", "Fake owner metrics", "Critical override without remediation"],
    reportDestination: "Founder Command Room",
    truthRules: ["owner-only", "read-only by default", "sensitive actions audited"],
  },
];

const PLANET_STATES: PlanetState[] = CONTINENTS.flatMap((continent) =>
  continent.states.map((stateName, index) => ({
    id: `${continent.id}_${index + 1}`,
    continentId: continent.id,
    name: stateName,
    purpose: `Operational state inside ${continent.name}.`,
    readiness: continent.readiness,
    riskLevel: continent.riskLevel,
    automationLevel: continent.automationLevel,
    active: continent.active.slice(0, 2),
    planned: continent.planned.slice(0, 2),
    blocked: continent.blocked.slice(0, 2),
    reportDestination: "Founder Command Room",
  }))
);

const CITY_MODULES: PlanetCityModule[] = CONTINENTS.flatMap((continent) =>
  continent.cityModules.map((moduleName, index) => ({
    id: `${continent.id}_module_${index + 1}`,
    continentId: continent.id,
    stateId: `${continent.id}_${Math.min(index + 1, continent.states.length)}`,
    name: moduleName,
    purpose: `Product module governed by ${continent.ownerRole}.`,
    readiness: continent.readiness,
    citizenClasses: continent.citizenClasses,
    active: continent.active.slice(0, 2),
    planned: continent.planned.slice(0, 2),
    blocked: continent.blocked.slice(0, 2),
    truthRules: continent.truthRules,
  }))
);

const PROFESSIONS: PlanetProfession[] = [
  {
    id: "founder_king",
    title: "Founder King / Sovereign Creator",
    purpose: "Owns final product direction and high-risk approvals.",
    permissions: ["review planet reports", "approve reviewed high-risk actions"],
    boundaries: ["cannot bypass critical Guardian/Legal blocks without remediation"],
    reportsTo: "Founder Command Room",
  },
  {
    id: "guardian_officer",
    title: "Guardian Officer",
    purpose: "Protects accounts, APIs, abuse boundaries, and unsafe claims.",
    permissions: ["flag abuse", "escalate incidents", "recommend blocks"],
    boundaries: ["no invasive surveillance", "no secret exposure"],
    reportsTo: "Guardian & Defense Ministry",
  },
  {
    id: "legal_counsel",
    title: "Legal Counsel Coordinator",
    purpose: "Reviews claims, disclaimers, media wording, and account status wording.",
    permissions: ["block risky claims", "request revisions", "escalate to Founder"],
    boundaries: ["does not claim legal certification", "does not replace qualified counsel"],
    reportsTo: "Justice / Legal / Compliance Ministry",
  },
  {
    id: "engineering_guild",
    title: "Engineering Guild",
    purpose: "Maintains code, tests, visual discipline, and safe product contracts.",
    permissions: ["ship validated code", "repair regressions", "write operational contracts"],
    boundaries: ["no fake capability", "no secrets in code", "no launch claims"],
    reportsTo: "Engineering & Infrastructure Ministry",
  },
  {
    id: "media_officer",
    title: "Media Officer",
    purpose: "Prepares content drafts and campaign plans for review.",
    permissions: ["draft content", "classify campaign risk"],
    boundaries: ["no external posting", "no risky claim without review"],
    reportsTo: "Media & Communications Ministry",
  },
  {
    id: "academy_teacher",
    title: "Academy Teacher / Coach",
    purpose: "Creates education, paper training, and safe coaching guidance.",
    permissions: ["write lessons", "suggest journal prompts"],
    boundaries: ["no financial advice", "no guaranteed outcomes"],
    reportsTo: "Academy & Education Ministry",
  },
];

type MinistryDefinition = Omit<
  MinistryReport,
  "coordination" | "lastUpdated" | "productTruth" | "reportDestination"
>;

const MINISTRY_DEFINITIONS: MinistryDefinition[] = [
  {
    ministryId: "presidency_command",
    ministryName: "Presidency & Command",
    leaderTitle: "Founder Command Chief",
    status: "ready",
    confidence: "high",
    riskLevel: "critical",
    automationLevel: "founder_approval",
    summary: "Coordinates Planet OS reporting and keeps Founder Command private.",
    keyMetrics: ["private_owner_only", "public_command_route_absent"],
    activeWork: ["planet snapshot", "founder briefing"],
    blockers: ["desktop/mobile command apps not shipped"],
    incidents: [],
    pendingApprovals: ["future owner-only command UI"],
    guardianFlags: ["protect command access"],
    legalFlags: ["avoid authority or public launch claims"],
    engineeringFlags: ["no public command route"],
    citizenImpact: "Citizens do not see private owner controls.",
    revenueImpactLater: "No revenue claim; supports future governance only.",
    nextActions: ["Keep command reporting read-only until owner guard exists."],
    founderDecisionNeeded: false,
    reportCadence: "daily",
  },
  {
    ministryId: "interior_citizen_affairs",
    ministryName: "Interior & Citizen Affairs",
    leaderTitle: "Citizen Affairs Operator",
    status: "operating",
    confidence: "medium",
    riskLevel: "medium",
    automationLevel: "review",
    summary: "Owns account/session truth, feedback routing, and citizen-facing clarity.",
    keyMetrics: ["auth_guarded", "feedback_route_guarded"],
    activeWork: ["auth/session UI", "feedback triage path"],
    blockers: ["real beta users are not claimed"],
    incidents: [],
    pendingApprovals: [],
    guardianFlags: ["protect feedback spam"],
    legalFlags: ["avoid public signup claims"],
    engineeringFlags: ["preserve protected route checks"],
    citizenImpact: "Citizens get clear account and feedback states.",
    revenueImpactLater: "No billing implication.",
    nextActions: ["Keep feedback lifecycle compact and guarded."],
    founderDecisionNeeded: false,
    reportCadence: "daily",
  },
  {
    ministryId: "guardian_defense",
    ministryName: "Guardian & Defense",
    leaderTitle: "Guardian Commander",
    status: "ready",
    confidence: "high",
    riskLevel: "high",
    automationLevel: "review",
    summary: "Protects abuse, assistant misuse, API guardrails, and unsafe activation attempts.",
    keyMetrics: ["live_execution_blocked", "real_money_blocked"],
    activeWork: ["threat model", "operator playbook", "safety boundaries"],
    blockers: ["owner alert automation not shipped"],
    incidents: [],
    pendingApprovals: [],
    guardianFlags: ["watch execution bypass attempts", "watch media abuse"],
    legalFlags: ["avoid surveillance claims"],
    engineeringFlags: ["keep protected APIs guarded"],
    citizenImpact: "Improves safety semantics without invasive monitoring.",
    revenueImpactLater: "Trust readiness only; no monetization claim.",
    nextActions: ["Route future sensitive actions through audit events."],
    founderDecisionNeeded: false,
    reportCadence: "event_driven",
  },
  {
    ministryId: "justice_legal_compliance",
    ministryName: "Justice / Legal / Compliance",
    leaderTitle: "Legal Counsel Lead",
    status: "ready",
    confidence: "medium",
    riskLevel: "high",
    automationLevel: "founder_approval",
    summary: "Maintains product claims, disclaimers, Islamic status wording, and media review rules.",
    keyMetrics: ["no_financial_advice", "no_sharia_certification_claim"],
    activeWork: ["claims policy", "risk disclosure", "Islamic account disclaimer"],
    blockers: ["external qualified legal review not claimed"],
    incidents: [],
    pendingApprovals: ["future public claims", "future pricing language"],
    guardianFlags: ["block manipulative claims"],
    legalFlags: ["no guaranteed profit", "no win-rate claims"],
    engineeringFlags: ["surface truthful status only"],
    citizenImpact: "Citizens see safer, non-deceptive language.",
    revenueImpactLater: "Pricing claims require review before activation.",
    nextActions: ["Keep all planned claims in approval workflow."],
    founderDecisionNeeded: false,
    reportCadence: "weekly",
  },
  {
    ministryId: "engineering_infrastructure",
    ministryName: "Engineering & Infrastructure",
    leaderTitle: "Engineering Guild Master",
    status: "operating",
    confidence: "high",
    riskLevel: "medium",
    automationLevel: "review",
    summary: "Owns validated code, APIs, UI stability, and platform contracts.",
    keyMetrics: ["tests_required", "build_required"],
    activeWork: ["web app", "regression suite", "Planet OS runtime contracts"],
    blockers: ["native apps not shipped"],
    incidents: [],
    pendingApprovals: [],
    guardianFlags: ["no secret commits"],
    legalFlags: ["no fake capability wording"],
    engineeringFlags: ["validate before commit"],
    citizenImpact: "Citizens get stable web product surfaces.",
    revenueImpactLater: "No revenue path activated.",
    nextActions: ["Keep runtime contracts deterministic and test-covered."],
    founderDecisionNeeded: false,
    reportCadence: "daily",
  },
  {
    ministryId: "treasury_economy",
    ministryName: "Treasury & Economy",
    leaderTitle: "Treasury Operator",
    status: "planned",
    confidence: "medium",
    riskLevel: "high",
    automationLevel: "founder_approval",
    summary: "Plans Free, Pro, VIP, and Enterprise classes while billing remains inactive.",
    keyMetrics: ["billing_inactive", "current_fee_zero"],
    activeWork: ["plan catalog truth", "VIP roadmap"],
    blockers: ["billing provider absent", "paid entitlements inactive"],
    incidents: [],
    pendingApprovals: ["future billing language", "future performance-fee research"],
    guardianFlags: ["prevent fake paid access"],
    legalFlags: ["pricing requires review"],
    engineeringFlags: ["do not unlock features without entitlement logic"],
    citizenImpact: "Plan labels remain truthful and non-deceptive.",
    revenueImpactLater: "Commercial readiness only; no active billing.",
    nextActions: ["Keep Pro/VIP as planned unless entitlement exists."],
    founderDecisionNeeded: true,
    reportCadence: "weekly",
  },
  {
    ministryId: "media_communications",
    ministryName: "Media & Communications",
    leaderTitle: "Media Office Director",
    status: "blocked",
    confidence: "high",
    riskLevel: "high",
    automationLevel: "founder_approval",
    summary: "Prepares content systems; external publishing is blocked until configured and approved.",
    keyMetrics: ["publishing_blocked", "no_social_tokens"],
    activeWork: ["content calendar", "media claims policy", "AI video studio plan"],
    blockers: ["no connected social accounts", "no publishing approval UI"],
    incidents: [],
    pendingApprovals: ["future content drafts"],
    guardianFlags: ["block spam and misleading urgency"],
    legalFlags: ["block performance claims"],
    engineeringFlags: ["do not add social tokens"],
    citizenImpact: "No external public claim is made from the product.",
    revenueImpactLater: "Marketing readiness only; no campaign metrics claimed.",
    nextActions: ["Keep drafts internal until Guardian, Legal, and Founder review exist."],
    founderDecisionNeeded: true,
    reportCadence: "event_driven",
  },
  {
    ministryId: "academy_education",
    ministryName: "Academy & Education",
    leaderTitle: "Academy Director",
    status: "ready",
    confidence: "medium",
    riskLevel: "low",
    automationLevel: "auto",
    summary: "Defines safe education, glossary, paper training, and coach language.",
    keyMetrics: ["education_only", "paper_training_first"],
    activeWork: ["academy roadmap", "coach safety model"],
    blockers: ["full lesson library not shipped"],
    incidents: [],
    pendingApprovals: [],
    guardianFlags: ["avoid manipulative prompts"],
    legalFlags: ["no financial advice"],
    engineeringFlags: ["no new feature unlock"],
    citizenImpact: "Citizens get safer learning context.",
    revenueImpactLater: "No paid education claim active.",
    nextActions: ["Keep education wording bounded and non-prescriptive."],
    founderDecisionNeeded: false,
    reportCadence: "weekly",
  },
  {
    ministryId: "community_culture",
    ministryName: "Community & Culture",
    leaderTitle: "Community Steward",
    status: "planned",
    confidence: "medium",
    riskLevel: "medium",
    automationLevel: "review",
    summary: "Prepares community, support, and VIP room rules without claiming a live community.",
    keyMetrics: ["community_planned", "vip_rooms_planned"],
    activeWork: ["community architecture", "VIP private rooms policy"],
    blockers: ["community product not implemented"],
    incidents: [],
    pendingApprovals: [],
    guardianFlags: ["anti-scam", "anti-spam"],
    legalFlags: ["no fake profit screenshots"],
    engineeringFlags: ["no public social feature claim"],
    citizenImpact: "Future community rules are clear before any rollout.",
    revenueImpactLater: "VIP community value remains planned only.",
    nextActions: ["Keep rooms marked planned until implementation exists."],
    founderDecisionNeeded: false,
    reportCadence: "weekly",
  },
  {
    ministryId: "ai_iq_brain",
    ministryName: "AI / IQ / Brain",
    leaderTitle: "Brain Systems Lead",
    status: "operating",
    confidence: "medium",
    riskLevel: "medium",
    automationLevel: "review",
    summary: "Keeps assistant and intelligence surfaces bounded as decision support.",
    keyMetrics: ["operator_assist_only", "no_prediction_guarantee"],
    activeWork: ["assistant tiers", "AI/IQ wording", "market context"],
    blockers: ["advanced VIP Brain remains planned"],
    incidents: [],
    pendingApprovals: [],
    guardianFlags: ["prompt injection caution"],
    legalFlags: ["no guaranteed signals"],
    engineeringFlags: ["do not execute actions from assistant"],
    citizenImpact: "Citizens can understand state without deceptive predictions.",
    revenueImpactLater: "VIP intelligence remains planned until entitlement exists.",
    nextActions: ["Keep assistant explanations tied to platform truth."],
    founderDecisionNeeded: false,
    reportCadence: "daily",
  },
  {
    ministryId: "ops_health_reliability",
    ministryName: "Ops / Health / Reliability",
    leaderTitle: "Ops Tower Lead",
    status: "ready",
    confidence: "high",
    riskLevel: "medium",
    automationLevel: "review",
    summary: "Surfaces health, readiness, incidents, recovery, and deployment blockers.",
    keyMetrics: ["health_routes_available", "production_not_claimed"],
    activeWork: ["health endpoint", "diagnostics probes", "ops runbooks"],
    blockers: ["external monitoring unconfigured", "production deployment blocked"],
    incidents: [],
    pendingApprovals: [],
    guardianFlags: ["do not expose secrets"],
    legalFlags: ["no production-ready claim without validation"],
    engineeringFlags: ["route checks stay current"],
    citizenImpact: "Operational truth is visible and stable.",
    revenueImpactLater: "No launch impact until external requirements exist.",
    nextActions: ["Keep missing external requirements explicit."],
    founderDecisionNeeded: false,
    reportCadence: "daily",
  },
  {
    ministryId: "markets_trading",
    ministryName: "Markets & Trading",
    leaderTitle: "Market District Operator",
    status: "operating",
    confidence: "high",
    riskLevel: "high",
    automationLevel: "review",
    summary: "Owns chart, market context, paper ticket, and blocked live execution truth.",
    keyMetrics: ["fallback_market_active", "paper_only_execution"],
    activeWork: ["workstation", "chart visual layer", "paper execution ticket"],
    blockers: ["live broker/feed activation unconfigured"],
    incidents: [],
    pendingApprovals: ["future broker/feed pilot"],
    guardianFlags: ["block execution bypass"],
    legalFlags: ["no live trading claim"],
    engineeringFlags: ["preserve market fallback stability"],
    citizenImpact: "Citizens see chart-first paper trading truth.",
    revenueImpactLater: "Trading monetization remains inactive.",
    nextActions: ["Keep fallback and blocked states compact and visible."],
    founderDecisionNeeded: false,
    reportCadence: "daily",
  },
  {
    ministryId: "platforms_devices",
    ministryName: "Platforms & Devices",
    leaderTitle: "Device Platform Lead",
    status: "planned",
    confidence: "medium",
    riskLevel: "medium",
    automationLevel: "review",
    summary: "Prepares web-to-desktop/mobile readiness without shipping native apps.",
    keyMetrics: ["web_active", "native_apps_not_shipped"],
    activeWork: ["desktop readiness docs", "mobile readiness docs"],
    blockers: ["installers and app-store packages not built"],
    incidents: [],
    pendingApprovals: ["future desktop/mobile build path"],
    guardianFlags: ["protect session bridging"],
    legalFlags: ["no native app release claim"],
    engineeringFlags: ["no fake installer assets"],
    citizenImpact: "Web remains the active product surface.",
    revenueImpactLater: "No paid mobile or desktop claim.",
    nextActions: ["Keep native app readiness separate from shipped product truth."],
    founderDecisionNeeded: false,
    reportCadence: "weekly",
  },
  {
    ministryId: "account_types_special_programs",
    ministryName: "Account Types & Special Programs",
    leaderTitle: "Account Program Steward",
    status: "ready",
    confidence: "medium",
    riskLevel: "high",
    automationLevel: "founder_approval",
    summary: "Keeps Standard and Islamic status truthful, with review required and not certified by default.",
    keyMetrics: ["standard_active", "islamic_not_certified_by_default"],
    activeWork: ["account type identity", "Islamic disclaimer"],
    blockers: ["external Sharia review not claimed"],
    incidents: [],
    pendingApprovals: ["future reviewed Islamic wording"],
    guardianFlags: ["prevent false certification"],
    legalFlags: ["Sharia certification not claimed"],
    engineeringFlags: ["keep account status visible"],
    citizenImpact: "Citizens see account type truth without certification claims.",
    revenueImpactLater: "No special program monetization active.",
    nextActions: ["Keep Islamic status as not certified unless genuinely reviewed."],
    founderDecisionNeeded: false,
    reportCadence: "weekly",
  },
  {
    ministryId: "records_audit_journal",
    ministryName: "Records / Audit / Journal",
    leaderTitle: "Records Officer",
    status: "ready",
    confidence: "medium",
    riskLevel: "medium",
    automationLevel: "review",
    summary: "Organizes audit, journal, and future decision replay without exposing private records.",
    keyMetrics: ["audit_required_for_sensitive_actions", "journal_planned"],
    activeWork: ["audit semantics", "journal roadmap"],
    blockers: ["advanced journal analytics not shipped"],
    incidents: [],
    pendingApprovals: [],
    guardianFlags: ["protect record privacy"],
    legalFlags: ["avoid performance guarantee interpretation"],
    engineeringFlags: ["do not expose private data"],
    citizenImpact: "Records stay purposeful and privacy-conscious.",
    revenueImpactLater: "Advanced analytics remain planned.",
    nextActions: ["Keep audit and journal surfaces non-invasive."],
    founderDecisionNeeded: false,
    reportCadence: "weekly",
  },
  {
    ministryId: "emergency_incident",
    ministryName: "Emergency & Incident",
    leaderTitle: "Incident Commander",
    status: "ready",
    confidence: "medium",
    riskLevel: "high",
    automationLevel: "review",
    summary: "Defines incident categories, recovery, escalation, and rollback truth.",
    keyMetrics: ["manual_recovery", "operator_guided"],
    activeWork: ["ops recovery", "runbook actions"],
    blockers: ["external paging not configured"],
    incidents: [],
    pendingApprovals: [],
    guardianFlags: ["block panic automation"],
    legalFlags: ["truthful degraded disclosure"],
    engineeringFlags: ["maintain route checks"],
    citizenImpact: "Errors and degraded states remain explainable.",
    revenueImpactLater: "No launch readiness claim.",
    nextActions: ["Keep recovery manual until monitoring exists."],
    founderDecisionNeeded: false,
    reportCadence: "event_driven",
  },
  {
    ministryId: "quality_inspection",
    ministryName: "Quality & Inspection",
    leaderTitle: "Quality Inspector",
    status: "operating",
    confidence: "high",
    riskLevel: "medium",
    automationLevel: "review",
    summary: "Enforces validation, visual acceptance, product truth, and regression discipline.",
    keyMetrics: ["tsc_required", "build_required", "regression_required"],
    activeWork: ["validated baseline", "route smoke", "visual proof discipline"],
    blockers: ["manual visual review still required for subjective score"],
    incidents: [],
    pendingApprovals: [],
    guardianFlags: ["watch truth regressions"],
    legalFlags: ["do not accept deceptive wording"],
    engineeringFlags: ["run lint/build/test before commit"],
    citizenImpact: "Citizens benefit from stable, coherent product surfaces.",
    revenueImpactLater: "No quality-to-revenue claim.",
    nextActions: ["Keep tests aligned with new internal contracts."],
    founderDecisionNeeded: false,
    reportCadence: "daily",
  },
  {
    ministryId: "rights_brand_ip",
    ministryName: "Rights / Brand / IP",
    leaderTitle: "Rights & Brand Officer",
    status: "ready",
    confidence: "medium",
    riskLevel: "medium",
    automationLevel: "review",
    summary: "Protects logo, brand identity, anti-copying rules, and asset usage readiness.",
    keyMetrics: ["brand_assets_documented", "no_trademark_registration_claim"],
    activeWork: ["brand identity", "brand assets", "rights policy"],
    blockers: ["trademark registration not claimed"],
    incidents: [],
    pendingApprovals: ["future public launch materials"],
    guardianFlags: ["avoid competitor copying"],
    legalFlags: ["do not claim registered marks unless real"],
    engineeringFlags: ["keep SVG assets source-controlled"],
    citizenImpact: "Brand remains coherent and trustworthy.",
    revenueImpactLater: "Supports future commercial readiness only.",
    nextActions: ["Keep brand rules attached to all future media work."],
    founderDecisionNeeded: false,
    reportCadence: "weekly",
  },
];

function buildMinistryReports(checkedAt: string): MinistryReport[] {
  const detailedReports: MinistryReport[] = MINISTRY_DEFINITIONS.map((definition) => ({
    ...definition,
    coordination: getMinistryCoordinationReadinessFor(definition.ministryName),
    productTruth: { ...PRODUCT_TRUTH },
    reportDestination: "Founder Command Room" as const,
    lastUpdated: checkedAt,
  }));
  const detailedIds = new Set(detailedReports.map((report) => report.ministryId));
  const hierarchyReports: MinistryReport[] = PLANET_40_MINISTRIES.filter(
    (ministry) => !detailedIds.has(ministry.id)
  ).map((ministry) => ({
    ministryId: ministry.id,
    ministryName: ministry.officialName,
    leaderTitle: ministry.leaderTitle,
    status:
      ministry.readiness === "active"
        ? "operating"
        : ministry.readiness === "blocked"
        ? "blocked"
        : ministry.readiness === "planned"
        ? "planned"
        : "ready",
    confidence: ministry.readiness === "active" ? "high" : "medium",
    riskLevel: ministry.riskLevel,
    automationLevel: ministry.automationLevel,
    summary: ministry.purpose,
    keyMetrics: [
      `continent=${ministry.continent}`,
      `state=${ministry.state}`,
      `readiness=${ministry.readiness}`,
    ],
    activeWork:
      ministry.readiness === "active"
        ? ministry.responsibilities.slice(0, 2)
        : ["architecture readiness", "deterministic reporting"],
    blockers: ministry.blockers,
    incidents: [],
    pendingApprovals:
      ministry.automationLevel === "founder_approval"
        ? ["future sensitive action approval"]
        : [],
    guardianFlags: ministry.guardianBoundaries,
    legalFlags: ministry.legalBoundaries,
    engineeringFlags: ["no fake activation", "keep contract deterministic"],
    citizenImpact: ministry.citizenFacingValue,
    revenueImpactLater: "No revenue, billing, subscription, or performance-fee activation is active.",
    nextActions: ministry.nextActions,
    founderDecisionNeeded: ministry.automationLevel === "founder_approval",
    coordination: getMinistryCoordinationReadinessFor(ministry.officialName),
    productTruth: { ...PRODUCT_TRUTH },
    reportDestination: "Founder Command Room",
    lastUpdated: checkedAt,
    reportCadence: "weekly",
  }));

  return [...detailedReports, ...hierarchyReports];
}

function buildMinistryCatalog(reports: MinistryReport[]): PlanetMinistry[] {
  return reports.map((report) => ({
    id: report.ministryId,
    name: report.ministryName,
    leaderTitle: report.leaderTitle,
    purpose: report.summary,
    status: report.status,
    riskLevel: report.riskLevel,
    automationLevel: report.automationLevel,
    controlledModules: report.keyMetrics,
    activeWork: report.activeWork,
    blockers: report.blockers,
    reportDestination: "Founder Command Room",
    productTruth: [
      `liveExecution=${report.productTruth.liveExecution}`,
      `realMoneyRouting=${report.productTruth.realMoneyRouting}`,
      `billing=${report.productTruth.billing}`,
      `publicLaunch=${report.productTruth.publicLaunch}`,
    ],
  }));
}

function buildFounderBriefing(
  checkedAt: string,
  reports: MinistryReport[]
): FounderBriefing {
  const blockedOrDegraded = reports
    .filter((report) => report.status === "blocked" || report.status === "degraded")
    .map((report) => report.ministryName);
  const operating = reports
    .filter((report) => report.status === "operating" || report.status === "ready")
    .map((report) => report.ministryName);
  const founderDecisions = reports
    .filter((report) => report.founderDecisionNeeded)
    .map((report) => report.ministryName);

  return {
    checkedAt,
    planetStatus: blockedOrDegraded.length > 0 ? "degraded" : "operating",
    topRisks: [
      "Do not claim public launch, production deployment, or active billing.",
      "Do not activate broker/feed, live execution, or real-money routing.",
      "Keep Founder Command private until owner-only desktop/mobile access exists.",
    ],
    operatingMinistries: operating,
    operatingNormally: operating,
    blockedMinistries: blockedOrDegraded,
    blockedOrDegraded,
    approvalsNeeded: founderDecisions,
    guardianAlerts: [
      "Live execution and real-money routing are blocked.",
      "External publishing and social account connection are blocked.",
    ],
    legalWarnings: [
      "No guaranteed profit, win-rate, risk-free, legal-advice, or Sharia certification claims.",
      "Founder approval cannot override critical Guardian/Legal blocks without remediation.",
    ],
    mediaQueueReadiness: [
      "Media Office is documented only.",
      "No external publishing tokens or connected accounts exist.",
    ],
    engineeringTasks: [
      "Keep Planet OS runtime contracts deterministic.",
      "Keep diagnostics compact and non-public-command oriented.",
      "Run full validation before committing product truth changes.",
    ],
    productGaps: [
      "Native Founder Command apps are not shipped.",
      "External monitoring, production deployment, billing, and integrations remain unconfigured.",
      "Community, Academy depth, and VIP rooms remain planned product surfaces.",
    ],
    proVipReadiness: [
      "Pro and VIP are roadmap/identity states only.",
      "No paid entitlement or premium access is active by default.",
    ],
    pendingApprovals: founderDecisions,
    recommendedDecisions: [
      "Use Planet OS for internal reporting only.",
      "Keep public product surfaces focused on paper-safe trading truth.",
    ],
    nextSafeActions: [
      "Review ministry blockers from diagnostics.",
      "Keep future command app owner-only and read-only by default.",
      "Preserve blocked/inactive states until real external values and approvals exist.",
    ],
    whatNotToDoToday: [
      "Do not launch.",
      "Do not expose secrets.",
      "Do not publish media externally.",
      "Do not turn planned systems into active claims.",
      "Do not enable live execution, broker/feed activation, billing, or real money.",
    ],
  };
}

export function getPlanetMinistryReports(
  checkedAt = new Date().toISOString()
): MinistryReport[] {
  return buildMinistryReports(checkedAt);
}

export function getFounderBriefing(
  checkedAt = new Date().toISOString()
): FounderBriefing {
  return buildFounderBriefing(checkedAt, buildMinistryReports(checkedAt));
}

export function getPlanetOsStatusSnapshot(
  checkedAt = new Date().toISOString()
): PlanetStateSummary {
  const ministries = buildMinistryReports(checkedAt);
  const founderBriefing = buildFounderBriefing(checkedAt, ministries);

  return {
    checkedAt,
    model: "tpm_planet_earth_os",
    status: founderBriefing.planetStatus,
    founderCommand: {
      privateOwnerOnly: true,
      publicRouteExposed: false,
      desktopAppShipped: false,
      mobileAppShipped: false,
      reportDestination: "Founder Command Room",
    },
    continents: CONTINENTS,
    states: PLANET_STATES,
    ministries,
    ministryCatalog: buildMinistryCatalog(ministries),
    cityModules: CITY_MODULES,
    citizenClasses: CITIZEN_CLASSES,
    professions: PROFESSIONS,
    founderBriefing,
    safetyBoundaries: SAFETY_BOUNDARIES,
    truth: PRODUCT_TRUTH,
  };
}

export function getPlanetEarthStateSummary(
  checkedAt = new Date().toISOString()
): PlanetStateSummary {
  return getPlanetOsStatusSnapshot(checkedAt);
}

export function getMinistryReportContractExample(
  checkedAt = new Date().toISOString()
): MinistryReport {
  return getPlanetMinistryReports(checkedAt)[2];
}
