import "server-only";

import type { MinistryWorkflow } from "./types";

export const INTER_MINISTRY_WORKFLOWS: MinistryWorkflow[] = [
  {
    id: "media-campaign-workflow",
    name: "Media Campaign Workflow",
    path: [
      "Media Ministry",
      "Founder Presidency Coordination",
      "Legal Counsel",
      "Guardian",
      "Treasury",
      "Founder Approval",
      "Media Ministry",
    ],
    steps: [
      "Media drafts internal campaign",
      "Presidency classifies risk and routing",
      "Legal reviews claims",
      "Guardian reviews safety and abuse risk",
      "Treasury reviews Pro/VIP or monetization wording when present",
      "Founder approval is required for sensitive public claims",
      "Media receives approved-safe wording or revision request",
    ],
    currentTruth: "readiness_only",
    blockedCapabilities: ["external publishing", "social tokens", "fake metrics"],
    requiredReviews: ["Legal Counsel", "Guardian", "Founder Command Room"],
    riskLevel: "high",
    automationLevel: "founder_approval",
    blockedConditions: [
      "guaranteed profit",
      "win-rate claim",
      "fake launch",
      "fake broker/feed",
      "fake billing",
    ],
    founderDecisionPoint: "before any sensitive public campaign is scheduled later",
    productTruthProtections: [
      "social publishing inactive",
      "public launch inactive",
      "billing inactive",
    ],
    whatMustNotBeFaked: ["followers", "revenue", "published campaign", "live trading"],
    founderApprovalRequired: true,
  },
  {
    id: "vip-feature-workflow",
    name: "VIP Feature Workflow",
    path: [
      "Product / AI / Companion Ministry",
      "Founder Presidency Coordination",
      "Treasury",
      "Legal",
      "Guardian",
      "Engineering",
      "Quality",
      "Founder Approval",
    ],
    steps: [
      "Product or AI ministry proposes VIP capability",
      "Presidency checks entitlement, billing, safety, and claim risk",
      "Treasury reviews plan/economy truth",
      "Legal reviews paid and capability wording",
      "Guardian reviews bypass and abuse risk",
      "Engineering scopes implementation",
      "Quality defines acceptance",
      "Founder reviews sensitive direction",
    ],
    currentTruth: "readiness_only",
    blockedCapabilities: ["billing activation", "fake VIP access", "premium guarantees"],
    requiredReviews: ["Treasury", "Legal", "Guardian", "Engineering", "Quality"],
    riskLevel: "high",
    automationLevel: "founder_approval",
    blockedConditions: ["fake VIP active", "billing implied", "guaranteed signal"],
    founderDecisionPoint: "before VIP claim or entitlement activation later",
    productTruthProtections: ["VIP planned", "billing inactive", "no paid access faked"],
    whatMustNotBeFaked: ["VIP activation", "paid entitlement", "VIP guarantee"],
    founderApprovalRequired: true,
  },
  {
    id: "security-incident-workflow",
    name: "Security Incident Workflow",
    path: [
      "Guardian Ministry",
      "Founder Presidency Coordination",
      "Emergency Ministry",
      "Engineering",
      "Legal",
      "Founder Command",
    ],
    steps: [
      "Guardian classifies incident severity",
      "Presidency routes emergency dependencies",
      "Emergency ministry coordinates response readiness",
      "Engineering reviews technical containment",
      "Legal reviews user/public wording if needed",
      "Founder Command receives critical status",
    ],
    currentTruth: "architecture_only",
    blockedCapabilities: ["invasive surveillance", "silent secret exposure"],
    requiredReviews: ["Guardian", "Emergency", "Engineering", "Legal"],
    riskLevel: "critical",
    automationLevel: "review",
    blockedConditions: ["private data exposure", "secret exposure", "unsafe silent action"],
    founderDecisionPoint: "for high/critical incident direction later",
    productTruthProtections: ["no private data leaked", "no secret exposure"],
    whatMustNotBeFaked: ["incident count", "resolved incident", "security certification"],
    founderApprovalRequired: true,
  },
  {
    id: "islamic-wording-workflow",
    name: "Islamic Account Wording Workflow",
    path: [
      "Account Types Ministry",
      "Founder Presidency Coordination",
      "Legal Counsel",
      "Rights & Brand",
      "Founder Approval",
    ],
    steps: [
      "Account Types drafts wording",
      "Presidency flags certification risk",
      "Legal reviews no-certification wording",
      "Rights & Brand checks respectful brand use",
      "Founder approves final direction later",
    ],
    currentTruth: "readiness_only",
    blockedCapabilities: ["fake Sharia certification", "unreviewed Islamic claims"],
    requiredReviews: ["Legal Counsel", "Rights & Brand", "Founder Command Room"],
    riskLevel: "high",
    automationLevel: "founder_approval",
    blockedConditions: ["Sharia certified claim", "Islamic compliance claim without proof"],
    founderDecisionPoint: "before any sensitive Islamic wording becomes public later",
    productTruthProtections: ["Islamic/Sharia not certified by default"],
    whatMustNotBeFaked: ["Sharia certification", "religious/legal approval"],
    founderApprovalRequired: true,
  },
  {
    id: "sponsored-clock-workflow",
    name: "Sponsored Swiss Clock Partnership Workflow",
    path: [
      "Partnerships / Treasury",
      "Founder Presidency Coordination",
      "Legal",
      "Rights & Brand",
      "Media",
      "Founder Approval",
    ],
    steps: [
      "Partnerships drafts sponsor concept",
      "Presidency checks brand and Swiss status risk",
      "Legal reviews contract needs",
      "Rights & Brand reviews asset usage",
      "Media reviews public wording",
      "Founder approves or blocks direction later",
    ],
    currentTruth: "architecture_only",
    blockedCapabilities: ["fake Swiss company status", "uncontracted brand/company use"],
    requiredReviews: ["Legal", "Rights & Brand", "Media", "Founder Command Room"],
    riskLevel: "high",
    automationLevel: "founder_approval",
    blockedConditions: ["company name without contract", "Swiss legal status claim"],
    founderDecisionPoint: "before any sponsored Swiss precision claim later",
    productTruthProtections: ["Swiss-inspired only", "no company/legal status claim"],
    whatMustNotBeFaked: ["sponsor", "contract", "Swiss registration"],
    founderApprovalRequired: true,
  },
  {
    id: "production-activation-workflow",
    name: "Production Activation Workflow",
    path: [
      "Ops",
      "Founder Presidency Coordination",
      "Engineering",
      "Guardian",
      "Legal",
      "Founder Approval",
    ],
    steps: [
      "Ops raises readiness request",
      "Presidency classifies as blocked in current phase",
      "Engineering, Guardian, and Legal requirements are listed",
      "Founder sees blocker list",
      "No production activation occurs",
    ],
    currentTruth: "blocked_until_future_stage",
    blockedCapabilities: ["production deployment", "live execution", "billing", "broker/feed"],
    requiredReviews: ["Ops", "Engineering", "Guardian", "Legal", "Founder Command Room"],
    riskLevel: "critical",
    automationLevel: "blocked",
    blockedConditions: ["current phase forbids production", "secrets not configured in Git"],
    founderDecisionPoint: "future explicit production phase only",
    productTruthProtections: [
      "production readiness blocked",
      "public launch inactive",
      "secrets not exposed",
    ],
    whatMustNotBeFaked: ["production ready", "public launch", "secret rotation complete"],
    founderApprovalRequired: true,
  },
  {
    id: "companion-response-policy-workflow",
    name: "Companion Response Policy Workflow",
    path: [
      "Companion Ministry",
      "Founder Presidency Coordination",
      "Legal",
      "Guardian",
      "AI Brain",
      "Quality",
      "Founder if sensitive",
    ],
    steps: [
      "Companion proposes response policy",
      "Presidency routes claim and safety review",
      "Legal checks advice/claims language",
      "Guardian checks misuse and bypass risk",
      "AI Brain checks context limits",
      "Quality validates copy and behavior",
    ],
    currentTruth: "readiness_only",
    blockedCapabilities: ["trade execution", "profit claim", "auth bypass"],
    requiredReviews: ["Legal", "Guardian", "AI Brain", "Quality"],
    riskLevel: "medium",
    automationLevel: "review",
    blockedConditions: ["financial advice", "guaranteed signal", "enable live request"],
    founderDecisionPoint: "only for sensitive assistant capabilities later",
    productTruthProtections: ["assistant cannot execute trades", "AI certainty claims blocked"],
    whatMustNotBeFaked: ["predictive certainty", "execution authority", "broker activation"],
    founderApprovalRequired: false,
  },
  {
    id: "community-moderation-workflow",
    name: "Community Moderation Workflow",
    path: [
      "Community Ministry",
      "Founder Presidency Coordination",
      "Guardian",
      "Legal if claims/abuse",
      "Support",
      "Founder if high-risk",
    ],
    steps: [
      "Community reports moderation concern",
      "Presidency classifies abuse/claim/legal risk",
      "Guardian reviews scams, harassment, and manipulation",
      "Legal reviews claims/illegal content when needed",
      "Support prepares user-safe response",
    ],
    currentTruth: "architecture_only",
    blockedCapabilities: ["signal selling", "fake profit screenshots", "impersonation"],
    requiredReviews: ["Guardian", "Support"],
    riskLevel: "medium",
    automationLevel: "review",
    blockedConditions: ["scam", "harassment", "guaranteed signal sale"],
    founderDecisionPoint: "high-risk moderation only",
    productTruthProtections: ["no fake community activity", "no deceptive strategy selling"],
    whatMustNotBeFaked: ["community scale", "profit screenshots", "moderation resolution"],
    founderApprovalRequired: false,
  },
  {
    id: "journal-coach-feature-workflow",
    name: "Journal/Coach Feature Workflow",
    path: [
      "Coach / Journal Ministry",
      "Founder Presidency Coordination",
      "Legal",
      "Guardian",
      "AI Brain",
      "Quality",
    ],
    steps: [
      "Coach/Journal proposes prompt or replay surface",
      "Presidency checks advice and pressure risk",
      "Legal reviews no-financial-advice wording",
      "Guardian reviews manipulation/gambling prompts",
      "AI Brain checks context quality",
      "Quality verifies safe UX",
    ],
    currentTruth: "readiness_only",
    blockedCapabilities: ["profit coaching", "gambling-style prompts"],
    requiredReviews: ["Legal", "Guardian", "AI Brain", "Quality"],
    riskLevel: "medium",
    automationLevel: "review",
    blockedConditions: ["profit promise", "overtrading pressure", "financial advice"],
    founderDecisionPoint: "only for premium coaching claims later",
    productTruthProtections: ["coach is educational", "decision replay is not outcome certainty"],
    whatMustNotBeFaked: ["performance guarantee", "alternative outcome certainty"],
    founderApprovalRequired: false,
  },
  {
    id: "plan-entitlement-change-workflow",
    name: "Plan Entitlement Change Workflow",
    path: [
      "Treasury / Plans",
      "Founder Presidency Coordination",
      "Legal",
      "Guardian",
      "Engineering",
      "Founder Approval",
    ],
    steps: [
      "Treasury/Plans proposes entitlement change",
      "Presidency checks billing and plan truth",
      "Legal reviews commercial wording",
      "Guardian checks bypass risk",
      "Engineering scopes entitlement logic",
      "Founder approves sensitive direction later",
    ],
    currentTruth: "readiness_only",
    blockedCapabilities: ["billing activation", "fake paid access", "performance-fee exposure"],
    requiredReviews: ["Legal", "Guardian", "Engineering", "Founder Command Room"],
    riskLevel: "high",
    automationLevel: "founder_approval",
    blockedConditions: ["billing implied", "VIP active without entitlement"],
    founderDecisionPoint: "before any paid entitlement change later",
    productTruthProtections: ["billing inactive", "Pro/VIP planned", "performance fee hidden"],
    whatMustNotBeFaked: ["paid access", "VIP active", "performance-fee activation"],
    founderApprovalRequired: true,
  },
];

export function getInterMinistryWorkflowSnapshot(
  checkedAt = new Date().toISOString()
) {
  return {
    checkedAt,
    mode: "inter_ministry_workflow_templates",
    workflows: INTER_MINISTRY_WORKFLOWS,
    summary: {
      workflows: INTER_MINISTRY_WORKFLOWS.length,
      blockedWorkflows: INTER_MINISTRY_WORKFLOWS.filter(
        (workflow) => workflow.currentTruth === "blocked_until_future_stage"
      ).length,
      founderApprovalWorkflows: INTER_MINISTRY_WORKFLOWS.filter(
        (workflow) => workflow.founderApprovalRequired
      ).length,
      externalExecutionActive: false,
      publicLaunchActive: false,
      socialPublishingActive: false,
    },
  };
}
