import "server-only";

import type { BrandIdentityState, BrandStateLanguage } from "./types";

const allPublicSurfaces = [
  "public_entry",
  "workstation",
  "settings",
  "diagnostics",
  "assistant",
  "journal_coach",
  "academy",
  "community",
  "media_office",
  "mobile_future",
  "desktop_future",
] as const;

export const BRAND_STATE_LANGUAGE: Record<BrandIdentityState, BrandStateLanguage> = {
  ready: {
    state: "ready",
    label: "Ready",
    userCopyStyle: "calm readiness; no launch claim",
    visualTone: "stable premium accent",
    markBehavior: "ready",
    colorRole: "aqua/neutral",
    urgency: "calm",
    allowedSurfaces: [...allPublicSurfaces, "founder_command", "local_command"],
    forbiddenClaims: ["production ready", "launch ready"],
    assistantWordingRule: "Explain readiness as local/platform readiness only.",
    founderInternalWordingRule: "May mention internal readiness gates.",
  },
  paper_safe: {
    state: "paper_safe",
    label: "Paper-safe",
    userCopyStyle: "trustworthy and reassuring",
    visualTone: "stable cyan/neutral",
    markBehavior: "paper_safe",
    colorRole: "paper-safe accent",
    urgency: "calm",
    allowedSurfaces: [...allPublicSurfaces],
    forbiddenClaims: ["live execution active", "real-money routing active"],
    assistantWordingRule: "Explain paper mode as bounded learning, not advice.",
    founderInternalWordingRule: "May mention current paper-only safety posture.",
  },
  local_only: {
    state: "local_only",
    label: "Local only",
    userCopyStyle: "closed local operation; never launch wording",
    visualTone: "contained gold pulse",
    markBehavior: "local_only",
    colorRole: "local readiness accent",
    urgency: "normal",
    allowedSurfaces: ["settings", "diagnostics", "founder_command", "local_command"],
    forbiddenClaims: ["public launch active", "production active"],
    assistantWordingRule: "Explain local-only without public launch implication.",
    founderInternalWordingRule: "May mention Local Universe operations.",
  },
  fallback: {
    state: "fallback",
    label: "Fallback",
    userCopyStyle: "bounded and honest",
    visualTone: "slower blue readiness",
    markBehavior: "fallback",
    colorRole: "fallback blue",
    urgency: "normal",
    allowedSurfaces: [...allPublicSurfaces],
    forbiddenClaims: ["live feed active", "broker feed active"],
    assistantWordingRule: "Explain fallback as simulated/local context.",
    founderInternalWordingRule: "May mention fallback architecture.",
  },
  blocked: {
    state: "blocked",
    label: "Blocked",
    userCopyStyle: "firm but not broken",
    visualTone: "steady Swiss red point; muted orbit",
    markBehavior: "blocked",
    colorRole: "blocked red",
    urgency: "blocked",
    allowedSurfaces: [...allPublicSurfaces, "founder_command", "local_command"],
    forbiddenClaims: ["can bypass", "active capability"],
    assistantWordingRule: "Explain why blocked and offer safe alternatives.",
    founderInternalWordingRule: "May include blocked category and required review.",
  },
  review_required: {
    state: "review_required",
    label: "Review required",
    userCopyStyle: "calm review language",
    visualTone: "segmented gold orbit",
    markBehavior: "review_required",
    colorRole: "review gold",
    urgency: "review",
    allowedSurfaces: ["settings", "diagnostics", "assistant", "founder_command", "local_command"],
    forbiddenClaims: ["approved", "certified", "activated"],
    assistantWordingRule: "Say review is required before claims or activation.",
    founderInternalWordingRule: "May name required internal review path.",
  },
  degraded: {
    state: "degraded",
    label: "Degraded",
    userCopyStyle: "non-scary reduced confidence",
    visualTone: "muted violet/neutral",
    markBehavior: "degraded",
    colorRole: "degraded violet",
    urgency: "review",
    allowedSurfaces: [...allPublicSurfaces, "founder_command", "local_command"],
    forbiddenClaims: ["fully operational"],
    assistantWordingRule: "Explain degraded state as lower confidence, not failure.",
    founderInternalWordingRule: "May mention remediation path.",
  },
  inactive: {
    state: "inactive",
    label: "Inactive",
    userCopyStyle: "not active today; not failed",
    visualTone: "muted static",
    markBehavior: "inactive",
    colorRole: "muted neutral",
    urgency: "calm",
    allowedSurfaces: [...allPublicSurfaces, "founder_command", "local_command"],
    forbiddenClaims: ["active", "enabled"],
    assistantWordingRule: "Say inactive means not enabled in this product state.",
    founderInternalWordingRule: "May mention future activation prerequisites.",
  },
  planned: {
    state: "planned",
    label: "Planned",
    userCopyStyle: "future/planned, never active",
    visualTone: "muted static premium",
    markBehavior: "planned",
    colorRole: "planned neutral",
    urgency: "calm",
    allowedSurfaces: [...allPublicSurfaces, "founder_command", "local_command"],
    forbiddenClaims: ["available now", "activated"],
    assistantWordingRule: "Use planned/locked language.",
    founderInternalWordingRule: "May mention roadmap and approval dependencies.",
  },
  future: {
    state: "future",
    label: "Future",
    userCopyStyle: "future only",
    visualTone: "muted formal",
    markBehavior: "planned",
    colorRole: "future neutral",
    urgency: "calm",
    allowedSurfaces: [...allPublicSurfaces],
    forbiddenClaims: ["shipped", "active"],
    assistantWordingRule: "Say future, not current.",
    founderInternalWordingRule: "May mention future planning.",
  },
  not_certified: {
    state: "not_certified",
    label: "Not certified",
    userCopyStyle: "clear, calm, no alarm",
    visualTone: "neutral review",
    markBehavior: "review_required",
    colorRole: "review neutral",
    urgency: "review",
    allowedSurfaces: ["settings", "diagnostics", "assistant", "founder_command"],
    forbiddenClaims: ["Islamic/Sharia certified", "officially certified"],
    assistantWordingRule: "Do not claim certification; explain review state.",
    founderInternalWordingRule: "May mention certification gap and review route.",
  },
};

export function getBrandStateLanguage(
  state: BrandIdentityState
): BrandStateLanguage {
  return BRAND_STATE_LANGUAGE[state] ?? BRAND_STATE_LANGUAGE.ready;
}

export function getBrandStateLanguageSnapshot(): BrandStateLanguage[] {
  return Object.values(BRAND_STATE_LANGUAGE);
}
