import "server-only";

import type {
  InvisibleOperatingLayerSnapshot,
  InvisibleOperatingLayerSystem,
} from "./types";
import { mapInvisibleSystemsToPublicOutputs } from "./output-mapper";

const systems: InvisibleOperatingLayerSystem[] = [
  {
    key: "product_truth",
    privateLabel: "Product Truth",
    publicLabel: "Readiness",
    publicOutput: "Paper-safe now; live, billing, broker/feed, and public launch stay inactive.",
    status: "ready",
    visibleToPublicUsers: true,
    visibleToFounder: true,
    notes: "The truth layer protects public claims and internal decisions.",
  },
  {
    key: "plan_entitlements",
    privateLabel: "Plan Entitlements",
    publicLabel: "Plans",
    publicOutput: "Free is available; Pro, VIP, and Institutional remain planned or future.",
    status: "readiness_only",
    visibleToPublicUsers: true,
    visibleToFounder: true,
    notes: "No paid activation or hidden entitlement is implied.",
  },
  {
    key: "tpm_assistant_context",
    privateLabel: "TPM Assistant Context",
    publicLabel: "TPM Assistant",
    publicOutput: "Guidance is paper-safe, bounded, and non-predictive.",
    status: "ready",
    visibleToPublicUsers: true,
    visibleToFounder: true,
    notes: "Assistant context may explain states but cannot execute.",
  },
  {
    key: "why_blocked",
    privateLabel: "Why Blocked",
    publicLabel: "Why Blocked",
    publicOutput: "Blocked, inactive, planned, and future states are explained clearly.",
    status: "ready",
    visibleToPublicUsers: true,
    visibleToFounder: true,
    notes: "Users get simple reasons instead of internal gate names.",
  },
  {
    key: "guardian",
    privateLabel: "Guardian",
    publicLabel: "Safety",
    publicOutput: "Claims, risky actions, and unsafe activation stay reviewed or blocked.",
    status: "ready",
    visibleToPublicUsers: true,
    visibleToFounder: true,
    notes: "Guardian names remain internal; public users see safety language.",
  },
  {
    key: "legal",
    privateLabel: "Legal",
    publicLabel: "Claim review",
    publicOutput: "No legal, company, certification, or performance status is faked.",
    status: "ready",
    visibleToPublicUsers: true,
    visibleToFounder: true,
    notes: "Legal review is internal; public copy stays truthful.",
  },
  {
    key: "trust_governor",
    privateLabel: "Trust Governor",
    publicLabel: "Trust",
    publicOutput: "Diagnostics and readiness labels avoid fake metrics or fake users.",
    status: "ready",
    visibleToPublicUsers: true,
    visibleToFounder: true,
    notes: "Trust rules constrain public claims.",
  },
  {
    key: "brand_intelligence",
    privateLabel: "Brand Intelligence",
    publicLabel: "Visual readiness",
    publicOutput: "The code-only Earth identity adapts by plan and surface.",
    status: "ready",
    visibleToPublicUsers: true,
    visibleToFounder: true,
    notes: "No raster images or external map assets are used.",
  },
  {
    key: "product_memory",
    privateLabel: "Product Memory",
    publicLabel: null,
    publicOutput: null,
    status: "hidden",
    visibleToPublicUsers: false,
    visibleToFounder: true,
    notes: "Founder/internal memory is not exposed; users may only see local Journal truth where relevant.",
  },
  {
    key: "sovereign_autonomy",
    privateLabel: "Sovereign Autonomy",
    publicLabel: null,
    publicOutput: null,
    status: "hidden",
    visibleToPublicUsers: false,
    visibleToFounder: true,
    notes: "Founder idea/event/task governance never appears in public navigation.",
  },
  {
    key: "codex_governance",
    privateLabel: "Codex Governance",
    publicLabel: null,
    publicOutput: null,
    status: "hidden",
    visibleToPublicUsers: false,
    visibleToFounder: true,
    notes: "Codex drafts and permits are Founder-only and never executed by the web app.",
  },
  {
    key: "local_day_cycle",
    privateLabel: "Local Day Cycle",
    publicLabel: "Local readiness",
    publicOutput: "Local review can continue without public launch activation.",
    status: "readiness_only",
    visibleToPublicUsers: true,
    visibleToFounder: true,
    notes: "Public output stays simple while Founder Command sees the full loop.",
  },
  {
    key: "diagnostics",
    privateLabel: "Diagnostics",
    publicLabel: "Diagnostics",
    publicOutput: "System readiness is visible without internal control details.",
    status: "ready",
    visibleToPublicUsers: true,
    visibleToFounder: true,
    notes: "Diagnostics sanitizes internal terminology.",
  },
  {
    key: "world_interface",
    privateLabel: "World Interface",
    publicLabel: "Support readiness",
    publicOutput: "Support paths are readiness-only until real backend channels exist.",
    status: "readiness_only",
    visibleToPublicUsers: true,
    visibleToFounder: true,
    notes: "No external sending or social publishing is active.",
  },
  {
    key: "security_sovereignty",
    privateLabel: "Security Sovereignty",
    publicLabel: null,
    publicOutput: null,
    status: "hidden",
    visibleToPublicUsers: false,
    visibleToFounder: true,
    notes: "Private security control terminology never appears in public surfaces.",
  },
  {
    key: "secrets_authority",
    privateLabel: "Secrets Authority",
    publicLabel: null,
    publicOutput: null,
    status: "hidden",
    visibleToPublicUsers: false,
    visibleToFounder: true,
    notes: "Secret categories are status-only privately and never expose raw values.",
  },
];

export function getInvisibleOperatingLayerSnapshot(
  checkedAt = new Date().toISOString()
): InvisibleOperatingLayerSnapshot {
  return {
    checkedAt,
    mode: "invisible_operating_intelligence_map",
    systems,
    publicSafeOutputs: mapInvisibleSystemsToPublicOutputs(systems),
    hiddenFromPublic: systems
      .filter((system) => !system.visibleToPublicUsers)
      .map((system) => system.key),
    founderVisibleSystems: systems
      .filter((system) => system.visibleToFounder)
      .map((system) => system.key),
    truth: {
      publicInternalTerminologyLeakAllowed: false,
      secretsVisibleToPublic: false,
      preciseLocationTracking: false,
      externalCalls: false,
      shellExecution: false,
      liveExecution: false,
      realMoney: false,
      brokerFeed: false,
      billing: false,
      socialPublishing: false,
    },
  };
}
