import type { AlkonWorldSeed, GenesisGateId } from "./types";

export const ALL_GENESIS_GATES: GenesisGateId[] = [
  "meaning_gate",
  "human_need_gate",
  "market_gate",
  "law_gate",
  "treasury_gate",
  "security_gate",
  "prototype_gate",
  "proof_gate",
  "prime_world_protection_gate",
  "founder_gate",
  "birth_gate",
];

const defaultForbiddenScope = [
  "public page",
  "new product launch",
  "production activation",
  "billing activation",
  "payment execution",
  "broker/feed activation",
  "live execution",
  "real money",
  "social publishing",
  "external account creation",
  "secret storage",
];

export const ALKON_WORLD_SEEDS: AlkonWorldSeed[] = [
  {
    seedId: "ai_media_studio_seed",
    name: "AI Media Studio",
    category: "media_ai_studio",
    purposeHypothesis:
      "Future support for content drafts, scripts, claims review, and media readiness.",
    intendedAudience: "Founder/internal media review",
    relationshipToPrime: "supports_prime_world",
    possibleValue: "Can strengthen truthful public communication after claims gates.",
    possibleRisk: "Could create fake claims or publishing pressure if ungated.",
    requiredGates: ALL_GENESIS_GATES,
    currentStatus: "evaluating",
    allowedScopeNow: ["docs", "claims review model", "read-only readiness"],
    forbiddenScopeNow: defaultForbiddenScope,
    nextSafeAction: "Keep as media readiness only and pass Media Claims Gate.",
    publicVisible: false,
    founderVisible: true,
    requiresMediaClaims: true,
    founderApproval: "not_requested",
  },
  {
    seedId: "academy_platform_seed",
    name: "Academy / Education Platform",
    category: "education_academy",
    purposeHypothesis:
      "Possible future expansion of learning paths and practice education.",
    intendedAudience: "Pro Max Trading learners",
    relationshipToPrime: "extends_prime_world",
    possibleValue: "Can strengthen onboarding and reduce support burden.",
    possibleRisk: "Could distract from current Academy readiness if overbuilt.",
    requiredGates: ALL_GENESIS_GATES,
    currentStatus: "prototype_allowed",
    allowedScopeNow: ["curriculum outline", "support/learning readiness"],
    forbiddenScopeNow: defaultForbiddenScope,
    nextSafeAction: "Keep as learning/support readiness until Prime World acceptance.",
    publicVisible: false,
    founderVisible: true,
    hasMarketProof: true,
    hasLegalProof: true,
    founderApproval: "approved_prototype",
  },
  {
    seedId: "treasury_ops_seed",
    name: "Treasury / Business Ops Tool",
    category: "treasury_business_ops",
    purposeHypothesis:
      "Future internal business ops tooling for invoices, budget evidence, and tax readiness.",
    intendedAudience: "Founder/internal operations",
    relationshipToPrime: "supports_prime_world",
    possibleValue: "Can improve accounting readiness and Founder oversight.",
    possibleRisk: "Could touch money, tax, or bank/card data if ungated.",
    requiredGates: ALL_GENESIS_GATES,
    currentStatus: "delayed",
    allowedScopeNow: ["readiness docs", "invoice evidence model"],
    forbiddenScopeNow: defaultForbiddenScope,
    nextSafeAction: "Keep payment execution disabled and require Treasury / Tax Gate.",
    publicVisible: false,
    founderVisible: true,
    requiresExternalSpend: true,
    hasTreasuryEstimate: false,
    founderApproval: "delayed",
  },
  {
    seedId: "alkon_pocket_universe_seed",
    name: "Alkon Pocket Universe OS",
    category: "mobile_command_tool",
    purposeHypothesis:
      "Future mobile command layer for private Founder pulse and low-risk decisions.",
    intendedAudience: "Founder private devices",
    relationshipToPrime: "shares_infrastructure",
    possibleValue: "Can improve private command continuity after security gates.",
    possibleRisk: "Could expose Alkon or command authority if public or insecure.",
    requiredGates: ALL_GENESIS_GATES,
    currentStatus: "proof_required",
    allowedScopeNow: ["private device readiness", "mock UI", "security model"],
    forbiddenScopeNow: defaultForbiddenScope,
    nextSafeAction: "Require Security / Device Gate and no public exposure.",
    publicVisible: false,
    founderVisible: true,
    requiresAlkonAccess: true,
    hasSecurityProof: false,
    founderApproval: "approved_seed_evaluation",
  },
  {
    seedId: "financial_intelligence_seed",
    name: "Financial Intelligence Product",
    category: "financial_intelligence_product",
    purposeHypothesis:
      "Possible future product line for non-executing financial intelligence after review.",
    intendedAudience: "Future reviewed audience",
    relationshipToPrime: "independent_future",
    possibleValue: "Could become a separate future line if legal and market proof exists.",
    possibleRisk: "High regulatory, claims, advice, and trust risk.",
    requiredGates: ALL_GENESIS_GATES,
    currentStatus: "delayed",
    allowedScopeNow: ["regulatory readiness note", "blocked-state doctrine"],
    forbiddenScopeNow: defaultForbiddenScope,
    nextSafeAction: "Require Legal / FINMA / Product Truth gates before any prototype beyond docs.",
    publicVisible: false,
    founderVisible: true,
    requiresRegulatoryReview: true,
    founderApproval: "not_requested",
  },
  {
    seedId: "support_helpdesk_seed",
    name: "Support / Helpdesk Platform",
    category: "support_platform",
    purposeHypothesis:
      "Future support tooling for ticket readiness, knowledge base, and response consistency.",
    intendedAudience: "Support operators and future users",
    relationshipToPrime: "supports_prime_world",
    possibleValue: "Can improve trust and reduce confusion.",
    possibleRisk: "Could imply fake support backend or collect user data before privacy gates.",
    requiredGates: ALL_GENESIS_GATES,
    currentStatus: "evaluating",
    allowedScopeNow: ["support policy", "readiness model", "knowledge base outline"],
    forbiddenScopeNow: defaultForbiddenScope,
    nextSafeAction: "Pass Privacy / Support obligation gates before collection or promises.",
    publicVisible: false,
    founderVisible: true,
    requiresUserData: true,
    founderApproval: "not_requested",
  },
  {
    seedId: "analytics_readiness_seed",
    name: "Analytics / Readiness Platform",
    category: "analytics_platform",
    purposeHypothesis:
      "Future internal analytics and readiness scoring without hidden tracking.",
    intendedAudience: "Founder/internal product review",
    relationshipToPrime: "supports_prime_world",
    possibleValue: "Can improve Product Truth and readiness audits.",
    possibleRisk: "Could become surveillance or fake metrics if ungated.",
    requiredGates: ALL_GENESIS_GATES,
    currentStatus: "evaluating",
    allowedScopeNow: ["internal metrics taxonomy", "privacy-safe readiness model"],
    forbiddenScopeNow: defaultForbiddenScope,
    nextSafeAction: "Require Data / Privacy gates and no fake user metrics.",
    publicVisible: false,
    founderVisible: true,
    requiresUserData: true,
    founderApproval: "not_requested",
  },
];
