import "server-only";
import type { AlKawnVisualMapNode } from "./types";

export const alKawnVisualMapNodes: AlKawnVisualMapNode[] = [
  {
    id: "ahmad_human",
    arabicLabel: "أحمد الإنسان",
    englishLabel: "Ahmad Human",
    layerType: "origin",
    owner: "Ahmad",
    parent: null,
    children: ["ahmad_private_devices"],
    status: "protected",
    truthSource: "manual_founder_decision",
    visibilityScope: "ahmad_only",
    executionMeaning: "Ahmad is the origin and final decision authority.",
    boundaryType: "truth_guarded",
    relationToOrigin: "origin",
    productTruthImpact: "All final decisions return to Ahmad.",
    compactExplanation: "أحمد هو الأصل.",
  },
  {
    id: "ahmad_private_devices",
    arabicLabel: "أجهزة أحمد الخاصة",
    englishLabel: "Ahmad Private Devices",
    layerType: "device",
    owner: "Ahmad",
    parent: "ahmad_human",
    children: ["al_kawn"],
    status: "private_only",
    truthSource: "product_truth",
    visibilityScope: "ahmad_only",
    executionMeaning: "Only private device context may run الكون.",
    boundaryType: "private_only",
    relationToOrigin: "direct private access layer under Ahmad",
    productTruthImpact: "Blocks public الكون exposure.",
    compactExplanation: "الكون يعمل فقط على أجهزة أحمد الخاصة.",
  },
  {
    id: "al_kawn",
    arabicLabel: "الكون",
    englishLabel: "Ahmad private electronic self",
    layerType: "root",
    owner: "Ahmad",
    parent: "ahmad_private_devices",
    children: [
      "supreme_root_constitution",
      "product_truth",
      "universe_operating_kernel",
      "existence_contract_law",
      "ahmad_digital_vault",
      "protection_core",
      "universe_one",
      "swiss_local_constitution",
      "human_interface",
      "sovereign_execution",
      "execution_court",
      "causal_execution",
      "infinity_mode",
      "operator_mode",
      "self_building",
      "pro_max_galaxy",
    ],
    status: "protected",
    truthSource: "manual_founder_decision",
    visibilityScope: "private_founder",
    executionMeaning: "Private digital existence and main project root.",
    boundaryType: "private_only",
    relationToOrigin: "Ahmad private electronic self under Ahmad devices",
    productTruthImpact: "الكون is above Pro Max and never public now.",
    compactExplanation: "الكون هو نسخة أحمد الإلكترونية الخاصة.",
  },
  {
    id: "supreme_root_constitution",
    arabicLabel: "الدستور الجذري الأعلى",
    englishLabel: "Supreme Root Constitution",
    layerType: "law",
    owner: "الكون",
    parent: "al_kawn",
    children: [],
    status: "protected",
    truthSource: "manual_founder_decision",
    visibilityScope: "private_internal",
    executionMeaning: "Root doctrine for belonging, truth, and forbidden actions.",
    boundaryType: "truth_guarded",
    relationToOrigin: "root law under الكون",
    productTruthImpact: "Prevents contradictions against the root law.",
    compactExplanation: "Root constitution defines why the system exists.",
  },
  {
    id: "product_truth",
    arabicLabel: "Product Truth",
    englishLabel: "Product Truth",
    layerType: "law",
    owner: "الكون",
    parent: "al_kawn",
    children: [],
    status: "protected",
    truthSource: "product_truth",
    visibilityScope: "private_internal",
    executionMeaning: "Highest truth law for claims, gates, money, broker, launch, and visibility.",
    boundaryType: "truth_guarded",
    relationToOrigin: "highest truth law under الكون",
    productTruthImpact: "Product Truth blocks unsafe or false claims.",
    compactExplanation: "Product Truth هو قانون الحقيقة الأعلى.",
  },
  {
    id: "universe_operating_kernel",
    arabicLabel: "القاضي التنفيذي",
    englishLabel: "Universe Operating Kernel",
    layerType: "kernel",
    owner: "الكون",
    parent: "al_kawn",
    children: [],
    status: "active_with_notes",
    truthSource: "kernel_enforced",
    visibilityScope: "private_internal",
    executionMeaning: "Execution judge enforcing boundaries, Product Truth, and safe internal work.",
    boundaryType: "internal_execution",
    relationToOrigin: "execution judge under الكون",
    productTruthImpact: "Dangerous actions require Ahmad approval or stay blocked.",
    compactExplanation: "Universe Operating Kernel هو القاضي التنفيذي.",
  },
  {
    id: "existence_contract_law",
    arabicLabel: "قانون عقد الوجود",
    englishLabel: "Existence Contract Law",
    layerType: "law",
    owner: "الكون",
    parent: "al_kawn",
    children: [],
    status: "active",
    truthSource: "product_truth",
    visibilityScope: "private_internal",
    executionMeaning: "Every entity must declare why it exists and where it belongs.",
    boundaryType: "truth_guarded",
    relationToOrigin: "belonging law under الكون",
    productTruthImpact: "Blocks orphan entities and unclear product meaning.",
    compactExplanation: "كل شيء داخل الكون يجب أن ينتمي إلى طبقة واضحة.",
  },
  {
    id: "ahmad_digital_vault",
    arabicLabel: "خزنة أحمد الرقمية",
    englishLabel: "Ahmad Digital Vault",
    layerType: "vault",
    owner: "Ahmad",
    parent: "al_kawn",
    children: [],
    status: "future_gated",
    truthSource: "future_gate_pending",
    visibilityScope: "private_internal",
    executionMeaning: "Private documents, secrets, memory, and decisions stay under Ahmad control.",
    boundaryType: "secret_guarded",
    relationToOrigin: "private memory branch under الكون",
    productTruthImpact: "Blocks secrets in Git, public assets, or external systems.",
    compactExplanation: "Private memory and secrets remain under Ahmad control.",
  },
  {
    id: "protection_core",
    arabicLabel: "نواة الحماية",
    englishLabel: "Protection Core",
    layerType: "protection",
    owner: "الكون",
    parent: "al_kawn",
    children: [],
    status: "protected",
    truthSource: "kernel_enforced",
    visibilityScope: "private_internal",
    executionMeaning: "Permissions, audit, kill switch, and secret protection.",
    boundaryType: "secret_guarded",
    relationToOrigin: "protection branch under الكون",
    productTruthImpact: "Protects privacy and blocked dangerous actions.",
    compactExplanation: "Protection Core guards private operation.",
  },
  {
    id: "universe_one",
    arabicLabel: "Universe One",
    englishLabel: "Universe One",
    layerType: "reality",
    owner: "الكون",
    parent: "al_kawn",
    children: [],
    status: "active_with_notes",
    truthSource: "simulation_labeled",
    visibilityScope: "private_internal",
    executionMeaning: "Literal living reality system using labeled device-time and device-date simulation.",
    boundaryType: "truth_guarded",
    relationToOrigin: "living reality branch under الكون",
    productTruthImpact: "Prevents fake real-weather or exact-location claims.",
    compactExplanation: "Universe One is living reality, real when sourced and simulated when labeled.",
  },
  {
    id: "swiss_local_constitution",
    arabicLabel: "الدستور السويسري المحلي",
    englishLabel: "Swiss Local Constitution",
    layerType: "law",
    owner: "الكون",
    parent: "al_kawn",
    children: ["global_layer"],
    status: "future_gated",
    truthSource: "future_gate_pending",
    visibilityScope: "private_internal",
    executionMeaning: "Local legal review layer that stays above global/public layers.",
    boundaryType: "legal_stop",
    relationToOrigin: "local legal review branch under الكون",
    productTruthImpact: "Blocks global claims before Swiss/local review.",
    compactExplanation: "Swiss Local Constitution is above the Global Layer.",
  },
  {
    id: "human_interface",
    arabicLabel: "واجهة أحمد",
    englishLabel: "Human Interface",
    layerType: "interface",
    owner: "Ahmad",
    parent: "al_kawn",
    children: [],
    status: "active",
    truthSource: "local_project_state",
    visibilityScope: "private_founder",
    executionMeaning: "Founder-facing command, reports, decisions, and Product Truth surfaces.",
    boundaryType: "private_only",
    relationToOrigin: "Ahmad interface under الكون",
    productTruthImpact: "Keeps final decisions with Ahmad.",
    compactExplanation: "Human Interface connects Ahmad to الكون.",
  },
  {
    id: "sovereign_execution",
    arabicLabel: "التنفيذ السيادي",
    englishLabel: "Sovereign Execution",
    layerType: "execution",
    owner: "الكون",
    parent: "al_kawn",
    children: [],
    status: "future_gated",
    truthSource: "future_gate_pending",
    visibilityScope: "private_internal",
    executionMeaning: "Future safe internal execution under Product Truth and Ahmad boundary.",
    boundaryType: "internal_execution",
    relationToOrigin: "future execution branch under الكون",
    productTruthImpact: "No external or dangerous execution without gates.",
    compactExplanation: "Future-governed internal execution only.",
  },
  {
    id: "execution_court",
    arabicLabel: "محكمة التنفيذ",
    englishLabel: "Execution Court",
    layerType: "execution",
    owner: "الكون",
    parent: "al_kawn",
    children: [],
    status: "future_gated",
    truthSource: "future_gate_pending",
    visibilityScope: "private_internal",
    executionMeaning: "Future verdict/evidence/review layer for execution decisions.",
    boundaryType: "truth_guarded",
    relationToOrigin: "future review branch under الكون",
    productTruthImpact: "Keeps execution explainable.",
    compactExplanation: "Future execution review, not active.",
  },
  {
    id: "causal_execution",
    arabicLabel: "التنفيذ السببي",
    englishLabel: "Causal Execution",
    layerType: "execution",
    owner: "الكون",
    parent: "al_kawn",
    children: [],
    status: "future_gated",
    truthSource: "future_gate_pending",
    visibilityScope: "private_internal",
    executionMeaning: "Future cause/effect execution model with traceability and rollback.",
    boundaryType: "truth_guarded",
    relationToOrigin: "future trace branch under الكون",
    productTruthImpact: "Prevents uncontrolled automation chains.",
    compactExplanation: "Future causal trace, not active.",
  },
  {
    id: "infinity_mode",
    arabicLabel: "وضع اللانهاية",
    englishLabel: "Infinity Mode",
    layerType: "mode",
    owner: "الكون",
    parent: "al_kawn",
    children: [],
    status: "blocked",
    truthSource: "future_gate_pending",
    visibilityScope: "private_internal",
    executionMeaning: "Future mode only; blocked now.",
    boundaryType: "future_gate",
    relationToOrigin: "blocked future mode under الكون",
    productTruthImpact: "Prevents premature Infinity Mode activation.",
    compactExplanation: "Infinity Mode محجوب حاليًا.",
  },
  {
    id: "operator_mode",
    arabicLabel: "وضع المشغل",
    englishLabel: "Operator Mode",
    layerType: "mode",
    owner: "الكون",
    parent: "al_kawn",
    children: [],
    status: "blocked",
    truthSource: "future_gate_pending",
    visibilityScope: "private_internal",
    executionMeaning: "Future operator capability only; blocked now.",
    boundaryType: "future_gate",
    relationToOrigin: "blocked future mode under الكون",
    productTruthImpact: "Prevents premature operator authority.",
    compactExplanation: "Operator Mode محجوب حاليًا.",
  },
  {
    id: "self_building",
    arabicLabel: "البناء الذاتي",
    englishLabel: "Self-Building",
    layerType: "mode",
    owner: "الكون",
    parent: "al_kawn",
    children: [],
    status: "future_gated",
    truthSource: "future_gate_pending",
    visibilityScope: "private_internal",
    executionMeaning: "Future-governed only, no uncontrolled code-changing automation.",
    boundaryType: "future_gate",
    relationToOrigin: "future governed mode under الكون",
    productTruthImpact: "Blocks uncontrolled self-building.",
    compactExplanation: "Self-Building is future-governed only.",
  },
  {
    id: "pro_max_galaxy",
    arabicLabel: "مجرة برو ماكس",
    englishLabel: "Pro Max Galaxy",
    layerType: "galaxy",
    owner: "الكون",
    parent: "al_kawn",
    children: ["earth_planet"],
    status: "protected",
    truthSource: "manual_founder_decision",
    visibilityScope: "private_internal",
    executionMeaning: "Product galaxy inside الكون.",
    boundaryType: "truth_guarded",
    relationToOrigin: "product galaxy branch under الكون",
    productTruthImpact: "Keeps Pro Max below الكون.",
    compactExplanation: "Pro Max Galaxy داخل الكون.",
  },
  {
    id: "earth_planet",
    arabicLabel: "كوكب الأرض",
    englishLabel: "Earth Planet",
    layerType: "planet",
    owner: "Pro Max Galaxy",
    parent: "pro_max_galaxy",
    children: [
      "trading_project",
      "trading_surface",
      "pro_max_center",
      "global_layer",
      "public_pro_max_future",
      "alkon_background_guardian",
    ],
    status: "active_with_notes",
    truthSource: "local_project_state",
    visibilityScope: "private_internal",
    executionMeaning: "First planet and complete trading project.",
    boundaryType: "truth_guarded",
    relationToOrigin: "first planet inside Pro Max Galaxy",
    productTruthImpact: "Keeps trading demo-safe and public future blocked.",
    compactExplanation: "Earth Planet داخل Pro Max Galaxy.",
  },
  {
    id: "trading_project",
    arabicLabel: "مشروع التداول",
    englishLabel: "Trading Project",
    layerType: "project",
    owner: "Earth Planet",
    parent: "earth_planet",
    children: ["trading_surface"],
    status: "active_with_notes",
    truthSource: "local_project_state",
    visibilityScope: "private_internal",
    executionMeaning: "Complete trading project on Earth Planet.",
    boundaryType: "truth_guarded",
    relationToOrigin: "project surface inside Earth Planet",
    productTruthImpact: "Keeps trading demo-safe/read-only.",
    compactExplanation: "Trading Project belongs to Earth Planet.",
  },
  {
    id: "trading_surface",
    arabicLabel: "سطح التداول",
    englishLabel: "/trading",
    layerType: "route",
    owner: "Earth Planet",
    parent: "earth_planet",
    children: [],
    status: "active_with_notes",
    truthSource: "local_project_state",
    visibilityScope: "private_internal",
    executionMeaning: "Trading surface on Earth Planet.",
    boundaryType: "money_stop",
    relationToOrigin: "route under Earth Planet",
    productTruthImpact: "Real money and broker execution remain disabled.",
    compactExplanation: "/trading ينتمي إلى Earth Planet.",
  },
  {
    id: "pro_max_center",
    arabicLabel: "مركز برو ماكس",
    englishLabel: "Pro Max Center",
    layerType: "surface",
    owner: "Earth Planet",
    parent: "earth_planet",
    children: [],
    status: "active_with_notes",
    truthSource: "local_project_state",
    visibilityScope: "public_future_blocked",
    executionMeaning: "Public-safe product center while global launch remains blocked.",
    boundaryType: "public_block",
    relationToOrigin: "product center inside Earth Planet",
    productTruthImpact: "Must not expose الكون or ALKON publicly.",
    compactExplanation: "Pro Max Center belongs to Earth Planet / Pro Max product surface.",
  },
  {
    id: "global_layer",
    arabicLabel: "الطبقة العالمية",
    englishLabel: "Global Layer",
    layerType: "surface",
    owner: "Earth Planet",
    parent: "earth_planet",
    children: [],
    status: "future_gated",
    truthSource: "future_gate_pending",
    visibilityScope: "public_future_blocked",
    executionMeaning: "Future global layer under Swiss Local Constitution.",
    boundaryType: "legal_stop",
    relationToOrigin: "future global branch under Earth Planet",
    productTruthImpact: "No global public claims now.",
    compactExplanation: "Global Layer is under Swiss Local Constitution.",
  },
  {
    id: "public_pro_max_future",
    arabicLabel: "Pro Max العام المستقبلي",
    englishLabel: "Public Pro Max Future",
    layerType: "surface",
    owner: "Earth Planet",
    parent: "earth_planet",
    children: [],
    status: "future_gated",
    truthSource: "future_gate_pending",
    visibilityScope: "public_future_blocked",
    executionMeaning: "Future public product only after all gates close.",
    boundaryType: "public_block",
    relationToOrigin: "future public branch under Earth Planet",
    productTruthImpact: "Public launch remains blocked.",
    compactExplanation: "Public Pro Max Future بوابة مستقبلية.",
  },
  {
    id: "alkon_background_guardian",
    arabicLabel: "حارس ALKON الخلفي",
    englishLabel: "ALKON Background Guardian",
    layerType: "guardian",
    owner: "Earth Planet",
    parent: "earth_planet",
    children: [],
    status: "protected",
    truthSource: "product_truth",
    visibilityScope: "private_internal",
    executionMeaning: "Private background guardian, not public product layer.",
    boundaryType: "private_only",
    relationToOrigin: "private guardian under Earth Planet",
    productTruthImpact: "No public ALKON exposure.",
    compactExplanation: "ALKON هو حارس خلفي خاص.",
  },
];

export function getAlKawnVisualMapNodes(): AlKawnVisualMapNode[] {
  return alKawnVisualMapNodes;
}
