import "server-only";
import type { AlKawnVisualMapLayer } from "./types";

export const alKawnVisualMapLayers: AlKawnVisualMapLayer[] = [
  {
    id: "ahmad_human",
    arabicLabel: "أحمد",
    technicalLabel: "Ahmad Human",
    parent: null,
    children: ["ahmad_private_devices"],
    purpose: "Ahmad is the origin, decision maker, and final owner of the private digital existence.",
    status: "protected",
    truthSource: "manual_founder_decision",
    productTruthImpact: "All gates, approvals, and final decisions return to Ahmad.",
    executionRole: "Origin and final decision authority.",
    approvalGate: "Ahmad approval is required for legal, money, public launch, broker, brand, secrets, and final decisions.",
    visualImportance: "origin",
  },
  {
    id: "ahmad_private_devices",
    arabicLabel: "أجهزة أحمد الخاصة",
    technicalLabel: "Ahmad Private Devices",
    parent: "ahmad_human",
    children: ["al_kawn"],
    purpose: "The only allowed environment for the private الكون operating surface.",
    status: "protected",
    truthSource: "product_truth",
    productTruthImpact: "Blocks public Universe exposure.",
    executionRole: "Private access boundary.",
    approvalGate: "No public distribution without Ahmad approval.",
    visualImportance: "private_branch",
  },
  {
    id: "al_kawn",
    arabicLabel: "الكون",
    technicalLabel: "Ahmad private digital existence",
    parent: "ahmad_private_devices",
    children: [
      "existence_contract",
      "product_truth",
      "universe_operating_kernel",
      "ahmad_digital_vault",
      "protection_core",
      "universe_one",
      "swiss_local_constitution",
      "human_interface",
      "sovereign_execution",
      "execution_court",
      "causal_execution",
      "infinity_mode",
      "operator_mode",
      "self_building",
      "pro_max_galaxy",
    ],
    purpose: "الكون is Ahmad's private digital existence and the main private project.",
    status: "protected",
    truthSource: "manual_founder_decision",
    productTruthImpact: "Everything inside must preserve privacy, Product Truth, and Ahmad final authority.",
    executionRole: "Private operating reality for safe internal work.",
    approvalGate: "Stops for law, money, public exposure, secrets, and final founder decisions.",
    visualImportance: "core_system",
  },
  {
    id: "existence_contract",
    arabicLabel: "عقد الوجود",
    technicalLabel: "Existence Contract",
    parent: "al_kawn",
    children: [],
    purpose: "Every entity must know why it exists, its layer, source of truth, impact, and explanation path.",
    status: "active",
    truthSource: "product_truth",
    productTruthImpact: "Prevents orphan, fake, or contradictory project layers.",
    executionRole: "Admission rule for anything entering الكون.",
    approvalGate: "Entities without a contract require cleanup or Ahmad decision.",
    visualImportance: "governing_law",
  },
  {
    id: "product_truth",
    arabicLabel: "قانون الحقيقة",
    technicalLabel: "Product Truth",
    parent: "al_kawn",
    children: [],
    purpose: "The highest truth law for launch, money, broker, brand, legal, privacy, and claims.",
    status: "protected",
    truthSource: "product_truth",
    productTruthImpact: "Blocks violations immediately.",
    executionRole: "Highest truth law.",
    approvalGate: "No override without Ahmad and verified evidence.",
    visualImportance: "governing_law",
  },
  {
    id: "universe_operating_kernel",
    arabicLabel: "القاضي التنفيذي",
    technicalLabel: "Universe Operating Kernel",
    parent: "al_kawn",
    children: [],
    purpose: "Canonicalized existing kernel that judges safe internal execution and dangerous boundaries.",
    status: "active",
    truthSource: "kernel_state",
    productTruthImpact: "Enforces Product Truth and Absolute Founder Boundary.",
    executionRole: "Execution judge.",
    approvalGate: "Dangerous actions require Ahmad approval or remain blocked.",
    visualImportance: "execution_judge",
  },
  {
    id: "ahmad_digital_vault",
    arabicLabel: "خزنة أحمد الرقمية",
    technicalLabel: "Ahmad Digital Vault",
    parent: "al_kawn",
    children: [],
    purpose: "Private documents, secrets, memory, and decisions remain under Ahmad control.",
    status: "protected",
    truthSource: "future_gate_pending",
    productTruthImpact: "Blocks secrets from public assets, Git, or external connections.",
    executionRole: "Private memory and secrets boundary.",
    approvalGate: "Explicit Ahmad approval required before external sharing.",
    visualImportance: "private_branch",
  },
  {
    id: "protection_core",
    arabicLabel: "نواة الحماية",
    technicalLabel: "Protection Core",
    parent: "al_kawn",
    children: [],
    purpose: "Permissions, audit, kill switch, secret protection, and boundary defense.",
    status: "protected",
    truthSource: "kernel_state",
    productTruthImpact: "Protects privacy, auditability, and dangerous-action blocking.",
    executionRole: "Safety and permission guard.",
    approvalGate: "Protected reports/routes/gates cannot be casually removed.",
    visualImportance: "core_system",
  },
  {
    id: "universe_one",
    arabicLabel: "الكون واحد",
    technicalLabel: "Universe One",
    parent: "al_kawn",
    children: [],
    purpose: "Literal living reality system: device time, device date, day/night, seasons, atmosphere, stars, moon, motion, soundscape, and source truth.",
    status: "active",
    truthSource: "local_project_state",
    productTruthImpact: "Keeps reality features labeled as sourced, simulated, pending, or not connected.",
    executionRole: "Living pulse and source-truth layer.",
    approvalGate: "No real weather/location claim without a real provider or permission.",
    visualImportance: "core_system",
  },
  {
    id: "swiss_local_constitution",
    arabicLabel: "الدستور السويسري المحلي",
    technicalLabel: "Swiss Local Constitution",
    parent: "al_kawn",
    children: ["global_layer"],
    purpose: "Local legal-awareness layer that stays above Global Layer.",
    status: "pending",
    truthSource: "future_gate_pending",
    productTruthImpact: "Prevents global/public activity from bypassing Swiss/local review.",
    executionRole: "Local constitution gate.",
    approvalGate: "Legal review required.",
    visualImportance: "governing_law",
  },
  {
    id: "human_interface",
    arabicLabel: "واجهة أحمد الإنسانية",
    technicalLabel: "Human Interface",
    parent: "al_kawn",
    children: [],
    purpose: "Founder-facing private surfaces for decisions, reports, tasks, appointments, and Product Truth.",
    status: "active",
    truthSource: "local_project_state",
    productTruthImpact: "Keeps founder decisions visible and separate from automation.",
    executionRole: "Ahmad interaction layer.",
    approvalGate: "No final decision is automatic.",
    visualImportance: "private_branch",
  },
  {
    id: "sovereign_execution",
    arabicLabel: "التنفيذ السيادي",
    technicalLabel: "Sovereign Execution",
    parent: "al_kawn",
    children: [],
    purpose: "Safe internal execution concept under Product Truth and kernel judgment.",
    status: "pending",
    truthSource: "future_gate_pending",
    productTruthImpact: "No external, legal, money, or irreversible execution without Ahmad.",
    executionRole: "Future governed internal execution layer.",
    approvalGate: "Requires controlled mission before activation.",
    visualImportance: "future_gate",
  },
  {
    id: "execution_court",
    arabicLabel: "محكمة التنفيذ",
    technicalLabel: "Execution Court",
    parent: "al_kawn",
    children: [],
    purpose: "Future decision court for execution verdicts, evidence, and rollback explanation.",
    status: "pending",
    truthSource: "future_gate_pending",
    productTruthImpact: "Keeps dangerous execution explainable and approval-gated.",
    executionRole: "Future execution verdict review.",
    approvalGate: "Requires Ahmad-approved architecture mission.",
    visualImportance: "future_gate",
  },
  {
    id: "causal_execution",
    arabicLabel: "التنفيذ السببي",
    technicalLabel: "Causal Execution",
    parent: "al_kawn",
    children: [],
    purpose: "Future cause/effect execution model from intent to evidence to rollback.",
    status: "pending",
    truthSource: "future_gate_pending",
    productTruthImpact: "Prevents uncontrolled automation chains.",
    executionRole: "Future causal trace layer.",
    approvalGate: "Requires Ahmad approval before build.",
    visualImportance: "future_gate",
  },
  {
    id: "infinity_mode",
    arabicLabel: "وضع اللانهاية",
    technicalLabel: "Infinity Mode",
    parent: "al_kawn",
    children: [],
    purpose: "Future expansion mode only after conflicts, boundary, and kernel gates are resolved.",
    status: "blocked",
    truthSource: "future_gate_pending",
    productTruthImpact: "Must not become active during cleanup or visual-map work.",
    executionRole: "Future mode, not active.",
    approvalGate: "Ahmad approval and registry clearance required.",
    visualImportance: "future_gate",
  },
  {
    id: "operator_mode",
    arabicLabel: "وضع المشغل",
    technicalLabel: "Operator Mode",
    parent: "al_kawn",
    children: [],
    purpose: "Future governed operator capability, not started in this mission.",
    status: "blocked",
    truthSource: "future_gate_pending",
    productTruthImpact: "Prevents uncontrolled operational authority.",
    executionRole: "Future operator layer, not active.",
    approvalGate: "Ahmad approval required.",
    visualImportance: "future_gate",
  },
  {
    id: "self_building",
    arabicLabel: "البناء الذاتي",
    technicalLabel: "Self-Building",
    parent: "al_kawn",
    children: [],
    purpose: "Future self-building capability under kernel, boundary, audit, and Ahmad approval.",
    status: "blocked",
    truthSource: "future_gate_pending",
    productTruthImpact: "No uncontrolled code-changing automation.",
    executionRole: "Future capability, not active.",
    approvalGate: "Ahmad approval and safety gates required.",
    visualImportance: "future_gate",
  },
  {
    id: "pro_max_galaxy",
    arabicLabel: "مجرة Pro Max",
    technicalLabel: "Pro Max Galaxy",
    parent: "al_kawn",
    children: ["earth_planet"],
    purpose: "Product galaxy inside الكون and future public product container.",
    status: "protected",
    truthSource: "manual_founder_decision",
    productTruthImpact: "Keeps Pro Max below الكون and prevents Pro Max from claiming to be Universe.",
    executionRole: "Product container.",
    approvalGate: "Public product activity remains blocked until gates close.",
    visualImportance: "product_branch",
  },
  {
    id: "earth_planet",
    arabicLabel: "كوكب الأرض",
    technicalLabel: "Earth Planet",
    parent: "pro_max_galaxy",
    children: [
      "living_earth_reality",
      "trading_surface",
      "global_layer",
      "public_pro_max_future",
      "alkon_background_guardian",
    ],
    purpose: "First planet and complete trading project inside Pro Max Galaxy.",
    status: "active",
    truthSource: "local_project_state",
    productTruthImpact: "Keeps trading demo-safe/read-only and future public launch blocked.",
    executionRole: "Trading project world.",
    approvalGate: "Real money, broker, billing, legal, and public gates remain blocked.",
    visualImportance: "product_branch",
  },
  {
    id: "living_earth_reality",
    arabicLabel: "واقع الأرض الحي",
    technicalLabel: "Living Earth Reality",
    parent: "earth_planet",
    children: [],
    purpose: "Device-time and device-date life layers for Earth atmosphere, seasons, day/night, and visual continuity.",
    status: "active",
    truthSource: "local_project_state",
    productTruthImpact: "Labels simulation and blocks fake weather/location claims.",
    executionRole: "Living visual reality layer.",
    approvalGate: "No real weather or location claim without verified source.",
    visualImportance: "surface",
  },
  {
    id: "trading_surface",
    arabicLabel: "سطح التداول",
    technicalLabel: "/trading",
    parent: "earth_planet",
    children: [],
    purpose: "Private/demo-safe trading surface on Earth Planet.",
    status: "active",
    truthSource: "local_project_state",
    productTruthImpact: "Shows real money disabled and broker execution disabled/not connected.",
    executionRole: "Trading operating surface.",
    approvalGate: "No real trading or broker execution without Ahmad and legal/broker gates.",
    visualImportance: "surface",
  },
  {
    id: "global_layer",
    arabicLabel: "الطبقة العالمية",
    technicalLabel: "Global Layer",
    parent: "earth_planet",
    children: [],
    purpose: "Future global layer under Swiss Local Constitution.",
    status: "blocked",
    truthSource: "future_gate_pending",
    productTruthImpact: "Blocks global launch and global claims.",
    executionRole: "Future global review layer.",
    approvalGate: "Swiss/local and global legal review required.",
    visualImportance: "future_gate",
  },
  {
    id: "public_pro_max_future",
    arabicLabel: "Pro Max العام المستقبلي",
    technicalLabel: "Public Pro Max Future",
    parent: "earth_planet",
    children: [],
    purpose: "Future public product surface after all brand, legal, compliance, billing, broker, asset, and founder gates close.",
    status: "blocked",
    truthSource: "future_gate_pending",
    productTruthImpact: "Public launch remains blocked/not started.",
    executionRole: "Future public product layer.",
    approvalGate: "Ahmad final approval and all launch gates required.",
    visualImportance: "future_gate",
  },
  {
    id: "alkon_background_guardian",
    arabicLabel: "ALKON الحارس الخلفي",
    technicalLabel: "ALKON Background Guardian",
    parent: "earth_planet",
    children: [],
    purpose: "Private/background intelligence guardian and support layer.",
    status: "protected",
    truthSource: "product_truth",
    productTruthImpact: "Keeps ALKON private/background, not public, not second, and not visually dominant.",
    executionRole: "Private support guardian.",
    approvalGate: "No public exposure.",
    visualImportance: "background_guardian",
  },
];

export function getAlKawnVisualMapLayers(): AlKawnVisualMapLayer[] {
  return alKawnVisualMapLayers;
}
