import "server-only";

import type { LocalDayCycleStage } from "./types";

const stages: LocalDayCycleStage[] = [
  {
    id: "wake_start",
    order: 1,
    name: "Wake / Start",
    purpose: "Begin the local closed-universe review without launch or production assumptions.",
    checks: ["Open the repo", "Confirm local-only intent", "Confirm dangerous systems stay blocked"],
    passCriteria: ["Work starts from the local repo", "Launch and production remain out of scope"],
    failCriteria: ["Work begins with launch, billing, broker/feed, live, or production activation"],
    output: "Local review session started",
    nextAction: "Run build check",
  },
  {
    id: "build_check",
    order: 2,
    name: "Build check",
    purpose: "Verify the local codebase can compile before product review.",
    checks: ["Run build/type validation", "Do not edit secrets", "Do not use production activation"],
    passCriteria: ["Build evidence is available", "No production secret changes are required"],
    failCriteria: ["Build fails without a scoped repair plan", "Secret changes are requested"],
    output: "Build readiness note",
    nextAction: "Start runtime locally",
  },
  {
    id: "runtime_start",
    order: 3,
    name: "Runtime start",
    purpose: "Start the product locally for founder review.",
    checks: ["Run local runtime", "Keep local paper-safe mode", "Do not expose public launch"],
    passCriteria: ["Local routes respond", "No external publishing or live routing is active"],
    failCriteria: ["Runtime cannot start", "External activation is attempted"],
    output: "Runtime readiness note",
    nextAction: "Review public entry",
  },
  {
    id: "public_entry_review",
    order: 4,
    name: "Public entry review",
    purpose: "Review the first public impression with professional public language only.",
    checks: ["Earth Mark scale", "Free / Pro / VIP / Institutional naming", "No internal terminology leak"],
    passCriteria: ["Entry is clear, premium, local-safe, and non-launch"],
    failCriteria: ["Entry claims launch, billing, live trading, fake plans, or internal command access"],
    output: "Public entry acceptance note",
    nextAction: "Review Free/Demo journey",
  },
  {
    id: "free_demo_journey_review",
    order: 5,
    name: "Free/Demo journey review",
    purpose: "Confirm the active local user path is familiar, paper-safe, and not overloaded.",
    checks: ["Plan truth", "Paper-safe workspace", "Assistant basics", "Blocked states explained"],
    passCriteria: ["Free feels useful without pretending paid activation"],
    failCriteria: ["VIP/Pro/Institutional are presented as active without entitlement"],
    output: "Free journey note",
    nextAction: "Review workstation",
  },
  {
    id: "workstation_review",
    order: 6,
    name: "Workstation review",
    purpose: "Verify the Trading Workspace stays chart-first and uncluttered.",
    checks: ["Chart dominance", "Execution panel clarity", "Assistant placement", "No internal overload"],
    passCriteria: ["Workspace feels like a professional local trading terminal"],
    failCriteria: ["Chart is hidden, execution is confusing, or internal systems dominate"],
    output: "Workstation acceptance note",
    nextAction: "Review chart",
  },
  {
    id: "chart_review",
    order: 7,
    name: "Chart review",
    purpose: "Protect the repaired chart from visual regression.",
    checks: ["Grid readability", "Price labels", "Current price marker", "Dark/light contrast"],
    passCriteria: ["Chart remains readable and dominant"],
    failCriteria: ["Chart looks broken, tiny, washed out, or covered"],
    output: "Chart quality note",
    nextAction: "Review paper execution",
  },
  {
    id: "execution_paper_review",
    order: 8,
    name: "Execution paper review",
    purpose: "Confirm visible execution remains paper-only and blocked for real money.",
    checks: ["Buy / AI Wait / Sell clarity", "Paper-only truth", "Real mode remains blocked"],
    passCriteria: ["Paper execution is understandable and live execution remains disabled"],
    failCriteria: ["Real orders, broker routing, or money movement appear active"],
    output: "Execution truth note",
    nextAction: "Review TPM Assistant",
  },
  {
    id: "tpm_assistant_review",
    order: 9,
    name: "TPM Assistant review",
    purpose: "Verify Assistant responses explain state safely without signals or internal terminology.",
    checks: ["Plan-aware copy", "Blocked-state explanations", "No profit claims", "No execution authority"],
    passCriteria: ["Assistant is useful, compact, truthful, and safe"],
    failCriteria: ["Assistant promises outcomes, signals, live activation, or private command access"],
    output: "Assistant review note",
    nextAction: "Review Why Blocked",
  },
  {
    id: "why_blocked_review",
    order: 10,
    name: "Why Blocked review",
    purpose: "Confirm blocked conditions are clear and not scary.",
    checks: ["Live disabled explanation", "Billing inactive explanation", "Broker/feed guarded explanation"],
    passCriteria: ["User can understand blocked states without launch confusion"],
    failCriteria: ["Blocked states feel like errors or imply activation is available now"],
    output: "Blocked-state clarity note",
    nextAction: "Review Journal / Coach",
  },
  {
    id: "journal_coach_review",
    order: 11,
    name: "Journal / Coach review",
    purpose: "Check learning prompts remain safe and do not pressure trading.",
    checks: ["Journal prompts", "Coach prompts", "No financial advice", "No persistence overclaim"],
    passCriteria: ["Prompts support reflection and learning"],
    failCriteria: ["Prompts encourage overtrading, gambling, or guaranteed outcomes"],
    output: "Journal/Coach review note",
    nextAction: "Review Settings",
  },
  {
    id: "settings_review",
    order: 12,
    name: "Settings review",
    purpose: "Verify local user controls are clear and professional.",
    checks: ["Account/session", "Plan", "Assistant", "Journal/Coach", "Theme/language", "Account type"],
    passCriteria: ["Settings is a clean user control center"],
    failCriteria: ["Settings exposes internal command systems or fake billing"],
    output: "Settings review note",
    nextAction: "Review Diagnostics",
  },
  {
    id: "diagnostics_review",
    order: 13,
    name: "Diagnostics review",
    purpose: "Confirm readiness truth is visible without exposing secrets or fake metrics.",
    checks: ["Product truth", "Plan readiness", "Assistant readiness", "Safety boundaries", "Local ops readiness"],
    passCriteria: ["Diagnostics is compact, truthful, and non-sensitive"],
    failCriteria: ["Diagnostics leaks secrets, private data, fake metrics, or public launch claims"],
    output: "Diagnostics review note",
    nextAction: "Review Product Truth",
  },
  {
    id: "product_truth_review",
    order: 14,
    name: "Product Truth review",
    purpose: "Reconfirm all dangerous systems remain blocked or inactive.",
    checks: ["Live execution", "Real money", "Broker/feed", "Billing", "Launch", "Social publishing"],
    passCriteria: ["All dangerous systems remain blocked or inactive"],
    failCriteria: ["Any dangerous system appears enabled or marketed"],
    output: "Product truth note",
    nextAction: "Review visual acceptance",
  },
  {
    id: "visual_acceptance_review",
    order: 15,
    name: "Visual acceptance review",
    purpose: "Capture founder visual judgment before accepting local maturity.",
    checks: ["Dark theme", "Light theme", "RTL", "Laptop", "Ultrawide", "No clutter"],
    passCriteria: ["Ahmad accepts the visual state for the day"],
    failCriteria: ["Visual quality is confusing, busy, broken, or not premium enough"],
    output: "Visual acceptance decision",
    nextAction: "Founder decision",
  },
  {
    id: "founder_decision",
    order: 16,
    name: "Founder decision",
    purpose: "Record whether the local day passes, needs polish, or remains blocked by design.",
    checks: ["Acceptance notes", "Truth status", "Risk status", "Next safe action"],
    passCriteria: ["Decision is explicit and not launch-oriented"],
    failCriteria: ["No decision is recorded or launch pressure appears"],
    output: "Founder decision note",
    nextAction: "Create build task if needed",
  },
  {
    id: "build_task_creation",
    order: 17,
    name: "Build task creation",
    purpose: "Create scoped Codex tasks for safe local refinement only.",
    checks: ["Scope", "Forbidden scope", "Validation plan", "Product truth"],
    passCriteria: ["Task is specific, safe, and validation-heavy"],
    failCriteria: ["Task opens launch, billing, broker/feed, real money, social publishing, or secrets"],
    output: "Local build task draft",
    nextAction: "Validate",
  },
  {
    id: "validation",
    order: 18,
    name: "Validation",
    purpose: "Run validation before accepting local changes.",
    checks: ["TypeScript", "ESLint", "Build", "Prisma validate", "Regression", "Smoke", "Diff check"],
    passCriteria: ["Validation passes or failures are documented honestly"],
    failCriteria: ["Validation is skipped or falsely marked passing"],
    output: "Validation report",
    nextAction: "Git clean / push check",
  },
  {
    id: "git_clean_push_check",
    order: 19,
    name: "Git clean / push check",
    purpose: "Confirm work is committed/pushed only after validation.",
    checks: ["git status", "commit hash", "push status", "clean tree"],
    passCriteria: ["Git state is known and clean when required"],
    failCriteria: ["Unknown dirty changes remain"],
    output: "Git state note",
    nextAction: "End-of-day report",
  },
  {
    id: "end_of_day_report",
    order: 20,
    name: "End-of-day report",
    purpose: "Summarize the local day without fake metrics or launch claims.",
    checks: ["Completed stages", "Failed stages", "Blockers", "Next actions"],
    passCriteria: ["Report is honest and launch-forbidden"],
    failCriteria: ["Report claims public readiness or fake usage"],
    output: "Local operations report",
    nextAction: "Sleep / Archive",
  },
  {
    id: "sleep_archive",
    order: 21,
    name: "Sleep / Archive",
    purpose: "Close the local day and preserve learning for the next safe cycle.",
    checks: ["Archive decision", "No active dangerous workflow", "Next safe local action"],
    passCriteria: ["Day is closed safely"],
    failCriteria: ["Unresolved high-risk action is left ambiguous"],
    output: "Archived local day note",
    nextAction: "Wait for next local day",
  },
];

export function getLocalDayCycleSnapshot(checkedAt = new Date().toISOString()) {
  return {
    checkedAt,
    mode: "local_day_cycle" as const,
    operationMode: "local_closed_universe" as const,
    stages,
    summary: {
      totalStages: stages.length,
      launchCriteriaIncluded: false,
      productionCriteriaIncluded: false,
      billingCriteriaIncluded: false,
      realMoneyCriteriaIncluded: false,
      brokerFeedActivationIncluded: false,
      socialPublishingIncluded: false,
    },
    truth: {
      localOnly: true,
      paperSafe: true,
      readinessOnly: true,
      automaticLaunch: false,
      fakeUsersMetricsRevenue: "not_allowed" as const,
    },
  };
}
