import "server-only";

import type { LocalDigitalTwinProfile } from "./types";

const profiles: LocalDigitalTwinProfile[] = [
  {
    id: "guest_visitor",
    label: "Guest visitor",
    journey: ["Public entry", "Plan overview", "Enter workspace preview"],
    visibleSurfaces: ["Public entry", "Free plan explanation", "Product truth summary"],
    expectedConfusionPoints: ["Whether live trading is active", "Whether billing exists"],
    passCriteria: ["Understands Free is paper-safe", "Sees no fake launch claim"],
    failureSignals: ["Thinks broker/feed or billing is active", "Sees internal command language"],
    safeNextActions: ["Clarify paper-safe copy", "Keep CTA focused on workspace review"],
    testPersonaOnly: true,
  },
  {
    id: "free_demo_user",
    label: "Free/Demo user",
    journey: ["Workspace", "Chart", "Paper execution", "TPM Assistant", "Journal / Coach"],
    visibleSurfaces: ["Trading Workspace", "Paper execution", "TPM Assistant", "Settings", "Diagnostics"],
    expectedConfusionPoints: ["Why real execution is blocked", "Why Pro/VIP are planned"],
    passCriteria: ["Can use paper-safe workspace without internal complexity"],
    failureSignals: ["Sees VIP as active", "Sees Founder Command as a feature"],
    safeNextActions: ["Use Why Blocked explanations", "Keep Assistant guidance compact"],
    testPersonaOnly: true,
  },
  {
    id: "pro_interested_user",
    label: "Pro-interested user",
    journey: ["Plan comparison", "Assistant explanation", "Journal / Coach planned depth"],
    visibleSurfaces: ["Pro planned value", "Professional workspace language", "No billing claim"],
    expectedConfusionPoints: ["Whether Pro is active now", "Whether payment is available"],
    passCriteria: ["Understands Pro is planned unless entitled"],
    failureSignals: ["Sees checkout, active paid claim, or fake entitlement"],
    safeNextActions: ["Use planned/readiness language", "Avoid pricing activation"],
    testPersonaOnly: true,
  },
  {
    id: "vip_interested_user",
    label: "VIP-interested user",
    journey: ["VIP plan explanation", "Premium reports preview", "Community readiness"],
    visibleSurfaces: ["VIP planned value", "Premium reports planned", "VIP rooms planned"],
    expectedConfusionPoints: ["Whether VIP Brain or private rooms are active"],
    passCriteria: ["Understands VIP is premium planned value without active guarantee"],
    failureSignals: ["Sees guaranteed signals, win-rate, or active VIP claims"],
    safeNextActions: ["State premium layer as planned", "Block profit claims"],
    testPersonaOnly: true,
  },
  {
    id: "institutional_future_evaluator",
    label: "Institutional future evaluator",
    journey: ["Plan comparison", "Future team/admin/audit overview"],
    visibleSurfaces: ["Institutional future language", "No Enterprise public label"],
    expectedConfusionPoints: ["Whether institutional access is currently available"],
    passCriteria: ["Understands Institutional is future only"],
    failureSignals: ["Enterprise appears publicly", "Team/admin access appears active"],
    safeNextActions: ["Keep future-only wording", "Avoid sales claims"],
    testPersonaOnly: true,
  },
  {
    id: "arabic_rtl_user",
    label: "Arabic RTL user",
    journey: ["Arabic public entry", "RTL workspace", "Settings"],
    visibleSurfaces: ["RTL layout", "Chart numerics", "Assistant"],
    expectedConfusionPoints: ["Directionality", "Chart number readability"],
    passCriteria: ["Layout is stable and numerics remain readable"],
    failureSignals: ["Controls overlap", "Chart labels flip incorrectly"],
    safeNextActions: ["Run RTL screenshot review", "Keep chart numerics stable"],
    testPersonaOnly: true,
  },
  {
    id: "light_theme_user",
    label: "Light theme user",
    journey: ["Public entry", "Workspace", "Settings", "Diagnostics"],
    visibleSurfaces: ["Light theme", "Earth Mark", "Chart", "Plan surfaces"],
    expectedConfusionPoints: ["Washed-out contrast", "Weak status labels"],
    passCriteria: ["Light theme remains premium and readable"],
    failureSignals: ["Cards disappear", "Chart lacks contrast"],
    safeNextActions: ["Adjust tokens", "Capture light screenshots"],
    testPersonaOnly: true,
  },
  {
    id: "blocked_state_confused_user",
    label: "New user confused by blocked states",
    journey: ["Workspace", "Real mode attempt", "Why Blocked", "Assistant explanation"],
    visibleSurfaces: ["Blocked explanation", "TPM Assistant", "Product truth summary"],
    expectedConfusionPoints: ["Blocked versus broken", "Paper-safe versus live"],
    passCriteria: ["Understands blocked is intentional safety, not an error"],
    failureSignals: ["Thinks product is broken or live activation is one click away"],
    safeNextActions: ["Improve concise blocked copy", "Link to safe diagnostics"],
    testPersonaOnly: true,
  },
  {
    id: "founder_reviewer",
    label: "Founder reviewer",
    journey: ["Founder readiness", "Local report", "Visual acceptance", "Next build task"],
    visibleSurfaces: ["Founder Command readiness", "Local operations report", "Acceptance memory"],
    expectedConfusionPoints: ["What can be accepted locally versus launched globally"],
    passCriteria: ["Founder sees launch-forbidden local readiness clearly"],
    failureSignals: ["Report implies public launch or production readiness"],
    safeNextActions: ["Record acceptance state", "Draft scoped local build task"],
    testPersonaOnly: true,
  },
];

export function getLocalDigitalTwinSnapshot(checkedAt = new Date().toISOString()) {
  return {
    checkedAt,
    mode: "local_digital_twin_civilization" as const,
    profiles,
    summary: {
      profileCount: profiles.length,
      testPersonaOnly: true,
      fakeUsersIncluded: false,
      privateUserDataIncluded: false,
      secretsIncluded: false,
    },
    truth: {
      fakeUsers: "not_allowed" as const,
      realUserSimulation: "not_claimed" as const,
      launchReadinessFromPersonas: "not_allowed" as const,
      founderCommandVisibleOnlyToFounderReviewer: true,
    },
  };
}
