import "server-only";
import type { ArchitectureRegistryItem } from "./types";

export const canonicalArchitectureRegistry: ArchitectureRegistryItem[] = [
  {
    id: "route_founder_universe",
    label: "/founder/universe",
    category: "primary",
    layer: "alkawn_universe",
    path: "app/founder/universe/page.tsx",
    type: "route",
    purpose: "Private Universe Command Center for Ahmad-only review of hierarchy, gates, Product Truth, and next action.",
    canonicalOwner: "Private الكون / Universe route",
    importsOrUsedBy: ["app/founder/universe/_components/UniverseCommandCenter.tsx"],
    productTruthImpact: "Keeps Universe private, read-only, and blocked from public launch.",
    risk: "medium",
    recommendation: "Keep primary; update hierarchy wording through the registry rather than creating another command route.",
    evidence: ["reports/full-project-state-inventory.md", "tests/regression/private-universe-public-promax-layering-closure.spec.ts"],
  },
  {
    id: "route_trading",
    label: "/trading",
    category: "primary",
    layer: "trading_surface",
    path: "app/trading/page.tsx",
    type: "route",
    purpose: "Trading surface on the current Pro Max Earth operating floor.",
    canonicalOwner: "Trading surface on Earth Planet",
    importsOrUsedBy: ["app/trading/_components/TradingOperatingFloor.tsx"],
    productTruthImpact: "Shows demo-safe/read-only trading truth, disabled real money, and disabled broker execution.",
    risk: "medium",
    recommendation: "Keep primary and later rename internally to Earth Planet trading surface through controlled architecture cleanup.",
    evidence: ["reports/trading-premium-visual-realism-closure.md", "tests/regression/trading-premium-visual-realism-closure.spec.ts"],
  },
  {
    id: "route_home",
    label: "Pro Max Center /",
    category: "primary",
    layer: "public_pro_max_future",
    path: "app/page.tsx",
    type: "route",
    purpose: "Public-safe Pro Max Center surface while launch remains blocked.",
    canonicalOwner: "Public Pro Max future surface",
    importsOrUsedBy: ["modules/product/components/PublicProductEntry.tsx"],
    productTruthImpact: "Must not expose الكون, Universe internals, ALKON internals, or founder governance publicly.",
    risk: "medium",
    recommendation: "Keep primary public entry; avoid public Universe/ALKON wording.",
    evidence: ["reports/pro-max-world-status.md", "tests/regression/public-earth-product-completion.spec.ts"],
  },
  {
    id: "route_founder_alkon",
    label: "/founder/alkon",
    category: "protected",
    layer: "alkon_background_guardian",
    path: "app/founder/alkon/page.tsx",
    type: "route",
    purpose: "Private ALKON command/chat and Jar surface.",
    canonicalOwner: "ALKON private background guardian",
    importsOrUsedBy: ["modules/founder-command/components"],
    productTruthImpact: "Protects ALKON as private/background and not public.",
    risk: "high",
    recommendation: "Protect; do not expose in public nav and do not make it second layer.",
    evidence: ["reports/alkon-minus-zero-private-status.md", "tests/regression/alkon-private-command-universe.spec.ts"],
  },
  {
    id: "route_founder_command",
    label: "/founder/command",
    category: "protected",
    layer: "alkon_background_guardian",
    path: "app/founder/command/page.tsx",
    type: "route",
    purpose: "Private Founder Command room with validated governance panels.",
    canonicalOwner: "Founder command private surface",
    importsOrUsedBy: ["modules/founder-command/components/FounderCommandRoom.tsx"],
    productTruthImpact: "Private only; protects sensitive command and report surfaces.",
    risk: "high",
    recommendation: "Protect; future cleanup must preserve founder-only boundary.",
    evidence: ["reports/alkon-code-cohesion-audit.md", "tests/regression/alkon-sovereign-command-interface.spec.ts"],
  },
  {
    id: "route_founder_pocket",
    label: "/founder/pocket",
    category: "protected",
    layer: "ahmad_private_devices",
    path: "app/founder/pocket/page.tsx",
    type: "route",
    purpose: "Phone-readable private pocket decision route.",
    canonicalOwner: "Ahmad private device surface",
    importsOrUsedBy: ["modules/founder-command/components/Pocket*Card.tsx"],
    productTruthImpact: "Keeps device strategy private/read-only and blocks dangerous actions.",
    risk: "medium",
    recommendation: "Protect as private route; do not treat as native mobile app implementation.",
    evidence: ["reports/alkon-device-real-use-status.md", "tests/regression/alkon-a-z-operating-execution.spec.ts"],
  },
  {
    id: "routes_locale",
    label: "Locale compatibility routes",
    category: "compatibility",
    layer: "public_pro_max_future",
    path: "app/[locale]/*",
    type: "route",
    purpose: "Legacy/compatibility localized public routes.",
    canonicalOwner: "Public route compatibility",
    importsOrUsedBy: ["scripts/tpm-canonical-routes-smoke.mjs"],
    productTruthImpact: "Should not become primary trading identity.",
    risk: "low",
    recommendation: "Keep as compatibility while `/` and `/trading` remain canonical.",
    evidence: ["reports/pro-max-route-cohesion-result.md"],
  },
  {
    id: "api_kernel",
    label: "ALKON kernel APIs",
    category: "primary",
    layer: "kernel",
    path: "app/api/founder/alkon-kernel/*",
    type: "api",
    purpose: "Founder-only read APIs for existing ALKON kernel snapshot, commands, readiness, Local Day One, and one next action.",
    canonicalOwner: "Existing ALKON kernel",
    importsOrUsedBy: ["tests/regression/alkon-complete-sovereign-kernel.spec.ts"],
    productTruthImpact: "Keeps kernel private, read-only, no-execution, and no-public-api.",
    risk: "high",
    recommendation: "Canonicalize this existing kernel instead of creating a second Universe Operating Kernel.",
    evidence: ["lib/server/alkon-kernel/index.ts", "reports/alkon-kernel-status.md"],
  },
  {
    id: "api_infinite_growth",
    label: "Infinite growth APIs",
    category: "compatibility",
    layer: "kernel",
    path: "app/api/founder/infinite-growth/*",
    type: "api",
    purpose: "Founder-only read APIs for governed infinite growth gates and sample decisions.",
    canonicalOwner: "Governed growth compatibility layer",
    importsOrUsedBy: ["tests/regression/infinite-growth-swiss-law-constitution.spec.ts"],
    productTruthImpact: "Blocks unsafe domains but is not Universe Infinity Mode.",
    risk: "high",
    recommendation: "Keep compatibility; do not call it Infinity Mode until registry conflicts are resolved.",
    evidence: ["lib/server/infinite-growth/state.ts", "reports/duplicates-and-conflicts-audit.md"],
  },
  {
    id: "api_product_truth",
    label: "Product Truth API",
    category: "primary",
    layer: "product_truth",
    path: "app/api/product/truth/route.ts",
    type: "api",
    purpose: "Read-only Product Truth snapshot.",
    canonicalOwner: "Product Truth engine",
    importsOrUsedBy: ["public/founder diagnostics", "tests/regression/verified-platform-truth.spec.ts"],
    productTruthImpact: "Overrides automation, visuals, launch, billing, real money, broker, and claims.",
    risk: "high",
    recommendation: "Protect as primary truth API.",
    evidence: ["lib/server/product/truth.ts"],
  },
  {
    id: "api_brand_gate",
    label: "Brand Gate APIs",
    category: "protected",
    layer: "brand_gate",
    path: "app/api/founder/brand-clearance/*",
    type: "api",
    purpose: "Founder-only brand clearance readiness, risk, candidates, and adoption gate.",
    canonicalOwner: "Brand clearance gate",
    importsOrUsedBy: ["tests/regression/global-exclusive-brand-gate.spec.ts"],
    productTruthImpact: "Keeps Pro Max working_name_only and blocks public/global launch by brand gate.",
    risk: "high",
    recommendation: "Protect; do not reopen naming or adoption in this registry mission.",
    evidence: ["reports/global-brand-clearance-status.md", "reports/brand-name-freeze-status.md"],
  },
  {
    id: "api_trading_backend",
    label: "Trading backend APIs",
    category: "primary",
    layer: "trading_surface",
    path: "app/api/market/*, app/api/broker/state/route.ts",
    type: "api",
    purpose: "Demo market/fallback and broker state truth.",
    canonicalOwner: "Trading demo/read-only backend",
    importsOrUsedBy: ["scripts/tpm-canonical-routes-smoke.mjs", "tests/regression/verified-platform-truth.spec.ts"],
    productTruthImpact: "Must keep broker/feed inactive and real money disabled.",
    risk: "high",
    recommendation: "Keep primary with strict blocked broker state.",
    evidence: ["reports/pro-max-trading-readiness-status.md"],
  },
  {
    id: "api_planet",
    label: "Planet APIs",
    category: "cleanup_candidate",
    layer: "earth_planet",
    path: "app/api/planet/*",
    type: "api",
    purpose: "Parallel planet OS, consciousness, workflows, blueprint, and validation APIs.",
    canonicalOwner: "Unresolved Planet/Earth architecture",
    importsOrUsedBy: ["tests/regression/planetary-environment-engine.spec.ts"],
    productTruthImpact: "Could conflict with Earth Planet target if deepened without registry.",
    risk: "high",
    recommendation: "Classify before reuse; do not remove until controlled cleanup.",
    evidence: ["reports/full-project-state-inventory.md"],
  },
  {
    id: "api_platform_desktop_mobile",
    label: "Desktop/mobile platform APIs",
    category: "protected",
    layer: "desktop_mobile_strategy",
    path: "app/api/platform/desktop/*, app/api/platform/mobile/*",
    type: "api",
    purpose: "Read-only desktop/mobile strategy and productization readiness.",
    canonicalOwner: "Private Ahmad-only device strategy gate",
    importsOrUsedBy: ["diagnostics"],
    productTruthImpact: "No native app or store release claim.",
    risk: "medium",
    recommendation: "Keep strategy-only until native runtime is approved.",
    evidence: ["reports/private-ahmad-only-desktop-mobile-apps-strategy-gate.md"],
  },
  {
    id: "module_universe_management",
    label: "Universe Management",
    category: "primary",
    layer: "alkawn_universe",
    path: "lib/server/universe-management/index.ts",
    type: "server_module",
    purpose: "Current canonical hierarchy and Universe product truth.",
    canonicalOwner: "Universe hierarchy registry source",
    importsOrUsedBy: ["lib/server/project-universe-truth/index.ts", "tests/regression/private-universe-public-promax-layering-closure.spec.ts"],
    productTruthImpact: "Controls private Universe/public-future Pro Max hierarchy.",
    risk: "high",
    recommendation: "Keep primary; controlled cleanup normalized it to include الكون, Universe One, Swiss Local Constitution, Pro Max Galaxy, Earth Planet, and Global Layer.",
    evidence: ["reports/current-canonical-state-map.md", "reports/controlled-canonical-cleanup.md"],
  },
  {
    id: "module_project_universe_truth",
    label: "Project Universe Truth",
    category: "primary",
    layer: "alkawn_universe",
    path: "lib/server/project-universe-truth/index.ts",
    type: "server_module",
    purpose: "Server truth snapshot for `/founder/universe` and `/trading`.",
    canonicalOwner: "Project Universe Truth adapter",
    importsOrUsedBy: ["app/founder/universe/page.tsx", "app/trading/page.tsx"],
    productTruthImpact: "Keeps private/demo/legal/product gates visible.",
    risk: "high",
    recommendation: "Keep primary; do not bypass with route-local truth.",
    evidence: ["tests/regression/project-universe-real-world-operating-closure.spec.ts"],
  },
  {
    id: "module_architecture_registry",
    label: "Canonical Architecture Registry",
    category: "primary",
    layer: "alkawn_universe",
    path: "lib/server/universe/architecture-registry/*",
    type: "server_module",
    purpose: "Classifies relevant architecture into primary, compatibility, protected, cleanup candidate, and Ahmad-decision buckets.",
    canonicalOwner: "Canonical architecture registry",
    importsOrUsedBy: ["app/founder/universe/_components/UniverseCommandCenter.tsx", "tests/regression/canonical-architecture-registry.spec.ts"],
    productTruthImpact: "Blocks Infinity Mode and Ultimate Depth until conflicts are resolved.",
    risk: "high",
    recommendation: "Use for every future architecture cleanup and kernel canonicalization pass.",
    evidence: ["reports/canonical-architecture-registry.md"],
  },
  {
    id: "module_alkon_kernel",
    label: "Existing ALKON kernel",
    category: "primary",
    layer: "kernel",
    path: "lib/server/alkon-kernel/*",
    type: "server_module",
    purpose: "Existing private kernel, Command 0-16, evidence, legal, public trust, Local Day One, and one next action gates.",
    canonicalOwner: "Existing kernel foundation",
    importsOrUsedBy: ["founder APIs", "ALKON chat", "devices", "Founder Command", "tests"],
    productTruthImpact: "Prevents duplicate kernel and unsafe execution.",
    risk: "critical",
    recommendation: "Canonicalize as the base of any future Universe Operating Kernel; never duplicate.",
    evidence: ["reports/alkon-kernel-status.md", "tests/regression/alkon-complete-sovereign-kernel.spec.ts"],
  },
  {
    id: "module_jar",
    label: "Jar Build System",
    category: "primary",
    layer: "jar",
    path: "lib/server/jar-build/*",
    type: "server_module",
    purpose: "Private intake/classification/exit-permit/memory system.",
    canonicalOwner: "Jar intake filter",
    importsOrUsedBy: ["/founder/alkon", "Founder Command", "tests"],
    productTruthImpact: "Prevents direct execution without classification.",
    risk: "high",
    recommendation: "Keep primary and private.",
    evidence: ["reports/alkon-jar-status.md"],
  },
  {
    id: "module_reality_conversion",
    label: "Reality Conversion",
    category: "primary",
    layer: "reality_conversion",
    path: "lib/server/reality-conversion/*",
    type: "server_module",
    purpose: "Reality passports/resources/status for idea-to-reality governance.",
    canonicalOwner: "Reality Conversion system",
    importsOrUsedBy: ["Founder Command", "reports"],
    productTruthImpact: "Keeps future work evidence-backed and gated.",
    risk: "medium",
    recommendation: "Keep primary supporting governance.",
    evidence: ["reports/alkon-reality-conversion-status.md"],
  },
  {
    id: "module_existence_architecture",
    label: "Permission-to-Exist",
    category: "primary",
    layer: "permission_to_exist",
    path: "lib/server/existence-architecture/*",
    type: "server_module",
    purpose: "Classifies entities by purpose, owner, visibility, boundary, evidence, lifecycle, and next fate.",
    canonicalOwner: "Permission-to-Exist system",
    importsOrUsedBy: ["founder existence APIs", "tests"],
    productTruthImpact: "Prevents unowned files/routes/APIs/components.",
    risk: "high",
    recommendation: "Keep primary and connect to architecture registry in later cleanup.",
    evidence: ["reports/alkon-permission-to-exist-status.md"],
  },
  {
    id: "module_product_truth",
    label: "Product Truth engine",
    category: "primary",
    layer: "product_truth",
    path: "lib/server/product/truth.ts",
    type: "server_module",
    purpose: "Canonical safety truth for live execution, real money, broker, billing, launch, claims, native apps, and founder controls.",
    canonicalOwner: "Product Truth",
    importsOrUsedBy: ["many server modules", "app/api/product/truth/route.ts", "tests"],
    productTruthImpact: "Overrides all automation and visuals.",
    risk: "critical",
    recommendation: "Protect as primary source of Product Truth.",
    evidence: ["tests/regression/verified-platform-truth.spec.ts"],
  },
  {
    id: "module_brand_clearance",
    label: "Brand Clearance",
    category: "protected",
    layer: "brand_gate",
    path: "lib/server/brand-clearance/*",
    type: "server_module",
    purpose: "Working-name risk, candidate generation, search tasks, adoption gate, and migration plan.",
    canonicalOwner: "Brand Gate",
    importsOrUsedBy: ["founder brand APIs", "tests"],
    productTruthImpact: "Blocks global public launch and ownership claims.",
    risk: "high",
    recommendation: "Protect; keep deferred/frozen until Ahmad reopens.",
    evidence: ["reports/global-brand-clearance-status.md", "reports/brand-name-freeze-status.md"],
  },
  {
    id: "module_infinite_growth",
    label: "Infinite Growth",
    category: "compatibility",
    layer: "kernel",
    path: "lib/server/infinite-growth/*",
    type: "server_module",
    purpose: "Governed growth constitution, gates, safe creation domains, and sample decisions.",
    canonicalOwner: "Governed growth compatibility",
    importsOrUsedBy: ["founder APIs", "ALKON state", "Founder Command", "tests"],
    productTruthImpact: "Blocks billing, launch, production, broker/feed, live execution, real money, and regulated activity.",
    risk: "high",
    recommendation: "Keep compatibility; do not declare Infinity Mode active.",
    evidence: ["tests/regression/infinite-growth-swiss-law-constitution.spec.ts"],
  },
  {
    id: "module_earth_reality",
    label: "Earth Reality server modules",
    category: "compatibility",
    layer: "living_earth_reality",
    path: "lib/server/earth-reality/*",
    type: "server_module",
    purpose: "Server-side Earth reality checks for time, place/privacy, market, law/trust, environment, and product truth.",
    canonicalOwner: "Living Earth Reality compatibility",
    importsOrUsedBy: ["earth-reality APIs", "tests"],
    productTruthImpact: "Keeps reality features labeled and bounded.",
    risk: "medium",
    recommendation: "Map into Earth Planet/Living Earth Reality in controlled cleanup.",
    evidence: ["reports/full-project-state-inventory.md"],
  },
  {
    id: "module_planet_parallel",
    label: "Planet systems",
    category: "cleanup_candidate",
    layer: "earth_planet",
    path: "lib/server/planet-*/*, app/api/planet/*",
    type: "server_module",
    purpose: "Parallel planet OS/consciousness/memory/event/world systems.",
    canonicalOwner: "Unresolved planet architecture",
    importsOrUsedBy: ["planet APIs", "planet regression tests"],
    productTruthImpact: "Can conflict with Earth Planet if reused without canonical map.",
    risk: "high",
    recommendation: "Do not delete; classify and merge under Earth Planet only after Ahmad accepts target hierarchy mapping.",
    evidence: ["reports/duplicates-and-conflicts-audit.md"],
  },
  {
    id: "module_platform_native",
    label: "Desktop/mobile strategy",
    category: "protected",
    layer: "desktop_mobile_strategy",
    path: "lib/server/platform/*",
    type: "server_module",
    purpose: "Desktop/mobile foundation and productization readiness contracts.",
    canonicalOwner: "Private Ahmad-only app strategy gate",
    importsOrUsedBy: ["platform APIs", "diagnostics"],
    productTruthImpact: "Prevents native app release claims without runtime architecture.",
    risk: "medium",
    recommendation: "Keep strategy-only; do not implement native apps here.",
    evidence: ["reports/private-ahmad-only-desktop-mobile-apps-strategy-gate.md"],
  },
  {
    id: "client_living_universe",
    label: "Living Universe client engine",
    category: "primary",
    layer: "living_earth_reality",
    path: "lib/client/living-universe/*",
    type: "client_module",
    purpose: "Device time/date, phase, season, mood, visual tokens, reality sources, asset set, and soundscape profiles.",
    canonicalOwner: "Living Earth Reality client engine",
    importsOrUsedBy: ["app/_components/ProMaxLivingEarth.tsx", "ProMaxRealitySourceBar", "tests"],
    productTruthImpact: "Labels real-sourced and simulated reality features.",
    risk: "medium",
    recommendation: "Keep primary and do not claim real weather/location/exact sun position.",
    evidence: ["reports/living-universe-with-assets-closure.md"],
  },
  {
    id: "component_cosmic_identity",
    label: "ProMaxCosmicIdentity",
    category: "primary",
    layer: "earth_planet",
    path: "app/_components/ProMaxCosmicIdentity.tsx",
    type: "component",
    purpose: "Canonical Earth/Moon/Swiss red identity wrapper for private and product surfaces.",
    canonicalOwner: "Earth Planet visual identity",
    importsOrUsedBy: ["/founder/universe", "/trading", "Pro Max Center"],
    productTruthImpact: "Visual identity only; no NASA, Swiss government, FINMA, or legal claim.",
    risk: "medium",
    recommendation: "Keep primary Earth/Moon identity.",
    evidence: ["reports/hyper-real-earth-immersion-style-closure.md"],
  },
  {
    id: "component_living_earth",
    label: "App-level ProMaxLivingEarth",
    category: "primary",
    layer: "earth_planet",
    path: "app/_components/ProMaxLivingEarth.tsx",
    type: "component",
    purpose: "Code-driven realistic/procedural Earth with clouds, atmosphere, night lights, and reduced motion support.",
    canonicalOwner: "Earth Planet globe renderer",
    importsOrUsedBy: ["ProMaxCosmicIdentity", "tests"],
    productTruthImpact: "Keeps Earth local/procedural/license-safe and simulation-labeled.",
    risk: "medium",
    recommendation: "Keep primary globe renderer.",
    evidence: ["reports/promax-earth-identity-visual-closure.md"],
  },
  {
    id: "component_earth_identity_wrapper",
    label: "ProMaxEarthIdentity",
    category: "compatibility",
    layer: "earth_planet",
    path: "app/_components/ProMaxEarthIdentity.tsx",
    type: "component",
    purpose: "Compatibility wrapper around app-level Living Earth.",
    canonicalOwner: "Earth identity compatibility",
    importsOrUsedBy: ["tests/regression/promax-earth-identity-closure.spec.ts"],
    productTruthImpact: "Should not become a separate logo truth.",
    risk: "low",
    recommendation: "Keep as wrapper or migrate references to ProMaxCosmicIdentity.",
    evidence: ["reports/duplicates-and-conflicts-audit.md"],
  },
  {
    id: "component_brand_legacy",
    label: "Module brand Earth/logo components",
    category: "cleanup_candidate",
    layer: "public_pro_max_future",
    path: "modules/brand/components/*",
    type: "component",
    purpose: "Older ProductLogo, TPMEarthMark, ProMaxEarthMark, LivingEarthBackground, and module-level Earth components.",
    canonicalOwner: "Public brand compatibility",
    importsOrUsedBy: ["PublicProductEntry", "PublicAppShell", "legacy tests"],
    productTruthImpact: "Can fragment public visual identity if deepened separately.",
    risk: "medium",
    recommendation: "Do not delete; migrate or wrap behind primary identity in controlled cleanup.",
    evidence: ["reports/duplicates-and-conflicts-audit.md"],
  },
  {
    id: "component_reality_sources",
    label: "Reality Source and Continuity components",
    category: "primary",
    layer: "living_earth_reality",
    path: "app/_components/ProMaxRealitySourceBar.tsx, app/_components/ProMaxRealityContinuityLayer.tsx",
    type: "component",
    purpose: "Visible source labels for real/simulated/not-connected features.",
    canonicalOwner: "Reality source UI",
    importsOrUsedBy: ["/founder/universe", "/trading", "Pro Max Center"],
    productTruthImpact: "Prevents fake weather/location/legal/trading claims.",
    risk: "medium",
    recommendation: "Keep primary source-label UI.",
    evidence: ["tests/regression/hyper-real-earth-immersion-style-closure.spec.ts"],
  },
  {
    id: "component_soundscape",
    label: "Universe Soundscape",
    category: "protected",
    layer: "living_earth_reality",
    path: "app/_components/ProMaxUniverseSoundscape.tsx",
    type: "component",
    purpose: "User-controlled/off-by-default generated soundscape.",
    canonicalOwner: "Soundscape consent boundary",
    importsOrUsedBy: ["/founder/universe"],
    productTruthImpact: "No autoplay, no external audio, no public claim.",
    risk: "medium",
    recommendation: "Protect consent/off-by-default behavior.",
    evidence: ["reports/living-universe-with-assets-closure.md"],
  },
  {
    id: "component_trading_floor",
    label: "Trading floor components",
    category: "primary",
    layer: "trading_surface",
    path: "app/trading/_components/*",
    type: "component",
    purpose: "Trading command bar, chart, market watch, execution/risk, positions/activity, ALKON truth, and Product Truth strip.",
    canonicalOwner: "Trading surface on Earth Planet",
    importsOrUsedBy: ["/trading"],
    productTruthImpact: "Keeps chart priority, paper/demo safety, and blocked real execution.",
    risk: "high",
    recommendation: "Keep primary; later update wording from Pro Max Earth to Earth Planet if Ahmad approves canonical mapping.",
    evidence: ["reports/trading-premium-visual-realism-closure.md"],
  },
  {
    id: "style_earth_immersion",
    label: "Earth immersion tokens",
    category: "primary",
    layer: "living_earth_reality",
    path: "app/_styles/earth-immersion-tokens.css, lib/client/living-universe/earthImmersionTokens.ts",
    type: "style",
    purpose: "Shared time/season/atmosphere/Swiss red/panel depth style tokens.",
    canonicalOwner: "Inside/outside Earth continuity style",
    importsOrUsedBy: ["app/layout.tsx", "living universe components"],
    productTruthImpact: "Visual only; simulation remains labeled.",
    risk: "low",
    recommendation: "Keep primary style token source.",
    evidence: ["reports/hyper-real-earth-immersion-style-closure.md"],
  },
  {
    id: "asset_manifest",
    label: "Pro Max legal-safe asset manifest",
    category: "protected",
    layer: "living_earth_reality",
    path: "public/assets/promax/asset-manifest.json",
    type: "asset",
    purpose: "Local/procedural/license-safe asset manifest for Earth/universe visuals.",
    canonicalOwner: "Visual asset policy",
    importsOrUsedBy: ["living-universe asset set", "tests"],
    productTruthImpact: "Blocks random/unlicensed/NASA/official Swiss assets.",
    risk: "high",
    recommendation: "Protect; no public-launch asset approval without review.",
    evidence: ["docs/product/promax-visual-asset-policy.md"],
  },
  {
    id: "docs_professional_standard",
    label: "Project Universe Professional Standard",
    category: "primary",
    layer: "reports_docs_tests",
    path: "docs/product/project-universe-professional-standard.md",
    type: "doc",
    purpose: "Professional, visual, legal-safe, Product Truth, ALKON boundary, and inside/outside continuity standard.",
    canonicalOwner: "Professional standard documentation",
    importsOrUsedBy: ["tests/regression/hyper-real-earth-immersion-style-closure.spec.ts"],
    productTruthImpact: "Preserves forbidden claims and visual source honesty.",
    risk: "medium",
    recommendation: "Keep primary standard and align it with the created universe constitution.",
    evidence: ["reports/hyper-real-earth-immersion-style-closure.md"],
  },
  {
    id: "docs_missing_universe_constitution",
    label: "Universe Constitution",
    category: "primary",
    layer: "alkawn_universe",
    path: "docs/product/universe-constitution.md",
    type: "doc",
    purpose: "Canonical constitution for الكون / Universe, Universe One, Swiss Local Constitution, Pro Max Galaxy, Earth Planet, Global Layer, and ALKON background support.",
    canonicalOwner: "الكون constitution",
    importsOrUsedBy: ["lib/server/universe-management/index.ts", "reports/controlled-canonical-cleanup.md"],
    productTruthImpact: "Needed before Ultimate Depth or Infinity Mode can resume safely.",
    risk: "high",
    recommendation: "Keep as highest truth document; do not use it to build new layers until kernel and remaining cleanup pass.",
    evidence: ["reports/full-project-state-inventory.md", "reports/controlled-canonical-cleanup.md"],
  },
  {
    id: "docs_missing_code_architecture",
    label: "Canonical Code Architecture",
    category: "primary",
    layer: "reports_docs_tests",
    path: "docs/product/canonical-code-architecture.md",
    type: "doc",
    purpose: "Canonical code architecture map defining imports, ownership, compatibility paths, and no-second-kernel rule.",
    canonicalOwner: "Architecture cleanup documentation",
    importsOrUsedBy: [],
    productTruthImpact: "Needed to prevent duplicate kernels/components/routes.",
    risk: "medium",
    recommendation: "Keep primary architecture guide; use it before kernel canonicalization and any deeper missions.",
    evidence: ["reports/full-project-state-inventory.md", "reports/controlled-canonical-cleanup.md"],
  },
  {
    id: "reports_current_inventory",
    label: "Current inventory reports",
    category: "primary",
    layer: "reports_docs_tests",
    path: "reports/full-project-state-inventory.md, reports/current-canonical-state-map.md, reports/duplicates-and-conflicts-audit.md, reports/next-safe-action-after-inventory.md",
    type: "report",
    purpose: "Latest factual inventory and safest next action.",
    canonicalOwner: "Reality inventory evidence",
    importsOrUsedBy: ["Ahmad review", "this registry"],
    productTruthImpact: "Stops deeper work until conflicts are reconciled.",
    risk: "medium",
    recommendation: "Keep primary current audit evidence.",
    evidence: ["commit 0fc9596"],
  },
  {
    id: "reports_closure_history",
    label: "Historical closure reports",
    category: "protected",
    layer: "reports_docs_tests",
    path: "reports/*closure.md, reports/alkon-*.md, reports/pro-max-*.md",
    type: "report",
    purpose: "Validated closure evidence from earlier missions.",
    canonicalOwner: "Evidence memory",
    importsOrUsedBy: ["tests", "Wake Report", "Ahmad review"],
    productTruthImpact: "Must not be deleted casually because they prove prior states.",
    risk: "medium",
    recommendation: "Protect as history; supersede through current registry rather than editing away old truth.",
    evidence: ["reports/alkon-execution-history.md"],
  },
  {
    id: "tests_current_registry",
    label: "Canonical registry regression",
    category: "primary",
    layer: "reports_docs_tests",
    path: "tests/regression/canonical-architecture-registry.spec.ts",
    type: "test",
    purpose: "Protects private registry UI, blocked Infinity Mode wording, Product Truth, and forbidden claims.",
    canonicalOwner: "Registry evidence test",
    importsOrUsedBy: ["validation"],
    productTruthImpact: "Prevents claims that Infinity Mode or unsafe activation is active.",
    risk: "medium",
    recommendation: "Keep primary focused regression.",
    evidence: ["reports/canonical-architecture-registry.md"],
  },
  {
    id: "tests_old_hierarchy",
    label: "Old hierarchy regressions",
    category: "compatibility",
    layer: "reports_docs_tests",
    path: "tests/regression/private-universe-public-promax-layering-closure.spec.ts, tests/regression/deep-literal-universe-order-closure.spec.ts",
    type: "test",
    purpose: "Protects previous validated hierarchy while canonical cleanup is pending.",
    canonicalOwner: "Compatibility test layer",
    importsOrUsedBy: ["npm run test:regression"],
    productTruthImpact: "Prevents accidental public leak or ALKON layer inversion.",
    risk: "medium",
    recommendation: "Keep compatibility tests until target hierarchy is approved and tests are updated.",
    evidence: ["reports/current-canonical-state-map.md"],
  },
  {
    id: "target_alkawn",
    label: "الكون / Universe target meaning",
    category: "needs_ahmad_decision",
    layer: "alkawn_universe",
    path: "target-model: الكون / Universe",
    type: "doc",
    purpose: "Founder-facing private electronic self / main private project meaning.",
    canonicalOwner: "Ahmad final meaning",
    importsOrUsedBy: [],
    productTruthImpact: "Sensitive private founder meaning; must not be public.",
    risk: "critical",
    recommendation: "Needs Ahmad-approved canonical wording before code hierarchy update.",
    evidence: ["reports/full-project-state-inventory.md"],
  },
  {
    id: "target_digital_vault",
    label: "Ahmad Digital Vault",
    category: "needs_ahmad_decision",
    layer: "ahmad_digital_vault",
    path: "target-model: Ahmad Digital Vault",
    type: "server_module",
    purpose: "Private documents/secrets/memory/decisions concept.",
    canonicalOwner: "Ahmad private vault strategy",
    importsOrUsedBy: [],
    productTruthImpact: "Could involve sensitive data; must not store raw personal documents without explicit gates.",
    risk: "critical",
    recommendation: "Needs Ahmad decision and security design before implementation.",
    evidence: ["reports/next-safe-action-after-inventory.md"],
  },
  {
    id: "target_protection_core",
    label: "Protection Core",
    category: "needs_ahmad_decision",
    layer: "protection_core",
    path: "target-model: Protection Core",
    type: "server_module",
    purpose: "Protection, permissions, audit, kill switch concept.",
    canonicalOwner: "Future protection architecture",
    importsOrUsedBy: [],
    productTruthImpact: "Security-sensitive and must be designed before build.",
    risk: "critical",
    recommendation: "Needs explicit architecture and Ahmad approval.",
    evidence: ["reports/next-safe-action-after-inventory.md"],
  },
  {
    id: "target_universe_one",
    label: "Universe One",
    category: "needs_ahmad_decision",
    layer: "universe_one",
    path: "target-model: Universe One",
    type: "server_module",
    purpose: "Literal living reality system concept.",
    canonicalOwner: "Future Universe One registry",
    importsOrUsedBy: [],
    productTruthImpact: "Must remain real when sourced and simulated when labeled.",
    risk: "high",
    recommendation: "Define as canonical target before implementation.",
    evidence: ["reports/current-canonical-state-map.md"],
  },
  {
    id: "target_swiss_constitution",
    label: "Swiss Local Constitution",
    category: "needs_ahmad_decision",
    layer: "swiss_local_constitution",
    path: "target-model: Swiss Local Constitution",
    type: "doc",
    purpose: "Local Swiss review layer above Global Layer.",
    canonicalOwner: "Future Swiss Local Constitution",
    importsOrUsedBy: [],
    productTruthImpact: "Must not imply Swiss government, FINMA, license, or legal approval.",
    risk: "critical",
    recommendation: "Define carefully with legal-review-pending language.",
    evidence: ["reports/project-universe-compliance-readiness-gate.md"],
  },
  {
    id: "target_pro_max_galaxy",
    label: "Pro Max Galaxy",
    category: "needs_ahmad_decision",
    layer: "pro_max_galaxy",
    path: "target-model: Pro Max Galaxy",
    type: "doc",
    purpose: "Product galaxy inside الكون.",
    canonicalOwner: "Future Pro Max Galaxy layer",
    importsOrUsedBy: [],
    productTruthImpact: "Must preserve Pro Max working_name_only and public launch block.",
    risk: "high",
    recommendation: "Define before moving Pro Max Earth/Earth Planet naming.",
    evidence: ["reports/current-canonical-state-map.md"],
  },
  {
    id: "target_earth_planet",
    label: "Earth Planet",
    category: "needs_ahmad_decision",
    layer: "earth_planet",
    path: "target-model: Earth Planet",
    type: "doc",
    purpose: "First planet / complete trading project inside Pro Max Galaxy.",
    canonicalOwner: "Future Earth Planet layer",
    importsOrUsedBy: [],
    productTruthImpact: "Must preserve trading demo/read-only and blocked public launch.",
    risk: "high",
    recommendation: "Map current Pro Max Earth to Earth Planet after Ahmad approves naming relationship.",
    evidence: ["reports/full-project-state-inventory.md"],
  },
  {
    id: "target_global_layer",
    label: "Global Layer",
    category: "needs_ahmad_decision",
    layer: "global_layer",
    path: "target-model: Global Layer",
    type: "doc",
    purpose: "Future global layer under Swiss Local Constitution.",
    canonicalOwner: "Future Global Layer",
    importsOrUsedBy: [],
    productTruthImpact: "Public/global launch remains blocked until all gates close.",
    risk: "critical",
    recommendation: "Define as future/blocked before any global launch work.",
    evidence: ["reports/global-brand-clearance-status.md"],
  },
];
