import type { AlkonRouteDecision, AlkonSignal, AlkonSignalType } from "./types";

type RouteTemplate = Omit<AlkonRouteDecision, "signalId">;

const ROUTES: Record<AlkonSignalType, RouteTemplate> = {
  founder_idea: {
    ownerSystem: "Alkon Command",
    supportingSystems: ["Founder Idea Inbox", "Codex Construction", "Product Memory"],
    responsibleWorker: "Alkon Report Worker",
    requiredMonitors: ["Memory Satellite", "Validation Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Product Memory",
  },
  visual_rejection: {
    ownerSystem: "Visual Identity",
    supportingSystems: ["Product Memory", "Result Tribunal"],
    responsibleWorker: "Logo Identity Worker",
    requiredMonitors: ["Logo Satellite", "Screenshot Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Visual Memory",
  },
  chart_annoyance: {
    ownerSystem: "Trading Workspace",
    supportingSystems: ["Visual Identity", "Result Tribunal"],
    responsibleWorker: "Chart Comfort Worker",
    requiredMonitors: ["Chart Satellite", "Screenshot Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Visual Memory",
  },
  public_ui_gap: {
    ownerSystem: "Public Earth",
    supportingSystems: ["Shell / Navigation", "Product Truth"],
    responsibleWorker: "Public Navigation Worker",
    requiredMonitors: ["Public UI Satellite", "Public Boundary Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Product Memory",
  },
  shell_duplication: {
    ownerSystem: "Shell / Navigation",
    supportingSystems: ["Trading Workspace", "Public Earth", "Result Tribunal"],
    responsibleWorker: "Public Navigation Worker",
    requiredMonitors: ["Public UI Satellite", "Chart Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Product Memory",
  },
  logo_rejection: {
    ownerSystem: "Visual Identity",
    supportingSystems: ["Public Earth", "Product Memory"],
    responsibleWorker: "Logo Identity Worker",
    requiredMonitors: ["Logo Satellite", "Screenshot Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Visual Memory",
  },
  build_failure: {
    ownerSystem: "Codex Construction",
    supportingSystems: ["Result Tribunal", "Product Memory"],
    responsibleWorker: "Diagnostics Worker",
    requiredMonitors: ["Validation Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Product Memory",
  },
  validation_failure: {
    ownerSystem: "Result Tribunal",
    supportingSystems: ["Codex Construction", "Product Memory"],
    responsibleWorker: "Result Tribunal Worker",
    requiredMonitors: ["Validation Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Product Memory",
  },
  public_private_leak: {
    ownerSystem: "Security Sovereignty",
    supportingSystems: ["Public Earth", "Secrets Authority", "Product Memory"],
    responsibleWorker: "Security Gate Worker",
    requiredMonitors: ["Public Boundary Satellite", "Security Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Security Memory",
  },
  secret_risk: {
    ownerSystem: "Secrets Authority",
    supportingSystems: ["Security Sovereignty", "Result Tribunal"],
    responsibleWorker: "Secrets Safety Worker",
    requiredMonitors: ["Secrets Satellite", "Security Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Security Memory",
  },
  billing_request: {
    ownerSystem: "Launch Readiness",
    supportingSystems: ["Product Truth", "Legal/Guardian"],
    responsibleWorker: "Security Gate Worker",
    requiredMonitors: ["Product Truth Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Product Memory",
  },
  live_request: {
    ownerSystem: "Trading Workspace",
    supportingSystems: ["Security Sovereignty", "Product Truth"],
    responsibleWorker: "Security Gate Worker",
    requiredMonitors: ["Product Truth Satellite", "Security Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Security Memory",
  },
  broker_feed_request: {
    ownerSystem: "Markets",
    supportingSystems: ["Product Truth", "Launch Readiness"],
    responsibleWorker: "Markets Worker",
    requiredMonitors: ["Product Truth Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Product Memory",
  },
  social_publish_request: {
    ownerSystem: "Launch Readiness",
    supportingSystems: ["World Interface", "Legal/Guardian"],
    responsibleWorker: "Security Gate Worker",
    requiredMonitors: ["World Interface Satellite", "Security Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Security Memory",
  },
  launch_request: {
    ownerSystem: "Launch Readiness",
    supportingSystems: ["Legal/Guardian", "Support", "Security Sovereignty"],
    responsibleWorker: "Alkon Report Worker",
    requiredMonitors: ["Product Truth Satellite", "Validation Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Product Memory",
  },
  codex_result: {
    ownerSystem: "Result Tribunal",
    supportingSystems: ["Codex Construction", "Product Memory"],
    responsibleWorker: "Result Tribunal Worker",
    requiredMonitors: ["Validation Satellite", "Memory Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Product Memory",
  },
  local_day_signal: {
    ownerSystem: "Alkon Command",
    supportingSystems: ["Product Memory", "Local Day Loop"],
    responsibleWorker: "Alkon Report Worker",
    requiredMonitors: ["Local Day Satellite", "Memory Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Product Memory",
  },
  support_gap: {
    ownerSystem: "Support",
    supportingSystems: ["Public Earth", "Product Truth"],
    responsibleWorker: "Support Readiness Worker",
    requiredMonitors: ["Public UI Satellite", "Product Truth Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Product Memory",
  },
  apps_gap: {
    ownerSystem: "Apps / Platforms",
    supportingSystems: ["Public Earth", "Product Truth"],
    responsibleWorker: "Apps Platforms Worker",
    requiredMonitors: ["Public UI Satellite", "Product Truth Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Product Memory",
  },
  assistant_gap: {
    ownerSystem: "TPM Assistant",
    supportingSystems: ["Product Truth", "Personal Reality"],
    responsibleWorker: "TPM Assistant Worker",
    requiredMonitors: ["Assistant Satellite", "Product Truth Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Product Memory",
  },
  environment_signal: {
    ownerSystem: "Planetary Environment",
    supportingSystems: ["Public Earth", "Diagnostics"],
    responsibleWorker: "Diagnostics Worker",
    requiredMonitors: ["Validation Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Product Memory",
  },
  weather_signal: {
    ownerSystem: "Planetary Environment",
    supportingSystems: ["Privacy", "Diagnostics"],
    responsibleWorker: "Diagnostics Worker",
    requiredMonitors: ["Validation Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Product Memory",
  },
  market_session_signal: {
    ownerSystem: "Markets",
    supportingSystems: ["Planetary Environment", "Product Truth"],
    responsibleWorker: "Markets Worker",
    requiredMonitors: ["Product Truth Satellite"],
    reportTarget: "Founder Command",
    memoryTarget: "Product Memory",
  },
};

export function routeAlkonSignal(signal: AlkonSignal): AlkonRouteDecision {
  return {
    signalId: signal.signalId,
    ...ROUTES[signal.type],
  };
}

export function routeAlkonSignals(signals: AlkonSignal[]) {
  return signals.map(routeAlkonSignal);
}
